### ISSUE TITLE
leveling emror

### ISSUE THREAD

**Issue by Fucksociety666** [SlavyanDesu/BocchiBot#103]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![Screenshot pada 2020-12-25 22-37-33](https://user-images.githubusercontent.com/74858900/103138118-4a110e00-46c7-11eb-9b51-a5e7c48002d6.png)

**Comment by Fucksociety666** [comment]
> Hello! Thanks for submiting the issue, we will respond to you ASAP.

kalo done bilang

**Comment by VideFrelan** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context**
> Add any other context about the problem here.
> ![Screenshot pada 2020-12-25 22-37-33](https://user-images.githubusercontent.com/74858900/103138118-4a110e00-46c7-11eb-9b51-a5e7c48002d6.png)

Ini bot Bocchi kah? ato bot lain tapi ngambil leveling dari Bocchi?

**Comment by VideFrelan** [comment]
Kalau belom bisa juga, coba ganti berikut:

case 'leveling':
                if (!isRegistered) return await bocchi.reply(from, ind.notRegistered(), id)
                if (!isGroupMsg) return await bocchi.reply(from, ind.groupOnly(), id)
                if (!isGroupAdmins) return await bocchi.reply(from, ind.adminOnly(), id)
                if (ar[0] == 'enable') {
                    if (isLevelingOn) return await bocchi.reply(from, ind.levelingOnAlready(), id)
                    _leveling.push(chat.id)
                    fs.writeFileSync('./database/leveling.json', JSON.stringify(_leveling))
                    await bocchi.reply(from, ind.levelingOn(), id)
                } else if (ar[0] == 'disable') {
                    _leveling.splice(chat.id, 1)
                    fs.writeFileSync('./database/leveling.json', JSON.stringify(_leveling))
                    await bocchi.reply(from, ind.levelingOff(), id)
                } else {
                    await bocchi.reply(from, ind.wrongFormat(), id)
                }
            break

**Comment by Fucksociety666** [comment]
sm aj format salah

**Comment by Fucksociety666** [comment]
dh done
thanks
