### ISSUE TITLE
Req

### ISSUE THREAD

**Issue by uukina** [SlavyanDesu/BocchiBot#105]
req terjemahan alquran bang 🙏

**Comment by albertstyles312** [comment]
req ini dong bang
https://docs-jojo.herokuapp.com/api/alkitabsearch?q=Matius
https://api.vhtear.com/ongoinganoboy&apikey=asfaagasgagaga
https://api.vhtear.com/cekongkir?kurir=jne&fromcity=surabaya&tocity=semarang&apikey=asgaksjgashghuasg
https://api.vhtear.com/downloadfilm?judul=joker&apikey=aagatgassagasgasg
https://enznoire.herokuapp.com/neonime?q=danmachi

:V

**Comment by VideFrelan** [comment]
> req terjemahan alquran bang

Cek pull ku

**Comment by VideFrelan** [comment]
> req ini juga dong bang
> https://docs-jojo.herokuapp.com/api/alkitabsearch?q=Matius
> https://api.vhtear.com/ongoinganoboy&apikey=asfaagasgagaga
> https://api.vhtear.com/cekongkir?kurir=jne&fromcity=surabaya&tocity=semarang&apikey=asgaksjgashghuasg
> https://api.vhtear.com/downloadfilm?judul=joker&apikey=aagatgassagasgasg
> https://enznoire.herokuapp.com/neolatest
> https://melodicxt.herokuapp.com/api/anitoki?apiKey=administrator
> 
> :V

Untuk alkitab cek pull, yg lainnya nanti ya mau istirahat wkwkwk

**Comment by uukina** [comment]
> > req terjemahan alquran bang
> 
> Cek pull ane

Naiss, tengkyuu

**Comment by VideFrelan** [comment]
> req ini juga dong bang
> https://docs-jojo.herokuapp.com/api/alkitabsearch?q=Matius
> https://api.vhtear.com/ongoinganoboy&apikey=asfaagasgagaga
> https://api.vhtear.com/cekongkir?kurir=jne&fromcity=surabaya&tocity=semarang&apikey=asgaksjgashghuasg
> https://api.vhtear.com/downloadfilm?judul=joker&apikey=aagatgassagasgasg
> https://enznoire.herokuapp.com/neolatest
> https://melodicxt.herokuapp.com/api/anitoki?apiKey=administrator
> 
> :V

Done, cek pull

**Comment by SlavyanDesu** [comment]
@albertstyles312 ini anime fetcher-nya mau beda-beda?

**Comment by albertstyles312** [comment]
iya kalo bisa hehe

**Comment by SlavyanDesu** [comment]
> iya kalo bisa hehe

done, silakan update.
