### ISSUE TITLE
Error: Could not parse font file

### ISSUE THREAD

**Issue by devil-slayer141** [SlavyanDesu/BocchiBot#125]
(node:7940) UnhandledPromiseRejectionWarning: Error: Could not parse font file
    at Object.registerFont (C:\Users\muazm\OneDrive\Desktop\Rҽɳα Kҽιƙσ-bot\node_modules\canvas\index.js:48:17)
    at Function.registerFonts (C:\Users\muazm\OneDrive\Desktop\Rҽɳα Kҽιƙσ-bot\node_modules\canvacord\src\Canvacord.js:381:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7940) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7940) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by SlavyanDesu** [comment]
Need more details on this one, but you can try to reinstall `canvacord` module by typing:
```bash
> npm uninstall canvacord
> npm install canvacord
```

**Comment by devil-slayer141** [comment]
I did try but it's showing eerror! what code do i need for that?

**Comment by SlavyanDesu** [comment]
> I did try but it's showing eerror! what code do i need for that?

is that the same error or different?

**Comment by devil-slayer141** [comment]
Same error

**Comment by VideFrelan** [comment]
If this issue still continues, feel free to reopen this issue.

or if you want a quick response please join our whatsapp group: [here](https://chat.whatsapp.com/KSG5C4SGlT2IpRtFm05owkl)
