### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by arifrahmanulhakim** [SlavyanDesu/BocchiBot#129]
Sorry, can u help me? whats wrong with this [error?]
https://ibb.co/1smhBwq

**Comment by SlavyanDesu** [comment]
> Sorry, can u help me? whats wrong with this [error?]
> https://ibb.co/1smhBwq

can you give more details on this error? like when did error occurs

**Comment by arifrahmanulhakim** [comment]
> > Sorry, can u help me? whats wrong with this [error?]
> > https://ibb.co/1smhBwq
> 
> can you give more details on this error? like when did error occurs

I installed perfectly without errors, but when I use the command an error appears like in the ss :(

**Comment by arifrahmanulhakim** [comment]
> > > Sorry, can u help me? whats wrong with this [error?]
> > > https://ibb.co/1smhBwq
> > 
> > 
> > can you give more details on this error? like when did error occurs
> 
> I installed perfectly without errors, but when I use the command an error appears like in the ss :(

[CMD] 31/12/20 00:34:08 menu [0] from ? gea ?
[ERROR] Error: Evaluation failed: TypeError: Cannot read property 'toString' of
undefined
    at Object.initialize (https://web.whatsapp.com/app2.70dd0e66cffd251e7689.js:
2:552779)
    at new b (https://web.whatsapp.com/app.6be31a9914b3f8e528be.js:1:693760)
    at new $ (https://web.whatsapp.com/app.6be31a9914b3f8e528be.js:1:266526)
    at https://web.whatsapp.com/app2.70dd0e66cffd251e7689.js:2:402139
    at Array.filter (<anonymous>)
    at B.add (https://web.whatsapp.com/app2.70dd0e66cffd251e7689.js:2:402076)
    at https://web.whatsapp.com/app2.70dd0e66cffd251e7689.js:2:796078
    at z (https://web.whatsapp.com/app.6be31a9914b3f8e528be.js:1:971235)
    at MutationObserver.V (https://web.whatsapp.com/app.6be31a9914b3f8e528be.js:
1:970816)
    at ExecutionContext._evaluateInternal (C:\bocchi\node_modules\puppeteer\lib\
cjs\puppeteer\common\ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (C:\bocchi\node_modules\puppeteer\lib\cjs
\puppeteer\common\ExecutionContext.js:106:16)

**Comment by SlavyanDesu** [comment]
Try to update the source code
```bash
> git pull origin master
> npm install
> npm update
```
Hope this help

**Comment by arifrahmanulhakim** [comment]
> Try to update the source code
> 
> ```shell
> > git pull origin master
> > npm install
> > npm update
> ```
> 
> Hope this help

thank you for helping, sadly that error still appear

**Comment by VideFrelan** [comment]
> > Try to update the source code
> > ```shell
> > > git pull origin master
> > > npm install
> > > npm update
> > ```
> > 
> > 
> > Hope this help
> 
> thank you for helping, sadly that error still appear

Pakai bindo aja ngab kalo orang indo, btw ini error setelah agan nambahin fitur atau gimana?

**Comment by arifrahmanulhakim** [comment]
> > > Try to update the source code
> > > ```shell
> > > > git pull origin master
> > > > npm install
> > > > npm update
> > > ```
> > > 
> > > 
> > > Hope this help
> > 
> > 
> > thank you for helping, sadly that error still appear
> 
> Pakai bindo aja ngab kalo orang indo, btw ini error setelah agan nambahin fitur atau gimana?

oh iya :v, jadi gue barusan download sc nya, nah ga ada diapain2 cuman ganti prefix sama key doang , pas ketik semua menu ga bisa munculkek gtu

**Comment by SlavyanDesu** [comment]
Coba fotokan file yang kamu ubah

**Comment by arifrahmanulhakim** [comment]
> Coba fotokan file yang kamu ubah

udah 2x update, cuman edit ini aja, tapi muncul error tosting itu https://ibb.co/Wcgy5NG

**Comment by SlavyanDesu** [comment]
Coba prefix jangan @ takut tabrakan

**Comment by VideFrelan** [comment]
> > Coba fotokan file yang kamu ubah
> 
> udah 2x update, cuman edit ini aja, tapi muncul error tosting itu https://ibb.co/Wcgy5NG

Barusan ane coba pakai prefix yg agan ss, ga terjadi masalah kok

**Comment by SlavyanDesu** [comment]
Keknya ini mah open-wa masalahnya, coba hapus folder `node-modules` lalu npm install lagi

**Comment by arifrahmanulhakim** [comment]
Terima kasih banyak, Udah fix, entah mengapa setelah ganti nomor wa baru bisa
