### ISSUE TITLE
req

### ISSUE THREAD

**Issue by MrPawNO** [SlavyanDesu/BocchiBot#13]
Saya kan punya api di vhtear

@SlavyanDesu Bisa tolong tambahin fitur-fitur dari vhtear ga? api.vhtear.com

Sfire,Slightning,Calender,Ttg,dll

**Comment by SlavyanDesu** [comment]
> Saya kan punya api di vhtear
> 
> @SlavyanDesu Bisa tolong tambahin fitur-fitur dari vhtear ga? api.vhtear.com
> 
> Sfire,Slightning,Calender,Ttg,dll

Silakan di-list.

**Comment by MrPawNO** [comment]
> > Saya kan punya api di vhtear
> > @SlavyanDesu Bisa tolong tambahin fitur-fitur dari vhtear ga? api.vhtear.com
> > Sfire,Slightning,Calender,Ttg,dll
> 
> Silakan di-list.

Makaasih ya gan, mubadzir soalnya kalau ga dipake

List:
- Sticker Lightning
- Sticker Fire
- Calender Maker
- Harta Tahta
- Nulis
- XXX Downloader

Thanks.

**Comment by SlavyanDesu** [comment]
> > > Saya kan punya api di vhtear
> > > @SlavyanDesu Bisa tolong tambahin fitur-fitur dari vhtear ga? api.vhtear.com
> > > Sfire,Slightning,Calender,Ttg,dll
> > 
> > 
> > Silakan di-list.
> 
> Makaasih ya gan, mubadzir soalnya kalau ga dipake
> 
> List:
> 
> * Sticker Lightning
> * Sticker Fire
> * Calender Maker
> * Harta Tahta
> * Nulis
> * XXX Downloader
> 
> Thanks.

Kalau bisa, boleh pinjam keynya buat tes gak? Kirim di DM saja. Susah soalnya kalau gak trial and error wkwk

**Comment by MrPawNO** [comment]
> > > > Saya kan punya api di vhtear
> > > > @SlavyanDesu Bisa tolong tambahin fitur-fitur dari vhtear ga? api.vhtear.com
> > > > Sfire,Slightning,Calender,Ttg,dll
> > > 
> > > 
> > > Silakan di-list.
> > 
> > 
> > Makaasih ya gan, mubadzir soalnya kalau ga dipake
> > List:
> > 
> > * Sticker Lightning
> > * Sticker Fire
> > * Calender Maker
> > * Harta Tahta
> > * Nulis
> > * XXX Downloader
> > 
> > Thanks.
> 
> Kalau bisa, boleh pinjam keynya buat tes gak? Kirim di DM saja. Susah soalnya kalau gak trial and error wkwk



> > > > Saya kan punya api di vhtear
> > > > @SlavyanDesu Bisa tolong tambahin fitur-fitur dari vhtear ga? api.vhtear.com
> > > > Sfire,Slightning,Calender,Ttg,dll
> > > 
> > > 
> > > Silakan di-list.
> > 
> > 
> > Makaasih ya gan, mubadzir soalnya kalau ga dipake
> > List:
> > 
> > * Sticker Lightning
> > * Sticker Fire
> > * Calender Maker
> > * Harta Tahta
> > * Nulis
> > * XXX Downloader
> > 
> > Thanks.
> 
> Kalau bisa, boleh pinjam keynya buat tes gak? Kirim di DM saja. Susah soalnya kalau gak trial and error wkwk

Bolehh, dm kemana gan?

IG: @videfikri

**Comment by SlavyanDesu** [comment]
[Sini](https://www.instagram.com/rl_slavyan/) broo

**Comment by SlavyanDesu** [comment]
> * XXX Downloader

Ini untuk XXX downloader mau di set default quality ke berapa pixel?

**Comment by SlavyanDesu** [comment]
Semua command yang tadi di list sudah ditambahkan, kecuali XXX. Silakan update source code dengan cara:
```bash
> git pull origin master
> npm update
```
