### ISSUE TITLE
premium Bocchi Bot

### ISSUE THREAD

**Issue by kwteen** [SlavyanDesu/BocchiBot#130]
how to add premium in Bocchi Bot?

**Comment by arifrahmanulhakim** [comment]
Use command premium? Prefix add @tagmember Or number

**Comment by VideFrelan** [comment]
> how to add premium in Bocchi Bot?


Premium database is already available on bocchibot, you only need to add if (!isPremium) return bocchi.reply(from, 'This feature is only for premium users', id)

into the command you want
And don't forget to add the user number that you want to make premium in the / premium.json database
