### ISSUE TITLE
Role

### ISSUE THREAD

**Issue by nomercylimit** [SlavyanDesu/BocchiBot#135]
**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or featur you've considered.

**Additional context**

Tambahkan sistem role pada leveling tapi sort dari xp

**Comment by nomercylimit** [comment]
help

**Comment by SlavyanDesu** [comment]
nanti

**Comment by SlavyanDesu** [comment]
@nomercylimit https://github.com/SlavyanDesu/BocchiBot/commit/3dc526bbbc50df48a949a10bbf4bbcb20c11e7c1
