### ISSUE TITLE
API key leaked when error

### ISSUE THREAD

**Issue by kiky666** [SlavyanDesu/BocchiBot#137]
Bang benerin itu dong, kalo ada yg error apikey nya ikut muncul
Atau gk pesan error nya kirim ke owner aja

**Comment by SlavyanDesu** [comment]
Wah bahaya juga, oke deh

**Comment by VideFrelan** [comment]
> Bang benerin itu dong, kalo ada yg error apikey nya ikut muncul
> Atau gk pesan error nya kirim ke owner aja

Untuk solusi sementara coba agan ganti pesan error nya

await bocchi.reply(from, err, id) ==> await bocchi.reply(from, `Ada yang Error!`, id)

**Comment by SlavyanDesu** [comment]
done ya
