### ISSUE TITLE
menu owner error

### ISSUE THREAD

**Issue by rasmaniprogrammer** [SlavyanDesu/BocchiBot#139]
bang menu owner nya error gak tau kenapa gak bisa muncul padahal udah di command $menu 9 tapi gak mau muncul itu solusinya gimana tolong respon bang

**Comment by VideFrelan** [comment]
> bang menu owner nya error gak tau kenapa gak bisa muncul padahal udah di command $menu 9 tapi gak mau muncul itu solusinya gimana tolong respon bang

Masasih gan? ada yg dirubah ga? bisa di Screenshoot case 'menu' dan exports.menuOwner di ind.js?

**Comment by rasmaniprogrammer** [comment]
![Screenshot_2021_0103_012617](https://user-images.githubusercontent.com/76784400/103464040-7ed63280-4d63-11eb-97a3-20a9ae135074.jpg)
![Screenshot_2021_0103_013125](https://user-images.githubusercontent.com/76784400/103464047-8e557b80-4d63-11eb-901a-a910815ce7f1.jpg)
ini bang tolong bang

**Comment by SlavyanDesu** [comment]
ada output error nya nggak? udah pasang nomor owner? apa menu yang lain juga gak kebuka?

**Comment by rasmaniprogrammer** [comment]
![IMG_20210103_093128](https://user-images.githubusercontent.com/76784400/103470590-ab5f6e00-4da6-11eb-8f43-deebd756a86a.JPG)
sudah di atur bang tapi gak muncul juga error pun gak ada info

**Comment by rasmaniprogrammer** [comment]
> ada output error nya nggak? udah pasang nomor owner? apa menu yang lain juga gak kebuka?

kalo menu lainnya bisa kebuka tapi buat owner gak bisa

**Comment by SlavyanDesu** [comment]
coba update aja
```bash
> git pull origin master
```

**Comment by rasmaniprogrammer** [comment]
> coba update aja
> 
> ```shell
> > git pull origin master
> ```

waduh tetep bang jadi susah gak bisa buka menu ownernya 😌

**Comment by rasmaniprogrammer** [comment]
masalahnya ketemu bang ternyata nomor bot gak bisa jadi owner tak kirain apanya yang error
