### ISSUE TITLE
phdl error

### ISSUE THREAD

**Issue by selyxn** [SlavyanDesu/BocchiBot#14]
![Screenshot_2](https://user-images.githubusercontent.com/69533502/101602989-7d01a380-3a31-11eb-968b-d4260539da35.png)

Knp ngab, link dh bener pdhl

**Comment by SlavyanDesu** [comment]
> ![Screenshot_2](https://user-images.githubusercontent.com/69533502/101602989-7d01a380-3a31-11eb-968b-d4260539da35.png)
> 
> Knp ngab, link dh bener pdhl

Coba minta linknya, soalnya di saya bisa

**Comment by SlavyanDesu** [comment]
![IMG-20201209-WA0005](https://user-images.githubusercontent.com/28254882/101605136-69a40780-3a34-11eb-83be-2fc9c7e06de1.jpg)

**Comment by selyxn** [comment]
> > ![Screenshot_2](https://user-images.githubusercontent.com/69533502/101602989-7d01a380-3a31-11eb-968b-d4260539da35.png)
> > Knp ngab, link dh bener pdhl
> 
> Coba minta linknya, soalnya di saya bisa

[ini](https://www.pornhub.com/view_video.php?viewkey=ph5fab842c65bc9)

**Comment by selyxn** [comment]
pas pake link agan ngk bisa jg

**Comment by SlavyanDesu** [comment]
> > > ![Screenshot_2](https://user-images.githubusercontent.com/69533502/101602989-7d01a380-3a31-11eb-968b-d4260539da35.png)
> > > Knp ngab, link dh bener pdhl
> > 
> > 
> > Coba minta linknya, soalnya di saya bisa
> 
> [ini](https://www.pornhub.com/view_video.php?viewkey=ph5fab842c65bc9)

![IMG-20201209-WA0006](https://user-images.githubusercontent.com/28254882/101605876-49c11380-3a35-11eb-8258-71c50367e69d.jpg)

**Comment by SlavyanDesu** [comment]
maaf tapi saya ngakak wkwkwk

**Comment by selyxn** [comment]
> > > > ![Screenshot_2](https://user-images.githubusercontent.com/69533502/101602989-7d01a380-3a31-11eb-968b-d4260539da35.png)
> > > > Knp ngab, link dh bener pdhl
> > > 
> > > 
> > > Coba minta linknya, soalnya di saya bisa
> > 
> > 
> > [ini](https://www.pornhub.com/view_video.php?viewkey=ph5fab842c65bc9)
> 
> ![IMG-20201209-WA0006](https://user-images.githubusercontent.com/28254882/101605876-49c11380-3a35-11eb-8258-71c50367e69d.jpg)

Waduh terus apa yg salah ya

**Comment by SlavyanDesu** [comment]
coba buka terminal agan, terus ketik
```bash
> git pull origin master
> npm install
```
pada dasarnya ini seperti install ulang

**Comment by selyxn** [comment]
> coba buka terminal agan, terus ketik
> 
> ```shell
> > git pull origin master
> > npm install
> ```
> 
> pada dasarnya ini seperti install ulang

sama aja :(

**Comment by SlavyanDesu** [comment]
> > coba buka terminal agan, terus ketik
> > ```shell
> > > git pull origin master
> > > npm install
> > ```
> > 
> > 
> > pada dasarnya ini seperti install ulang
> 
> sama aja :(

host/server agan pake IP Indonesia? kalau pake, itu karena keblokir sob. ini sama aja kayak kita buka website ph, lalu ngambil video link

**Comment by SlavyanDesu** [comment]
solusinya ganti dns/pake vpn

**Comment by selyxn** [comment]
> solusinya ganti dns/pake vpn

Tapi dns laptop ku pake dns (google public dns)

Buka phub tanpa vpn di chrome juga bisa ngab

**Comment by selyxn** [comment]
Okay work pake vpn,

saranku kalau bisa bot nya ngirim video juga @SlavyanDesu

**Comment by SlavyanDesu** [comment]
https://github.com/SlavyanDesu/BocchiBot/blob/62e998779fde937b7c383446e9f61072efd80160/message/index.js#L832
`TypeError: cannot convert undefined or null to object`
Ini karena ada kesalahan saat ngambil data dari server ph hasilnya `null` atau `undefined`. Ini kesalahan antara module-nya atau koneksi agan.

**Comment by selyxn** [comment]
> https://github.com/SlavyanDesu/BocchiBot/blob/62e998779fde937b7c383446e9f61072efd80160/message/index.js#L832
> 
> 
> `TypeError: cannot convert undefined or null to object`
> Ini karena ada kesalahan saat ngambil data dari server ph hasilnya `null` atau `undefined`. Ini kesalahan antara module-nya atau koneksi agan.

Iya kesalahan koneksi, ga nyambung ke ph wkwkwkwk sorry

btw kalau bisa bot nya ngirim videonya juga hehe

**Comment by SlavyanDesu** [comment]
> Okay work pake vpn,
> 
> saranku kalau bisa bot nya ngirim video juga @SlavyanDesu

Kalau botnya ngirim video juga, bakalan berat sob. Soalnya video dari ph itu durasi panjang dan kualitasnya rata-rata 480P ke atas dan WA cuman membatasi sampe 50 MB.

**Comment by selyxn** [comment]
> > Okay work pake vpn,
> > saranku kalau bisa bot nya ngirim video juga @SlavyanDesu
> 
> Kalau botnya ngirim video juga, bakalan berat sob. Soalnya video dari ph itu durasi panjang dan kualitasnya rata-rata 480P ke atas dan WA cuman membatasi sampe 50 MB.

Ga bisa di set ke 480p ya gan?
if size >50MB return "Error saat mengirim file"

**Comment by SlavyanDesu** [comment]
> > > Okay work pake vpn,
> > > saranku kalau bisa bot nya ngirim video juga @SlavyanDesu
> > 
> > 
> > Kalau botnya ngirim video juga, bakalan berat sob. Soalnya video dari ph itu durasi panjang dan kualitasnya rata-rata 480P ke atas dan WA cuman membatasi sampe 50 MB.
> 
> Ga bisa di set ke 480p ya gan?
> if size >50MB return "Error saat mengirim file"

Ntar ku cek lagi kalau itu ya sob, silakan close issue kalau sudah solved :^)
