### ISSUE TITLE
Linux ~ QR Code doesn't looks right

### ISSUE THREAD

**Issue by Baguettou** [SlavyanDesu/BocchiBot#141]
Hi I'm using a Linux VM for testing and running the bot. 
When i run the bot and it generates the QR code it doesn't looks right and I can't scan it, this problem don´t happen in my pc (Windows 10). And I tried changing the encoding of my terminal but that didn´t help.

Thanks in advance :D

https://user-images.githubusercontent.com/68337546/103484267-7b6e9580-4dbb-11eb-8ee8-44e7b712e629.mp4

**Comment by SlavyanDesu** [comment]
> Hi I'm using a Linux VM for testing and running the bot.
> When i run the bot and it generates the QR code it doesn't looks right and I can't scan it, this problem don´t happen in my pc (Windows 10). And I tried changing the encoding of my terminal but that didn´t help.
> 
> Thanks in advance :D
> 
>  Action.3-01-2021.11-52-33.a.m.mp4

Hello. Have you tried to change the terminal font? I think [this](https://askubuntu.com/questions/157873/is-it-possible-to-change-the-terminal-font) could help.

**Comment by Baguettou** [comment]
> > Hi I'm using a Linux VM for testing and running the bot.
> > When i run the bot and it generates the QR code it doesn't looks right and I can't scan it, this problem don´t happen in my pc (Windows 10). And I tried changing the encoding of my terminal but that didn´t help.
> > Thanks in advance :D
> > Action.3-01-2021.11-52-33.a.m.mp4
> 
> Hello. Have you tried to change the terminal font? I think [this](https://askubuntu.com/questions/157873/is-it-possible-to-change-the-terminal-font) could help.

Hello and thanks for answering, I tried that, all the terminal changes the font, but those characters just looks thicker and bolder but they dont really change :(

Here is an example of how they look now:
 ![Screenshot_23](https://user-images.githubusercontent.com/68337546/103486048-ebcfe380-4dc8-11eb-95f4-aa111c2cc06d.png)

What other thing could I try?

**Comment by SlavyanDesu** [comment]
This might do the trick but less efficient.

1. Authenticate your WhatsApp bot number in Windows 10.
2. After the bot successfully online, terminate it. There's a file called `BocchiBot.data.json` in bot directory.
3. Copy it and paste the file to your WhatsApp bot directory in your Linux VM.
4. Then try running it again.

**Comment by Baguettou** [comment]
It worked :D 
Thank you so much ^ - ^

**Comment by ozandesu** [comment]
> This might do the trick but less efficient.
> 
> 1. Authenticate your WhatsApp bot number in Windows 10.
> 2. After the bot successfully online, terminate it. There's a file called `BocchiBot.data.json` in bot directory.
> 3. Copy it and paste the file to your WhatsApp bot directory in your Linux VM.
> 4. Then try running it again.



> This might do the trick but less efficient.
> 
> 1. Authenticate your WhatsApp bot number in Windows 10.
> 2. After the bot successfully online, terminate it. There's a file called `BocchiBot.data.json` in bot directory.
> 3. Copy it and paste the file to your WhatsApp bot directory in your Linux VM.
> 4. Then try running it again.

Nama session.json apa bang?
