### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by arh-space** [SlavyanDesu/BocchiBot#144]
Permisi mau nanya ini kenapa ya? saat npm i
![error](https://user-images.githubusercontent.com/65483182/103597214-aa5f4580-4f3a-11eb-9dc7-6257a468b55e.png)

**Comment by SlavyanDesu** [comment]
coba hapus file `package-lock.json` lalu install lagi

**Comment by arh-space** [comment]
> coba hapus file `package-lock.json` lalu install lagi

masih error, udah di hapus

**Comment by SlavyanDesu** [comment]
Udah install git belum gan?

**Comment by arh-space** [comment]
Fixed, Thank you
