### ISSUE TITLE
will the level system be updated?

### ISSUE THREAD

**Issue by kwteen** [SlavyanDesu/BocchiBot#146]
this level system is incredible, it would be great to have a pant system, for example bronze silver gold. thank you so much ♥

**Comment by SlavyanDesu** [comment]
> this level system is incredible, it would be great to have a pant system, for example bronze silver gold. thank you so much ♥

pant system?

**Comment by kwteen** [comment]
yes, it would be nice to have a marriage system where members could get married. and a dungeon system to win xp and a duel system

**Comment by SlavyanDesu** [comment]
> yes, it would be nice to have a marriage system where members could get married. and a dungeon system to win xp and a duel system

maybe in the future update i will make it possible
