### ISSUE TITLE
BocchiBot Premium

### ISSUE THREAD

**Issue by Baguettou** [SlavyanDesu/BocchiBot#147]
Hi, sorry for bothering, but I would like to ask how can I get BocchiBot premium, if its possible its current price and if I would need a paid API. - Thanks in advance 😃.

**Comment by SlavyanDesu** [comment]
> Hi, sorry for bothering, but I would like to ask how can I get BocchiBot premium, if its possible its current price and if I would need a paid API. - Thanks in advance 😃.

The premium commands (multi lewds, multi fetish, and API-less nHentai downloader) price is IDR 30,000, it's about USD 2.16

**Comment by Baguettou** [comment]
Oh that´s cool, how can I buy it? Maybe PayPal?

**Comment by SlavyanDesu** [comment]
> Oh that´s cool, how can I buy it? Maybe PayPal?

Sure thing! You can contact with me that is listed in README.

**Comment by Baguettou** [comment]
Ow then im going to do it :D 
Thanks for answering.

**Comment by SlavyanDesu** [comment]
@Baguettou Hi! As you can see this repository is now available for funding. You can use Ko-fi platform to buy the commands.

**Comment by Baguettou** [comment]
Hi, thanks and sorry fot taking so long xD.
