### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by idkmew** [SlavyanDesu/BocchiBot#15]
Error Bang jadi gmna ya cara gnatasiny?
![image](https://user-images.githubusercontent.com/72456125/101614259-b1805a00-3a47-11eb-93d1-8cc222399742.png)

**Comment by SlavyanDesu** [comment]
> Error Bang jadi gmna ya cara gnatasiny?
> ![image](https://user-images.githubusercontent.com/72456125/101614259-b1805a00-3a47-11eb-93d1-8cc222399742.png)

Sudah mengedit file dan mengikut tata cara installasi semuanya belum sob?

**Comment by SlavyanDesu** [comment]
Kalau blank begitu biasanya koneksi atau dari wa-automate nya

**Comment by idkmew** [comment]
> Kalau blank begitu biasanya koneksi atau dari wa-automate nya

ap punya solusi bang gmna cara ngatasiny?

**Comment by MrPawNO** [comment]
> Error Bang jadi gmna ya cara gnatasiny?
> ![image](https://user-images.githubusercontent.com/72456125/101614259-b1805a00-3a47-11eb-93d1-8cc222399742.png)

Faktor koneksi gan, timeout biasanya gitu

**Comment by idkmew** [comment]
> > Kalau blank begitu biasanya koneksi atau dari wa-automate nya
> 
> ap punya solusi bang gmna cara ngatasiny?

dan saya udah mengikuti tata cara instalasinya, yaitu npm install dan npm start, dan saya udah pastikan kalau jaringan saya normal pingny dibawah 100

**Comment by SlavyanDesu** [comment]
> > > Kalau blank begitu biasanya koneksi atau dari wa-automate nya
> > 
> > 
> > ap punya solusi bang gmna cara ngatasiny?
> 
> dan saya udah mengikuti tata cara instalasinya, yaitu npm install dan npm start, dan saya udah pastikan kalau jaringan saya normal pingny dibawah 100

Di folder bot-nya ada file `BocchiBot.data.json` gak? Kalau ada, hapus. Setelah itu mulai lagi dan scan QR.

**Comment by idkmew** [comment]
> > > > Kalau blank begitu biasanya koneksi atau dari wa-automate nya
> > > 
> > > 
> > > ap punya solusi bang gmna cara ngatasiny?
> > 
> > 
> > dan saya udah mengikuti tata cara instalasinya, yaitu npm install dan npm start, dan saya udah pastikan kalau jaringan saya normal pingny dibawah 100
> 
> Di folder bot-nya ada file `BocchiBot.data.json` gak? Kalau ada, hapus. Setelah itu mulai lagi dan scan QR.

gaada sih bang yg berkaitan dgn nama BocchiBot.data.json, adanya config.json(untuk prefixny)
menurut abang kira" dibagian mana ya? biar saya check lagi klo misalny abangny tau letakny

**Comment by SlavyanDesu** [comment]
Gak ada ya hmm... Ini sih koneksi bro, coba pake jaringan yang lain

**Comment by idkmew** [comment]
> Gak ada ya hmm... Ini sih koneksi bro, coba pake jaringan yang lain

Engga bang, ini saya ngejalanin Elaina Bot yg versi sebelumny lancar ko

**Comment by SlavyanDesu** [comment]
> > Gak ada ya hmm... Ini sih koneksi bro, coba pake jaringan yang lain
> 
> Engga bang, ini saya ngejalanin Elaina Bot yg versi sebelumny lancar ko

Kalau boleh tau, itu ngestucknya dibagian launching browser doang atau bervariasi?

**Comment by SlavyanDesu** [comment]
Kalau mau lebih cepet resolve-nya, bisa bikin issue ke wa-automate langsung.
https://github.com/open-wa/wa-automate-nodejs/issues

**Comment by SlavyanDesu** [comment]
> > Gak ada ya hmm... Ini sih koneksi bro, coba pake jaringan yang lain
> 
> Engga bang, ini saya ngejalanin Elaina Bot yg versi sebelumny lancar ko

Dicoba, kali aja bisa
https://github.com/SlavyanDesu/BocchiBot/issues/35#issuecomment-743957386
