### ISSUE TITLE
o

### ISSUE THREAD

**Issue by benirabbny** [SlavyanDesu/BocchiBot#164]
sebarin semua bang.

**Comment by VideFrelan** [comment]
> sebarin semua bang.

lah napa u?

**Comment by SlavyanDesu** [comment]
> > sebarin semua bang.
> 
> lah napa u?

Gabut

**Comment by VideFrelan** [comment]
> sebarin semua bang.

Kalo mau ngopi masuk grup aja sini, dan kalo nyari masalah pakai akun asli bang wkwk
