### ISSUE TITLE
Sticker function is not working.

### ISSUE THREAD

**Issue by gabrielwsy** [SlavyanDesu/BocchiBot#165]
Hello, I'm trying to run the sticker function, but it's not working, the following error appears on my cmd, you know how to solve it ?!
I already have libwebp installed and it is already configured in the "patch", but the error still continues
![image](https://user-images.githubusercontent.com/40281950/104847538-63b90600-58bf-11eb-8293-9cd479fb87c6.png)

**Comment by VideFrelan** [comment]
> Hello, I'm trying to run the sticker function, but it's not working, the following error appears on my cmd, you know how to solve it ?!
> I already have libwebp installed and it is already configured in the "patch", but the error still continues
> ![image](https://user-images.githubusercontent.com/40281950/104847538-63b90600-58bf-11eb-8293-9cd479fb87c6.png)

Hello, have you updated your SC yet?

and make sure you run CMD/gitbash with run as admin

**Comment by gabrielwsy** [comment]
> > Hello, I'm trying to run the sticker function, but it's not working, the following error appears on my cmd, you know how to solve it ?!
> > I already have libwebp installed and it is already configured in the "patch", but the error still continues
> > ![image](https://user-images.githubusercontent.com/40281950/104847538-63b90600-58bf-11eb-8293-9cd479fb87c6.png)
> 
> Hello, have you updated your SC yet?
> 
> and make sure you run CMD/gitbash with run as admin

I didn't update, how do I do that ?!

**Comment by VideFrelan** [comment]
`> git pull origin master`

**Comment by arifrahmanulhakim** [comment]
![1](https://user-images.githubusercontent.com/74624435/104872817-d68eb380-5989-11eb-9345-7340ac1cb9eb.jpg)

Ini kenapa ya sticker nya ga bisa? cara masang libwebp bagaimana?

**Comment by SlavyanDesu** [comment]
> ![1](https://user-images.githubusercontent.com/74624435/104872817-d68eb380-5989-11eb-9345-7340ac1cb9eb.jpg)
> 
> Ini kenapa ya sticker nya ga bisa? cara masang libwebp bagaimana?

https://github.com/SlavyanDesu/BocchiBot/issues/163#issuecomment-761568680

**Comment by arifrahmanulhakim** [comment]
> > ![1](https://user-images.githubusercontent.com/74624435/104872817-d68eb380-5989-11eb-9345-7340ac1cb9eb.jpg)
> > Ini kenapa ya sticker nya ga bisa? cara masang libwebp bagaimana?
> 
> [#163 (comment)](https://github.com/SlavyanDesu/BocchiBot/issues/163#issuecomment-761568680)

terima kasih :D

**Comment by gabrielwsy** [comment]
> `> git pull origin master`

I tried and it didn't work yet, I will try again.

**Comment by SlavyanDesu** [comment]
> > `> git pull origin master`
> 
> I tried and it didn't work yet, I will try again.

If you can't run `> git pull origin master` try to update manually or install a new fresh code. Also, I've added an installation manual on [README](https://github.com/SlavyanDesu/BocchiBot/README.md).

**Comment by gabrielwsy** [comment]
> > > `> git pull origin master`
> > 
> > 
> > I tried and it didn't work yet, I will try again.
> 
> If you can't run `> git pull origin master` try to update manually or install a new fresh code. Also, I've added an installation manual on [README](https://github.com/SlavyanDesu/BocchiBot/blob/master/README.md).

Hello, the error still persists.
I reinstalled the bot all from 0 again and the error still appears.
I'm using windows 7 64bit, can this be the problem? 

![image](https://user-images.githubusercontent.com/40281950/105097815-fc01e700-5a87-11eb-8a5c-e65d3e267e0a.png)
![image](https://user-images.githubusercontent.com/40281950/105097855-08863f80-5a88-11eb-98d4-f57639a85ed1.png)

`[CMD] 20/01/21 04:53:08 sticker [0] from Gabs🍑
-q 100 "D:\BocchiBot\node_modules\webp-converter\temp\580301536.jpg" -o "D:\BocchiBot\node_modules\webp-converter\temp\580301536.webp"
Error: Command failed: "D:\BocchiBot\node_modules\webp-converter\bin\libwebp_win64\bin\cwebp.exe" -q 100 "D:\BocchiBot\node_modules\webp-converter\temp\580301536.jpg" -o "D:\BocchiBot\node_modules\webp-converter\temp\580301536.webp"
CoCreateInstance(MAKE_REFGUID(CLSID_WICImagingFactory), NULL, CLSCTX_INPROC_SERVER, MAKE_REFGUID(IID_IWICImagingFactory), (LPVOID*)&factory) failed 80040154
Couldn't access Windows Imaging Component (are you running Windows XP SP3 or newer?). Most formats not available. Use -s for the available YUV input.
Decoding of input data failed.
Status: 3(BITSTREAM_ERROR)
Error! Could not process file D:\BocchiBot\node_modules\webp-converter\temp\580301536.jpg
Error! Cannot read input picture file 'D:\BocchiBot\node_modules\webp-converter\temp\580301536.jpg'

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 4294967295,
  signal: null,
  cmd: '"D:\\BocchiBot\\node_modules\\webp-converter\\bin\\libwebp_win64\\bin\\cwebp.exe" -q 100 "D:\\BocchiBot\\node_modules\\webp-converter\\temp\\580301536.jpg" -o "D:\\BocchiBot\\node_modules\\webp-converter\\temp\\580301536.webp"'
}
(node:2104) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'D:\BocchiBot\node_modules\webp-converter\temp\580301536.webp'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at encode_image (D:\BocchiBot\node_modules\webp-converter\src\buffer_utils.js:11:19)
    at D:\BocchiBot\node_modules\webp-converter\src\buffer_utils.js:91:27
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2104) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

this is the error

**Comment by SlavyanDesu** [comment]
This seems `webp-converter`'s issue. I can give you a sticker command but with a different method which means the produced stickers won't have metadata (see the image below). Are you OK with that? 
![Screenshot_20210120-153029](https://user-images.githubusercontent.com/28254882/105148092-91f34b80-5b34-11eb-8d3c-bbbfae888be9.jpg)

**Comment by gabrielwsy** [comment]
> This seems `webp-converter`'s issue. I can give you a sticker command but with a different method which means the produced stickers won't have metadata (see the image below). Are you OK with that?
> ![Screenshot_20210120-153029](https://user-images.githubusercontent.com/28254882/105148092-91f34b80-5b34-11eb-8d3c-bbbfae888be9.jpg)

I understand, if it isn't, you can send the command, after sending you can close the topic.
Thanks in advance for your help.

**Comment by SlavyanDesu** [comment]
Replace it with this:
```js
case 'sticker':
case 'stiker':
  if (!isRegistered) return await bocchi.reply(from, eng.notRegistered(), id)
  if (isMedia && isImage || isQuotedImage) {
    await bocchi.reply(from, eng.wait(), id)
    const encryptMedia = isQuotedImage ? quotedMsg : message
    const _mimetype = isQuotedImage ? quotedMsg.mimetype : mimetype
    const mediaData = await decryptMedia(encryptMedia, uaOverride)
    const base64 = `data:${_mimetype};base64,${mediaData.toString('base64')}`
    await bocchi.sendImageAsSticker(from, base64)
    await bocchi.reply(from, eng.ok(), id)
  }
break
```

**Comment by gabrielwsy** [comment]
> Replace it with this:
> 
> ```js
> case 'sticker':
> case 'stiker':
>     if (!isRegistered) return await bocchi.reply(from, eng.notRegistered(), id)
>     if (isMedia && isImage || isQuotedImage) {
>         await bocchi.reply(from, eng.wait(), id)
>         const encryptMedia = isQuotedImage ? quotedMsg : message
>         const _mimetype = isQuotedImage ? quotedMsg.mimetype : mimetype
>         const mediaData = await decryptMedia(encryptMedia, uaOverride)
>         const base64 = `data:${_mimetype};base64,${mediaData.toString('base64')}`
>         await bocchi.sendImageAsSticker(from, base64)
>         await bocchi.reply(from, eng.ok(), id)
>     } else {
>         await bocchi.reply(from, eng.wrongFormat(), id)
>     }
> break
> ```

Thank you very much.
