### ISSUE TITLE
EXIF.DATA

### ISSUE THREAD

**Issue by bdrsmsdn** [SlavyanDesu/BocchiBot#167]
![WhatsApp Image 2021-01-17 at 09 28 11](https://user-images.githubusercontent.com/72941497/104851067-817a7100-58a7-11eb-91b9-c7f8d09d8bbf.jpeg)

how to custom this text in sticker cmd:>

**Comment by VideFrelan** [comment]
To give a default watermark to the sticker command, you must set it with the command **exif** package_name | author_name

Or if you want to create a sticker with a custom watermark, use the command **stickerwm** package_name | author_name
