### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by MrPawNO** [SlavyanDesu/BocchiBot#17]
Kenapa nih gan...
![Screenshot_4](https://user-images.githubusercontent.com/13583912/101663258-1013fb00-3a7d-11eb-9b65-53afeca2f937.png)

**Comment by SlavyanDesu** [comment]
`FetchError: invalid json body`: ini error dari vhtear sob, tadi gw cek nyoba make apikey yang tadi.
Entah kenapa yang bikin calender, sticker fire, sticker lightning error API-nya dan yang lain nggak

**Comment by SlavyanDesu** [comment]
Untuk XXX sih belum coba

**Comment by MrPawNO** [comment]
> `FetchError: invalid json body`: ini error dari vhtear sob, tadi gw cek nyoba make apikey yang tadi.
> Entah kenapa yang bikin calender, sticker fire, sticker lightning error API-nya dan yang lain nggak



> `FetchError: invalid json body`: ini error dari vhtear sob, tadi gw cek nyoba make apikey yang tadi.
> Entah kenapa yang bikin calender, sticker fire, sticker lightning error API-nya dan yang lain nggak

Gan dari api nya udah terfix, tapi di terminal tetep invalid json body
