### ISSUE TITLE
Anti-link problem.

### ISSUE THREAD

**Issue by Baguettou** [SlavyanDesu/BocchiBot#171]
Hi, I noticed that the anti-link doesn´t work if a group link have a description very extense

Like this example. I also think that this is due to the RegExp can´t detect if the message says read more.

![WhatsApp Image 2021-01-17 at 7 10 24 PM](https://user-images.githubusercontent.com/68337546/104860140-ea89d500-58f7-11eb-8ab7-5991f9127f9f.jpeg)

By the way: "Leer más" = "Read more" and "Unirme al grupo" = "Join the group"

**Comment by SlavyanDesu** [comment]
Hello, thanks for contacting us. This most likely WhatsApp or its library (wa-automate-nodejs) limitations, sadly we can't fix this because these are their works and we aren't pro enough to re-edit the WAPI they have.
