### ISSUE TITLE
Anti-Fake-Link

### ISSUE THREAD

**Issue by Baguettou** [SlavyanDesu/BocchiBot#172]
Hi, recently there are a lot of WhatsApp fake group links for phishing and scamming, I think that this could be easily warned editing the previous normal anti-link filter and adding a new filter.
This would be linked and activated as the normal anti-link but with a different message suggesting that the link could be "suspicius".

_**An example already tested for this command could be this:**_

[Pastebin example](https://pastebin.com/mAsvJ6mW) - Password: BocchiBot

_**And also here an example used in a group:**_

![WhatsApp Image 2021-01-18 at 2 06 03 AM](https://user-images.githubusercontent.com/68337546/104882863-c814ad80-5931-11eb-9430-a6692c43a0ad.jpeg)

As you can see it's very helpful ^ - ^ - Thanks in advance.

**Comment by SlavyanDesu** [comment]
Hello, thanks for your advice. It's a good idea for keeping groups as clean as possible, why don't you create a pull request instead?

**Comment by VideFrelan** [comment]
Make a pull request bro

**Comment by Baguettou** [comment]
Ok, thanks for answering :D
