### ISSUE TITLE
New sticker command.

### ISSUE THREAD

**Issue by Baguettou** [SlavyanDesu/BocchiBot#176]
Hi, I noticed that when the bot is making a sticker it crops it and some times it makes the sticker looks bad (I don't know if this happend because I'm using a linux VM). So for fixing it, I made a new command "stickerp" that fix this.

Like in these examples: 

**_Before:_**

![WhatsApp Image 2021-01-18 at 7 16 33 PM](https://user-images.githubusercontent.com/68337546/104973145-dd391d00-59c1-11eb-88a2-bbe7f7bdf91c.jpeg)

**_After:_**

![WhatsApp Image 2021-01-18 at 7 16 33 PM (1)](https://user-images.githubusercontent.com/68337546/104973173-ec1fcf80-59c1-11eb-9e56-cc3df31aeafb.jpeg)

And I would like to know if I should make a pull request. Thanks in advance.

**Comment by SlavyanDesu** [comment]
Sure thing.
