### ISSUE TITLE
ytmp3 ytmp4 error

### ISSUE THREAD

**Issue by mzakinfl** [SlavyanDesu/BocchiBot#180]
Saya hanya ingin berkontribusi, ini const dan case nya untuk vhtear silahkan di coba bang klo ngga mau juga ngga papa

/**
* Get YouTube media from URL.
* @param {String} query
* @returns {Object}
*/
const ytdl = (query) => new Promise((resolve, reject) => {
    console.log(`Get YouTube media from ${query}`)
    fetchJson(`https://api.vhtear.com/ytdl?link=${query}&apikey=${config.vhtear}`)
        .then((result) => resolve(result))
        .catch((err) => reject(err))
})

case 'ytmp3':
            if (args.length == 0) return await bocchi.reply(from, `Untuk mendownload Youtube MP3\ngunakan ${prefix}ytmp3 linkvideo`, id)
            await bocchi.reply(from, ind.wait(), id)
            downloader.ytdl(q)
            .then(async ({ result }) => {
            if (result.info) return bocchi.reply(from, result.info, id)
            if (Number(result.size.split(' MB')[0]) >= 15.00) return bocchi.sendFileFromUrl(from, result.imgUrl, `${result.title}.jpg`, `Judul: ${result.title}\nSize: ${result.size}\n\nGagal!, Maksimal video size adalah 15 MB`, id)
            await bocchi.sendFileFromUrl(from, result.imgUrl, `${result.title}.jpg`, `Judul: ${result.title}\nSize: ${result.size}\nID: ${result.id}\n\nSedang dikirim, sabar ya...`, id)
            await bocchi.sendFileFromUrl(from, result.UrlMp3, `${result.title}.mp3`, '', id)
        })
            .catch(async (err) => {
            console.error(err)
            await bocchi.reply(from, `Ada yang Error!`, id)
                    })

case 'ytmp4':
            if (args.length == 0) return await bocchi.reply(from, `Untuk mendownload Youtube MP4\ngunakan ${prefix}ytmp4 linkvideo`, id)
            await bocchi.reply(from, ind.wait(), id)
            downloader.ytdl(q)
            .then(async ({ result }) => {
            if (result.info) return bocchi.reply(from, result.info, id)
            if (Number(result.size.split(' MB')[0]) >= 15.00) return bocchi.sendFileFromUrl(from, result.imgUrl, `${result.title}.jpg`, `Judul: ${result.title}\nSize: ${result.size}\n\nGagal!, Maksimal video size adalah 15 MB`, id)
            await bocchi.sendFileFromUrl(from, result.imgUrl, `${result.title}.jpg`, `Judul: ${result.title}\nSize: ${result.size}\nID: ${result.id}\n\nSedang dikirim, sabar ya...`, id)
            await bocchi.sendFileFromUrl(from, result.UrlVideo, `${result.title}.mp4`, '', id)
        })
            .catch(async (err) => {
            console.error(err)
            await bocchi.reply(from, `Ada yang Error!`, id)
                    })
            break

**Comment by SlavyanDesu** [comment]
Silakan untuk membuat pull request ya, nanti saya review kembali kodenya. Terima kasih atas kontribusinya.

**Comment by mzakinfl** [comment]
Iya bang itu const sama case nya lengkap tinggal di coba saja, maaf tdi
spam ke kirim ga sengaja.

Pada tanggal Sel, 19 Jan 2021 18:47, Heikal Syah Shiddiq <
notifications@github.com> menulis:
