### ISSUE TITLE
#ytmp3 dan #play

### ISSUE THREAD

**Issue by MoziGuy** [SlavyanDesu/BocchiBot#184]
Mau tanya,cara fix #play jadi audio bukan voice message bagaimana? dan #ytmp3 tidak bisa malah mengirim file M4A bukan file audio/mp3,mohon solusinya,trima kasih

**Comment by SlavyanDesu** [comment]
M4A merupakan salah satu format audio juga, kalau kamu buka filenya dengan aplikasi pemutar audio juga pasti masih bisa terbaca.

**Comment by SlavyanDesu** [comment]
Untuk command `play` agar bisa mengirim file-nya saja, bisa kamu ikuti seperti command `ytmp3`, yaitu menggunakan:
```js
await bocchi.sendFileFromUrl(from, result.mp3, `${result.title}.mp3`, '', id)
```
Silakan jika masih ada yang ingin ditanyakan.

**Comment by MoziGuy** [comment]
> Untuk command `play` agar bisa mengirim file-nya saja, bisa kamu ikuti seperti command `ytmp3`, yaitu menggunakan:
> 
> ```js
> await bocchi.sendFileFromUrl(from, result.mp3, `${result.title}.mp3`, '', id)
> ```
> 
> Silakan jika masih ada yang ingin ditanyakan.

editnya disebelah mana bang? di misc.js trus bagian mn?

**Comment by SlavyanDesu** [comment]
Ini:
https://github.com/SlavyanDesu/BocchiBot/blob/6b095dbea8c91fcedb98d90e147688ca31742e82/message/index.js#L1057-L1059
Diganti dengan:
```js
await bocchi.sendFileFromUrl(from, result.mp3, `${result.title}.mp3`, '', id)
```
Semoga membantu.

**Comment by MoziGuy** [comment]
> Ini:
> https://github.com/SlavyanDesu/BocchiBot/blob/6b095dbea8c91fcedb98d90e147688ca31742e82/message/index.js#L1057-L1059
> 
> 
> Diganti dengan:
> ```js
> await bocchi.sendFileFromUrl(from, result.mp3, `${result.title}.mp3`, '', id)
> ```
> 
> Semoga membantu.

oke saya coba dulu

**Comment by MoziGuy** [comment]
[](url)
![Capture](https://user-images.githubusercontent.com/77720124/105154106-c4ed0d80-5b3b-11eb-9a9c-a43a1bc8fc59.PNG)

itu kenapa ya?

**Comment by MoziGuy** [comment]
> Ini:
> https://github.com/SlavyanDesu/BocchiBot/blob/6b095dbea8c91fcedb98d90e147688ca31742e82/message/index.js#L1057-L1059
> 
> 
> Diganti dengan:
> ```js
> await bocchi.sendFileFromUrl(from, result.mp3, `${result.title}.mp3`, '', id)
> ```
> 
> Semoga membantu.

Oiya dengan hal ini File Nya berubah menjadi file BIN knp ya?

**Comment by Mamatzzz** [comment]
bang ada case addsticker ga?
kalo kita kirim pesan nanti stikernya ada

**Comment by VideFrelan** [comment]
> ![Capture](https://user-images.githubusercontent.com/77720124/105154106-c4ed0d80-5b3b-11eb-9a9c-a43a1bc8fc59.PNG)
> 
> itu kenapa ya?

Ini kenapa ya? apa masih error?, kalau ada pesan error seperti itu, biasanya terjadi hanya sesekali, mungkin belum selesai ngeGet data tiktok nya... bisa diulang kembali perintahnya

**Comment by VideFrelan** [comment]
> bang ada case addsticker ga?
> kalo kita kirim pesan nanti stikernya ada

Bisa dijelaskan dengan detail?

**Comment by VideFrelan** [comment]
Dan silahkan dicoba update cmd play nya @MoziGuy

**Comment by MoziGuy** [comment]
> > ![Capture](https://user-images.githubusercontent.com/77720124/105154106-c4ed0d80-5b3b-11eb-9a9c-a43a1bc8fc59.PNG)
> > itu kenapa ya?
> 
> Ini kenapa ya? apa masih error?, kalau ada pesan error seperti itu, biasanya terjadi hanya sesekali, mungkin belum selesai ngeGet data tiktok nya... bisa diulang kembali perintahnya

sudah normal lagi

**Comment by MoziGuy** [comment]
> Dan silahkan dicoba update cmd play nya @MoziGuy

saya masalahnya cmn yang $play tapi terkirim nya bukan file mp3 tapi BIN,ada solusi?

**Comment by VideFrelan** [comment]
> > Dan silahkan dicoba update cmd play nya @MoziGuy
> 
> saya masalahnya cmn yang $play tapi terkirim nya bukan file mp3 tapi BIN,ada solusi?

Iya sudah saya ubah jadi sendFile audio gan, coba update sc nya, terus coba cmd play nya

**Comment by MoziGuy** [comment]
comma

> > > Dan silahkan dicoba update cmd play nya @MoziGuy
> > 
> > 
> > saya masalahnya cmn yang $play tapi terkirim nya bukan file mp3 tapi BIN,ada solusi?
> 
> Iya sudah saya ubah jadi sendFile audio gan, coba update sc nya, terus coba cmd play nya

command updatenya apa ya?maaf awam banget nih hehe

**Comment by VideFrelan** [comment]
> comma
> 
> > > > Dan silahkan dicoba update cmd play nya @MoziGuy
> > > 
> > > 
> > > saya masalahnya cmn yang $play tapi terkirim nya bukan file mp3 tapi BIN,ada solusi?
> > 
> > 
> > Iya sudah saya ubah jadi sendFile audio gan, coba update sc nya, terus coba cmd play nya
> 
> command updatenya apa ya?maaf awam banget nih hehe

`git pull origin master`

atau agan copy aja updatean play nya lalu replace case 'play' sebelumnya

**Comment by MoziGuy** [comment]
> > comma
> > > > > Dan silahkan dicoba update cmd play nya @MoziGuy
> > > > 
> > > > 
> > > > saya masalahnya cmn yang $play tapi terkirim nya bukan file mp3 tapi BIN,ada solusi?
> > > 
> > > 
> > > Iya sudah saya ubah jadi sendFile audio gan, coba update sc nya, terus coba cmd play nya
> > 
> > 
> > command updatenya apa ya?maaf awam banget nih hehe
> 
> `git pull origin master`
> 
> atau agan copy aja updatean play nya lalu replace case 'play' sebelumnya

masih BIN gan,apa open wa gk bisa?

**Comment by SlavyanDesu** [comment]
Issue sudah resolved via private chat WhatsApp. File yang terkirim menjadi `.bin` dikarenakan ada issue di bagian host-nya, sudah dites menggunakan source code yang berbeda juga masih sama.
Untuk @Mamatzzz silakan buka issue baru untuk command `addsticker`-nya dengan, terima kasih.
