### ISSUE TITLE
😢

### ISSUE THREAD

**Issue by MFarelS** [SlavyanDesu/BocchiBot#185]
![images (4)-picsay](https://user-images.githubusercontent.com/58540890/105272611-4b513000-5bcc-11eb-8444-e75ee4d45277.jpeg)
Awokwaokwaok

**Comment by FaizBastomi** [comment]
@MFarelS 😢😣😟

**Comment by Zalleya** [comment]
akqkq

**Comment by EBENZEX** [comment]
HMM

**Comment by MFarelS** [comment]
Mwehehe

**Comment by SlavyanDesu** [comment]
Maksudnya? 🤔

**Comment by VideFrelan** [comment]
Adakah bug yg fatal dalam topic ini? 😂
