### ISSUE TITLE
Changing Thumbnail - Possible new command?

### ISSUE THREAD

**Issue by Baguettou** [SlavyanDesu/BocchiBot#186]
Hi :D
While chatting on WhatsApp, I recognized that there are some trending pictures where the preview of the picture is mostly one but when you open it, a different one appears. I read that this is because WhatsApp takes the exif data and I also found that you can do this with this code:

`exiftool "-thumbnailimage<=thumb.jpg" image.jpg`

So, is this a good a idea for a new command?

Also here is an example:

<img src="https://user-images.githubusercontent.com/68337546/105278483-9854e800-5b73-11eb-9047-2088d0169aac.gif" width="260" height="350"/>

**Comment by SlavyanDesu** [comment]
> Hi :D
> While chatting on WhatsApp, I recognized that there are some trending pictures where the preview of the picture is mostly one but when you open it, a different one appears. I read that this is because WhatsApp takes the exif data and I also found that you can do this with this code:
> 
> `exiftool "-thumbnailimage<=thumb.jpg" image.jpg`
> 
> So, is this a good a idea for a new command?
> 
> Also here is an example:
> 
> <img alt="" width="260" height="350" src="https://user-images.githubusercontent.com/68337546/105278483-9854e800-5b73-11eb-9047-2088d0169aac.gif">

This is indeed a great command! Pull request is open. Also, do we need to change `exif.js` tool?

**Comment by SlavyanDesu** [comment]
And how do we implement it to the command?

**Comment by Baguettou** [comment]
Oh no, I have not make it already, but I was asking if the current `exif.js` supports it, because I thought it only works with the metadata of stickers but not with images.

**Comment by Baguettou** [comment]
> And how do we implement it to the command?

That is also another point I want to talk about, I was thinking about:

`!changebg Link_Image | Link_Background`

This is because the bot can convert images into links.

**Comment by Baguettou** [comment]
Oh, and a important information is that the thumbnail should be 160x120 pixels for preventing bugs or errors with WhatsApp. I was thinking about using FFmpeg for doing it automatically.

**Comment by SlavyanDesu** [comment]
It's good though. This is will work too `Reply to the image > $fakethumb link_fake_thumb`

**Comment by SlavyanDesu** [comment]
> Oh, and a important information is that the thumbnail should be 160x120 pixels for preventing bugs or errors with WhatsApp. I was thinking about using FFmpeg for doing it automatically.

I bet the code will kinda a bit messy. 😂

**Comment by SlavyanDesu** [comment]
Anyway, let's make this possible. I've heard that another library named `baileys` support with fake thumbnail.

**Comment by SlavyanDesu** [comment]
Also please join the official grup for the convenience. @Baguettou

**Comment by Baguettou** [comment]
> It's good though. This is will work too `Reply to the image > $fakethumb link_fake_thumb`

Ow that's a great idea :D

**Comment by Baguettou** [comment]
> Also please join the official grup for the convenience. @Baguettou

I'm sorry but I don't understand, what is the official group?.

**Comment by SlavyanDesu** [comment]
> > Also please join the official grup for the convenience. @Baguettou
> 
> I'm sorry but I don't understand, what is the official group?.

Hmmm, actually I only need your WhatsApp contact because GitHub is not so chat-able. So we can discuss about this in real-time in WhatsAlpp. Then I suggest you to join the official grup which is listed in README for preventing sharing your number here.

**Comment by Baguettou** [comment]
> > > Also please join the official grup for the convenience. @Baguettou
> > 
> > 
> > I'm sorry but I don't understand, what is the official group?.
> 
> Hmmm, actually I only need your WhatsApp contact because GitHub is not so chat-able. So we can discuss about this in real-time in WhatsApp. Then I suggest you to join the official grup which is listed in README for preventing sharing your number here.

Oh :0, yeah I'm going to look it up it right now. Thanks :D

**Comment by SlavyanDesu** [comment]
It's almost a month and still we can't make it through...

**Comment by VideFrelan** [comment]
Hi, I think this feature will be coming easily soon, based on the issue or feature request made in open-wa

**Comment by Baguettou** [comment]
Sadly, I'm not sure about that :( 

"However, we're in a weird situation where I brought this up to the insiders and they're voting against it due to the potential of abuse of this feature (imagine showing a preview of a puppy but instead its NSFW/NSFL). Also, there's another issue where this may be fixed by WA eventually because honestly, this is a bug that they should really fix ASAP." - Open-wa dev

**Comment by SlavyanDesu** [comment]
> Sadly, I'm not sure about that :(
> 
> "However, we're in a weird situation where I brought this up to the insiders and they're voting against it due to the potential of abuse of this feature (imagine showing a preview of a puppy but instead its NSFW/NSFL). Also, there's another issue where this may be fixed by WA eventually because honestly, this is a bug that they should really fix ASAP." - Open-wa dev

And yet, it's almost 3 years since this bug appear but WhatsApp somehow doesn't really care.
