### ISSUE TITLE
Bang request change username dan status

### ISSUE THREAD

**Issue by dwizidane** [SlavyanDesu/BocchiBot#187]
jadi owner bisa ganti username atau status yang ada di profile

**Comment by SlavyanDesu** [comment]
> jadi owner bisa ganti username atau status yang ada di profile

untuk set status udah ada make `$setstatus status_bot` kalau name belum

**Comment by SlavyanDesu** [comment]
done https://github.com/SlavyanDesu/BocchiBot/commit/b4ae01d46537af0484a91d69d6ec1d2c81da1cce
set username nggak work kalau akun bot-nya akun bisnis.
