### ISSUE TITLE
how to put the welcome card in another language

### ISSUE THREAD

**Issue by NaldoMota1** [SlavyanDesu/BocchiBot#192]
how to put the welcome card in another language

**Comment by VideFrelan** [comment]
Hello, to change the text on the welcome card

Steps:
1. Open your bot folder
2. Open node_modules
3. Find the discord-canvas folder
4. Open the src folder
5. Open the greetings folder
6. There is a greetings.js file, open the file and edit as you like

**Comment by SlavyanDesu** [comment]
Resolved.
