### ISSUE TITLE
how to adjust premium time

### ISSUE THREAD

**Issue by gabrielwsy** [SlavyanDesu/BocchiBot#197]
how can I set a user's premium time, I still don't understand.
Can someone help me.

![image](https://user-images.githubusercontent.com/40281950/105634939-40ea9c80-5e3f-11eb-9607-606810c21cf2.png)

**Comment by VideFrelan** [comment]
> how can I set a user's premium time, I still don't understand.
> Can someone help me.
> 
> ![image](https://user-images.githubusercontent.com/40281950/105634939-40ea9c80-5e3f-11eb-9607-606810c21cf2.png)

d = day(s)
h = hour(s)
m = minute(s)

Example:
$premium add number 30d

**Comment by gabrielwsy** [comment]
thank you very much
