### ISSUE TITLE
Doubts with Resizing the stickers.

### ISSUE THREAD

**Issue by gabrielwsy** [SlavyanDesu/BocchiBot#218]
In the previous code that I had, the animated figurines (stickergif) when made, were resized, that is, it would not cut if it was too wide.
However, this new code, the animated figures are becoming centralized, cut if the figure is wide.
I would like to know how I do to resize.
Thank you very much in advance.

**Comment by SlavyanDesu** [comment]
> In the previous code that I had, the animated figurines (stickergif) when made, were resized, that is, it would not cut if it was too wide.
> However, this new code, the animated figures are becoming centralized, cut if the figure is wide.
> I would like to know how I do to resize.
> Thank you very much in advance.

What module did you use for creating a GIFs?

**Comment by gabrielwsy** [comment]
> > In the previous code that I had, the animated figurines (stickergif) when made, were resized, that is, it would not cut if it was too wide.
> > However, this new code, the animated figures are becoming centralized, cut if the figure is wide.
> > I would like to know how I do to resize.
> > Thank you very much in advance.
> 
> What module did you use for creating a GIFs?

`case 'stickergif':
            case 'stikergif':
			case 'sgif':
                if (!isRegistered) return await bocchi.reply(from, br.notRegistered(), id)
                if (isMedia && type === 'video' || mimetype === 'image/gif') {
                    await bocchi.reply(from, br.wait(), id)
                    try {
                        const mediaData = await decryptMedia(message, uaOverride)
                        const videoBase64 = `data:${mimetype};base64,${mediaData.toString('base64')}`
                        await bocchi.sendMp4AsSticker(from, videoBase64, { fps: 30, startTime: '00:00:00.0', endTime : '00:00:05.0', loop: 0 })
						
							.then(async () => {
                                //await bocchi.sendText(from, br.ok())
                            })
						console.log(timeLog)
                    } catch (err) {
                        console.error(err)
                        await bocchi.reply(from, br.videoLimit(), id)
                    }
                } else if (isQuotedGif || isQuotedVideo) {
                    await bocchi.reply(from, br.wait(), id)
                    try {
                        const mediaData = await decryptMedia(quotedMsg, uaOverride)
                        const videoBase64 = `data:${quotedMsg.mimetype};base64,${mediaData.toString('base64')}`
                        await bocchi.sendMp4AsSticker(from, videoBase64, { fps: 30, startTime: '00:00:00.0', endTime : '00:00:05.0', loop: 0 })
							.then(async () => {                 
                                //await bocchi.sendText(from, br.ok())
                            })
						console.log(timeLog) 
                    } catch (err) {
                        console.error(err)
                        await bocchi.reply(from, br.videoLimit(), id)
                    }
                } else {
                    await bocchi.reply(from, br.wrongFormat(), id)
                }
            break
			/*
			 *  STICKERGIF = VERSÃO NOVA
			 */
			case 'stickergif2':
			case 'sticergif2':
			case 'sgif2':
				if (isMedia && mimetype == 'video/mp4' || mimetype == 'image/gif') {
					decryptMedia(message).then(mediaData => {
					bocchi.sendMp4AsSticker(from, mediaData, null, { author:`${arg.split('|')[1]}`, pack: `${arg.split('|')[0]}` })
					})
					console.log(timeLog)
				} else if (quotedMsg && quotedMsgObj.mimetype == 'video/mp4' || quotedMsgObj.mimetype == 'image/gif') {
					decryptMedia(quotedMsg).then(mediaData => {
					bocchi.sendMp4AsSticker(from, mediaData, null, { author:`${arg.split('|')[1]}`, pack: `${arg.split('|')[0]}` })
					console.log(timeLog)
					})
				}
			break`

**Comment by gabrielwsy** [comment]
> > In the previous code that I had, the animated figurines (stickergif) when made, were resized, that is, it would not cut if it was too wide.
> > However, this new code, the animated figures are becoming centralized, cut if the figure is wide.
> > I would like to know how I do to resize.
> > Thank you very much in advance.
> 
> What module did you use for creating a GIFs?

how do i see the module? sorry, I'm a layman
![image](https://user-images.githubusercontent.com/40281950/106478167-b4b42700-6487-11eb-84bc-968b62633669.png)

this is my case => https://pastebin.com/iu3Eb04s

**Comment by SlavyanDesu** [comment]
May I see your previous code that will resize the input, please?

**Comment by gabrielwsy** [comment]
> May I see your previous code that will resize the input, please?

case stickergif: https://pastebin.com/H07UzRKR

I noticed that when using the old code, it appears in cmd:
![image](https://user-images.githubusercontent.com/40281950/106484354-4d4da580-648e-11eb-9fd4-c873d7d107c2.png)

When using the updated code, no in cmd does not appear:
![image](https://user-images.githubusercontent.com/40281950/106484631-97cf2200-648e-11eb-953d-5e06c5bf2c30.png)

**Comment by VideFrelan** [comment]
> > > In the previous code that I had, the animated figurines (stickergif) when made, were resized, that is, it would not cut if it was too wide.
> > > However, this new code, the animated figures are becoming centralized, cut if the figure is wide.
> > > I would like to know how I do to resize.
> > > Thank you very much in advance.
> > 
> > 
> > What module did you use for creating a GIFs?
> 
> how do i see the module? sorry, I'm a layman
> ![image](https://user-images.githubusercontent.com/40281950/106478167-b4b42700-6487-11eb-84bc-968b62633669.png)
> 
> this is my case => https://pastebin.com/iu3Eb04s

You can set the crop to false

**Comment by SlavyanDesu** [comment]
Based on how @VideFrelan answers, this should be done by adding a `crop` parameter in [`client.sendMp4AsSticker`](https://docs.openwa.dev/classes/client.html#sendmp4assticker).

**_In this case, it can be done something like this_**:
```js
await bocchi.sendMp4AsSticker(from, videoBase64, { crop: false, fps: 30, startTime: '00:00:00.0', endTime:'00:00:05.0', loop: 0 })
```
There's more options you can configure, consider to read the docs [here](https://docs.openwa.dev/globals.html#mp4stickerconversionprocessoptions).

**_Reminder_**:
Please close the issue if your issue(s) has been resolved, thanks.

**Comment by gabrielwsy** [comment]
Thank you very much for your help, problem solved.
