### ISSUE TITLE
English Translation [INFO]

### ISSUE THREAD

**Issue by SlavyanDesu** [SlavyanDesu/BocchiBot#219]
I will be focusing on translating the `ind.js` to English due to the lack of English lines currently.
Any help on the grammars will be appreciated.

**Comment by AndrewDaGuy** [comment]
Sure, how do I help? ;)

**Comment by SlavyanDesu** [comment]
> Sure, how do I help? ;)

Thanks for that. I need a proof reader to review `eng.js` because my English is not so good.

**Comment by SlavyanDesu** [comment]
I will update `eng.js` ASAP. After that, you can start to proof read it. :D

**Comment by AndrewDaGuy** [comment]
> I will update `eng.js` ASAP. After that, you can start to proof read it. :D

uhhh you're a little too late for that ._.

**Comment by SlavyanDesu** [comment]
LMAO SORRY

**Comment by SlavyanDesu** [comment]
Yo @AndrewDaGuy, you can start the review now. :^)
