### ISSUE TITLE
Limit stack 24

### ISSUE THREAD

**Issue by rasmaniID** [SlavyanDesu/BocchiBot#222]
min limitnya cuma bisa sampe 24 dari 25 nih gak mau lebih jadi user nya kek gak ada limit jadi leluasa gitu gimana
![Screenshot_20210203_151458](https://user-images.githubusercontent.com/76784400/106717951-f6350580-6632-11eb-8cd1-d96764e6c6d6.jpg)

**Comment by SlavyanDesu** [comment]
Maksudnya gak ada limit gimana?

**Comment by rasmaniID** [comment]
> Maksudnya gak ada limit gimana?

limitnya gak mau 25 min nge stack di 24
