### ISSUE TITLE
command sticker

### ISSUE THREAD

**Issue by Fucksociety666** [SlavyanDesu/BocchiBot#234]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

![image](https://user-images.githubusercontent.com/74858900/107360703-32061a00-6ace-11eb-8a80-257e155e186b.png)

**Comment by SlavyanDesu** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context**
> Add any other context about the problem here.
> 
> ![image](https://user-images.githubusercontent.com/74858900/107360703-32061a00-6ace-11eb-8a80-257e155e186b.png)

Udah pake command sesuai format?

**Comment by Fucksociety666** [comment]
udah contoh !stcwm tes | tes

**Comment by rafaelmwah** [comment]
itu dari wa nya mas,dilihat lagi
di setting terus ke penyimpanan dan data terus ke unduh otomatis

**Comment by Fucksociety666** [comment]
> ilihat lagi
> di setting terus ke penyimpanan dan data terus ke unduh otomatis

unduh otomatis di aktifkan?

**Comment by rafaelmwah** [comment]
> > ilihat lagi
> > di setting terus ke penyimpanan dan data terus ke unduh otomatis
> 
> unduh otomatis di aktifkan?

Iya bener kak diaktifkan

**Comment by SlavyanDesu** [comment]
Ini error dari wa-automate-nodejs, silakan bikin issue di [sini](https://github.com/open-wa/wa-automate-nodejs/issues), terima kasih.
