### ISSUE TITLE
why am i getting this error? And how to solve

### ISSUE THREAD

**Issue by NaldoMota1** [SlavyanDesu/BocchiBot#237]
![Capturar](https://user-images.githubusercontent.com/71650872/107780696-c7e7b200-6d25-11eb-8b08-c904d416fdd9.PNG)

**Comment by shydoll-02** [comment]
yea, i think this is a problem with open-wa

**Comment by shydoll-02** [comment]
btw,,, dont yiu guys think baileys is better nowadays
??

**Comment by Baguettou** [comment]
Just update Open-wa, go to the folder of the bot and write in the command prompt `npm update` and `npm upgrade`.

**Comment by SlavyanDesu** [comment]
> btw,,, dont yiu guys think baileys is better nowadays
> ??

It's less resources usage. But for the features, I think open-wa is slightly better.

**Comment by SlavyanDesu** [comment]
Closed, it seems that the issue was resolved by @Baguettou.
