### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by bocchibotlovers** [SlavyanDesu/BocchiBot#243]
perintah user ga di respon sama bot, di console ada log exec tapi ga di respon sama bot

**Comment by SlavyanDesu** [comment]
> perintah user ga di respon sama bot, di console ada log exec tapi ga di respon sama bot

Update bot ke versi terbaru atau copy dan paste ini ke file `index.js`.
https://github.com/SlavyanDesu/BocchiBot/blob/73fea6bd4245564252fdad51561576aec4c63d51/index.js#L1-L133

**Comment by SlavyanDesu** [comment]
Closed. Issue tidak aktif selama lebih dari 5 hari.
