### ISSUE TITLE
Eror

### ISSUE THREAD

**Issue by Envious7777** [SlavyanDesu/BocchiBot#247]
Eror di arm64

**Comment by SlavyanDesu** [comment]
Sertakan screenshot.

**Comment by Envious7777** [comment]
![Screenshot from 2021-02-18 23-25-10](https://user-images.githubusercontent.com/35870230/108335858-fa058200-7205-11eb-8128-0e0e41bd1366.png)

**Comment by SlavyanDesu** [comment]
Run `npm install`

**Comment by Envious7777** [comment]
tetep gabsa bang 
![Screenshot from 2021-02-18 23-56-27](https://user-images.githubusercontent.com/35870230/108339735-5f5b7200-720a-11eb-8748-f31aa00dddfb.png)

**Comment by Envious7777** [comment]
![Screenshot from 2021-02-18 23-56-22](https://user-images.githubusercontent.com/35870230/108339786-6edabb00-720a-11eb-8fa5-7f1eaa9010b9.png)

**Comment by SlavyanDesu** [comment]
Versi Node.js berapa?

**Comment by Envious7777** [comment]
tetep eror a :(
npm -v
7.5.4
node -v
v15.9.0
