### ISSUE TITLE
ERROR WEBP-converter

### ISSUE THREAD

**Issue by aracuans** [SlavyanDesu/BocchiBot#248]
![image](https://user-images.githubusercontent.com/75974459/108285645-25fb1600-71ba-11eb-9de3-f1d7319596f7.png)
Webpmux done install + path
ffmpeg done install + path

Salah nya dmna ya bang?

**Comment by Baguettou** [comment]
1. Try to execute `npm update` and `npm upgrade` in te command prompt.
2. Check that in properties of the directory `node_modules\webp_converter` the option `Read only` it's unchecked.
3. Try to make a directory named `temp` inside of  `node_modules\webp_converter`

**Comment by aracuans** [comment]
> 1. Try to execute `npm update` and `npm upgrade` in te command prompt.
> 2. Check that in properties of the directory `node_modules\webp_converter` the option `Read only` it's unchecked.
> 3. Try to make a directory named `temp` inside of  `node_modules\webp_converter`

thank you for your answers. I will try it now

**Comment by Baguettou** [comment]
Did it work? :D

**Comment by aracuans** [comment]
> Did it work? :D

WORK THANKS:D

**Comment by SlavyanDesu** [comment]
> > Did it work? :D
> 
> WORK THANKS:D

Worknya digimanain?

**Comment by irham01** [comment]
> > > Did it work? :D
> > 
> > 
> > WORK THANKS:D
> 
> Worknya digimanain?

Try to make a directory named temp inside of node_modules\webp_converter
itu sih kayaknya...

**Comment by Baguettou** [comment]
Is there something wrong? :0

**Comment by SlavyanDesu** [comment]
Nah, just curious which solution is worked

**Comment by aracuans** [comment]
> Nah, just curious which solution is worked

disitu udah jelas bang gw nya aja otaknya tumlul:v 
disitu log nya no such file or directory. setelah gw cek di folder webp-converter nya memang gada folder temp. setelah gw buat folder temp baru bisa.

**Comment by DwiP27** [comment]
![issues](https://user-images.githubusercontent.com/66292964/110229969-ea917300-7f3f-11eb-8c77-37255274d8a3.png)
![issues2](https://user-images.githubusercontent.com/66292964/110229972-f11fea80-7f3f-11eb-87c4-8ed6e0559bb2.png)

**Comment by DwiP27** [comment]
aku bingung udh npm upgrade masih ja sama add temp

**Comment by DwiP27** [comment]
(node:7404) UnhandledPromiseRejectionWarning 
what it this?

**Comment by Destiny-cpu** [comment]
What do you mean because I don't understand

**Comment by NakanoMikuG75** [comment]
![Uploading IMG-20210328-WA0319.jpeg…]()
Solusi
