### ISSUE TITLE
Eval?

### ISSUE THREAD

**Issue by shansekai** [SlavyanDesu/BocchiBot#25]
Bagaimana cara menggunakan command eval?

**Comment by SlavyanDesu** [comment]
> Bagaimana cara menggunakan command eval?

![1](https://user-images.githubusercontent.com/28254882/101794532-8c6c1400-3b39-11eb-8f29-1a6c99f58aa8.png)

**Comment by SlavyanDesu** [comment]
Command eval gunanya buat eksekusi javascript code

**Comment by shansekai** [comment]
Ouh oke oke ngerti. Thx
