### ISSUE TITLE
Tutorial pasang Libwebp agar work stcwm by bang pliss, saya masih bingung

### ISSUE THREAD

**Issue by danta487** [SlavyanDesu/BocchiBot#256]
Tutorial pasang libwebp, saya bingung bang caranya gimana

**Comment by Baguettou** [comment]
I could help you making a short video, what OS are you using, linux or Windows?

**Comment by VideFrelan** [comment]
Kalau pakai Windows, harap buka issue ini: [here](https://github.com/SlavyanDesu/BocchiBot/issues/163#issuecomment-761568680)

**Comment by VideFrelan** [comment]
Kalau masih error harap buka issue baru, atau pakai sticker metadata saja biar lebih mudah
```js
await client.sendImageAsSticker(from, imageBase64, { author: 'AuthorName', pack: 'PackName' })
```
