### ISSUE TITLE
SendMessageWithThumb

### ISSUE THREAD

**Issue by hardiantojek93** [SlavyanDesu/BocchiBot#258]
**Question**
What would you like to ask?
Cara make nya gimana  kemarin coba Segala cara tapi game work

**Comment by SlavyanDesu** [comment]
> **Question**
> What would you like to ask?
> Cara make nya gimana kemarin coba Segala cara tapi game work

https://docs.openwa.dev/classes/client.html#sendmessagewiththumb

**Comment by hardiantojek93** [comment]
Tetep ga ngerti udah baca doc

**Comment by SlavyanDesu** [comment]
Coba liat code-nya kayak gimana

**Comment by hardiantojek93** [comment]
sendMessageWithThumb(from, base64, photo_realnya, 'hmm.jpg', '')

**Comment by SlavyanDesu** [comment]
Yang lengkap bro

**Comment by hardiantojek93** [comment]
Ntar ku buat lagi
