### ISSUE TITLE
Limit cmds

### ISSUE THREAD

**Issue by selyxn** [SlavyanDesu/BocchiBot#26]
Plis tambahkan fitur limit :(

Itung-itung supaya fitur premium ku ada guna nya :v

**Comment by selyxn** [comment]
> Plis tambahkan fitur limit :(
> 
> Itung-itung supaya fitur premium ku ada guna nya :v

kacang :( @SlavyanDesu

**Comment by SlavyanDesu** [comment]
> Plis tambahkan fitur limit :(
> 
> Itung-itung supaya fitur premium ku ada guna nya :v

Nanti. Pake command `$premium <add/del>` aja dulu, soalnya bot ku rencananya nggak di limit command gitu.

**Comment by SlavyanDesu** [comment]
Atau nggak, masuk-masukin function limit dari bot Elaina ke Bocchi tapi harus disesuain lagi

**Comment by selyxn** [comment]
> > Plis tambahkan fitur limit :(
> > Itung-itung supaya fitur premium ku ada guna nya :v
> 
> Nanti. Pake command `$premium <add/del>` aja dulu, soalnya bot ku rencananya nggak di limit command gitu.

Iya aku sdh ada fitur premium, tetapi kurang enak rasanya kalau user non premium gaada limit cmds nya
Kalau boleh, agan buatkan/tambahkan cmd limit, nanti kucontoh ke sc aku

limit yg di elainabot ada bug kalo gasalah & kurang menurutku, ga bisa set time dari 21.00 ke yang kita mau

**Comment by shansekai** [comment]
> Iya aku sdh ada fitur premium, tetapi kurang enak rasanya kalau user non premium gaada limit cmds nya
> Kalau boleh, agan buatkan/tambahkan cmd limit, nanti kucontoh ke sc aku
> 
> limit yg di elainabot ada bug kalo gasalah & kurang menurutku, ga bisa set time dari 21.00 ke yang kita mau

Jalanin pakai pm2 terus tambahin cron biar auto restart

https://github.com/ArugaZ/whatsapp-bot/issues/151#issuecomment-739247442

**Comment by selyxn** [comment]
> > Iya aku sdh ada fitur premium, tetapi kurang enak rasanya kalau user non premium gaada limit cmds nya
> > Kalau boleh, agan buatkan/tambahkan cmd limit, nanti kucontoh ke sc aku
> > limit yg di elainabot ada bug kalo gasalah & kurang menurutku, ga bisa set time dari 21.00 ke yang kita mau
> 
> Jalanin pakai pm2 terus tambahin cron biar auto restart
> 
> [ArugaZ/whatsapp-bot#151 (comment)](https://github.com/ArugaZ/whatsapp-bot/issues/151#issuecomment-739247442)

lah gw ga mnta cronjob

**Comment by shansekai** [comment]
Kan nyaranin

Sekali sekali mandiri lah jgn suruh org mulu

**Comment by selyxn** [comment]
> Kan nyaranin
> 
> Sekali sekali mandiri lah jgn suruh org mulu

saran lu ga sesuai dngn topik gw
bkn nyuruh tpi request
