### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by skout22** [SlavyanDesu/BocchiBot#261]
(node:16700) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: getQrPng is not defined
    at __puppeteer_evaluation_script__:1:1
    at ExecutionContext._evaluateInternal (C:\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:17
2:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (C:\bot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:107:1
6)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16700) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing ins
ide of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To termin
ate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodej
s.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16700) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejection
s that are not handled will terminate the Node.js process with a non-zero exit code.
![{B8323238-4F2B-4DC2-A525-1537F9A1CCA6} png](https://user-images.githubusercontent.com/21192745/109086281-3ffea080-7746-11eb-90c4-ea6180e5a83b.jpg)

**Comment by VirusLauncher** [comment]
@skout22 It was an open-wa/wa-automate problem, they have fixed it within the latest version.
Run: npm @open-wa/wa-automate @latest
