### ISSUE TITLE
genshin impact api

### ISSUE THREAD

**Issue by AllMightHero** [SlavyanDesu/BocchiBot#267]
npm ERR! code ENOVERSIONS
npm ERR! No versions available for genshin-impact-api

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-02T17_06_37_715Z-debug.log

**Comment by khaadaj** [comment]
just search for "genshin-impact-api" and delete

**Comment by SlavyanDesu** [comment]
The module (`genshin-impact-api`) has changed their name to `genshin`. Please update your source code to the latest version and perform the module installation once again. Make sure you have deleted `node_modules` folder first!

**_Run this_**:
```cmd
> git pull origin master
> npm install
```

**Comment by AllMightHero** [comment]
Ty
