### ISSUE TITLE
Token whatsapp

### ISSUE THREAD

**Issue by ozandesu** [SlavyanDesu/BocchiBot#268]
Bang, nama file untuk token whatsapp apa ya? Kok saya pas buat Bocchibot.data.json ga kebaca, trus malah menampilkan QR, pas  gw mau scan malah   QR nya ga tertata rapi.

**Comment by SlavyanDesu** [comment]
> Bang, nama file untuk token whatsapp apa ya? Kok saya pas buat Bocchibot.data.json ga kebaca, trus malah menampilkan QR, pas gw mau scan malah QR nya ga tertata rapi.

File `BocchiBot.data.json` nggak bisa dibuat secara manual. Hapus filenya, terus scan QR biasa. Kalau QR-nya gak tertata rapih, pakai terminal lain aja.

**Comment by ozandesu** [comment]
> > Bang, nama file untuk token whatsapp apa ya? Kok saya pas buat Bocchibot.data.json ga kebaca, trus malah menampilkan QR, pas gw mau scan malah QR nya ga tertata rapi.
> 
> File `BocchiBot.data.json` nggak bisa dibuat secara manual. Hapus filenya, terus scan QR biasa. Kalau QR-nya gak tertata rapih, pakai terminal lain aja.

Buatin dong bang, biar bisa manual soalnya user herokuapp ga mungkin bisa pake script ini .

**Comment by SlavyanDesu** [comment]
> > > Bang, nama file untuk token whatsapp apa ya? Kok saya pas buat Bocchibot.data.json ga kebaca, trus malah menampilkan QR, pas gw mau scan malah QR nya ga tertata rapi.
> > 
> > 
> > File `BocchiBot.data.json` nggak bisa dibuat secara manual. Hapus filenya, terus scan QR biasa. Kalau QR-nya gak tertata rapih, pakai terminal lain aja.
> 
> Buatin dong bang, biar bisa manual soalnya user herokuapp ga mungkin bisa pake script ini .

Ya nggak bisa, token ini sifatnya unik. Ga bisa di-recreate secara manual. Kamu bisa scan QR ini di PC, lalu pindahin file token-nya ke Heroku.

**Comment by ozandesu** [comment]
> > > > Bang, nama file untuk token whatsapp apa ya? Kok saya pas buat Bocchibot.data.json ga kebaca, trus malah menampilkan QR, pas gw mau scan malah QR nya ga tertata rapi.
> > > 
> > > 
> > > File `BocchiBot.data.json` nggak bisa dibuat secara manual. Hapus filenya, terus scan QR biasa. Kalau QR-nya gak tertata rapih, pakai terminal lain aja.
> > 
> > 
> > Buatin dong bang, biar bisa manual soalnya user herokuapp ga mungkin bisa pake script ini .
> 
> Ya nggak bisa, token ini sifatnya unik. Ga bisa di-recreate secara manual. Kamu bisa scan QR ini di PC, lalu pindahin file token-nya ke Heroku.

Caranya gimana ya, gw masih pemula

**Comment by SlavyanDesu** [comment]
Ya copy aja file `BocchiBot.data.json` yang udah ada tokennya ke Heroku, cara mindahin file-nya saya kurang tau karena gak pernah pakai. Bisa cari di Google.
