### ISSUE TITLE
Group features

### ISSUE THREAD

**Issue by Suryapardana** [SlavyanDesu/BocchiBot#271]
Fitur group yang antilink dan antinsfw kenapa cuma safe link saja tetapi tidak di kick?

**Comment by SlavyanDesu** [comment]
Maksudnya?

**Comment by Suryapardana** [comment]
Pada saat antilink diaktifkan orang ngirim link group tapi tidak ter kick, saya lihat di console log padahal tulisannya link safe gitu, apakah ini bug atau bagaimana?

**Comment by SlavyanDesu** [comment]
Link safe berarti aman, selain dari itu terkick.
Fitur anti-link di sini hanya berlaku untuk link WhatsApp group.

**Comment by SlavyanDesu** [comment]
Dicoba saja kirim link undangan grup ke grup.

**Comment by VideFrelan** [comment]
Pasti work kok, safe link artinya link aman, sebaliknya linnk tidak aman dan bot akan ngekick si pengirim link grup jika antilink nya diaktifkan.
