### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by Netsh1** [SlavyanDesu/BocchiBot#272]
**Question**
What would you like to ask?
Gimana ni cara ngatasinnya
![Screenshot_2021-03-06-14-51-28-968_com termux](https://user-images.githubusercontent.com/78953900/110199571-9036da80-7e8b-11eb-8dae-09e7953bc2cd.png)

**Comment by SlavyanDesu** [comment]
Sertain informasi lebih lanjut

**Comment by Netsh1** [comment]
> Sertain informasi lebih lanjut

Itu lagi npm install

**Comment by Netsh1** [comment]
Pas npm start gini hasil nya 
![Uploading Screenshot_2021-03-06-15-59-22-437_com.termux.png…]()

**Comment by Netsh1** [comment]
Pas npm start gini hasilnya
![Screenshot_2021-03-06-15-59-22-437_com termux](https://user-images.githubusercontent.com/78953900/110201340-24596f80-7e95-11eb-8383-fdcf4e21b21d.png)

**Comment by SlavyanDesu** [comment]
Ini termux atau make RDP lewat CLI?

**Comment by Netsh1** [comment]
> Ini termux atau make RDP lewat CLI?

Termux

**Comment by Suryapardana** [comment]
> > Ini termux atau make RDP lewat CLI?
> 
> Termux

Opem wa tidak bisa dipakai di termux

**Comment by SlavyanDesu** [comment]
Library open-wa nggak bisa pakai Termux, karena pake headless Chromium.
