### ISSUE TITLE
premium

### ISSUE THREAD

**Issue by DwiP27** [SlavyanDesu/BocchiBot#273]
saat add user premium bisa tetapi saat menggunakan fitur premium tidak bisa dengan peringatan kamu belum menjadi premium

**Comment by Suryapardana** [comment]
Make sure you have entered the database number

**Comment by VideFrelan** [comment]
Coba di cek di database premium nya, apakah nomor tersebut tersedia atau tidak

**Comment by DwiP27** [comment]
ada kak,sama fitur welcome nih , kalau habis bersihin chat tiba2 langsung spam welcome nya, gmna tuh bang

**Comment by SlavyanDesu** [comment]
> ada kak,sama fitur welcome nih , kalau habis bersihin chat tiba2 langsung spam welcome nya, gmna tuh bang

Spam welcome emang ini sering terjadi, kemungkinan error dari open-wa alias error library-nya

**Comment by squerenix** [comment]
Add premium kalau pribadi jangan pake tanda apa apa langsung 628xxxxxxxx, klw di group ditag orangnya bisa

**Comment by hardiantojek93** [comment]
> saat add user premium bisa tetapi saat menggunakan fitur premium tidak bisa dengan peringatan kamu belum menjadi premium

Coba liat case nya yg 
if (isPremium) 
Ganti jadi
If (!isPremium)
