### ISSUE TITLE
After installing the bot, it doesn't do anything.

### ISSUE THREAD

**Issue by DilieCat** [SlavyanDesu/BocchiBot#274]
<img width="674" alt="Screenshot 2021-03-07 at 17 25 51" src="https://user-images.githubusercontent.com/15648402/110246995-36f1a880-7f6a-11eb-8397-094c07e25c1f.png">

**Comment by VideFrelan** [comment]
Have you updated the source to the latest version?

**Comment by DilieCat** [comment]
> Have you updated the source to the latest version?

Yes, it is in version 0.7.0 now.

**Comment by Baguettou** [comment]
Check if you are using the correct prefix for the bot,

**Comment by SlavyanDesu** [comment]
Closed due to the inactivity.
