### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by DwiP27** [SlavyanDesu/BocchiBot#276]
**Question**
Saat saya menambahkan bot, ada balasan "max groups reached!" Saya mau merubah kata itu , dan dimana file.js nya ?, Dan saya ingin mengubah batas maksimal bergabung dalam grup ?

Thanks

**Comment by Destiny-cpu** [comment]
Why is boochi bot unavailable

**Comment by Baguettou** [comment]
If you want to modify the member limit and group limit of the bot you can do it in:

* BocchiBot/database/bot/setting.json

```
{
    "memberLimit": "x",
    "groupLimit": "y"
}
```

* x = Minimum number of members that a group need for the bot to work correctly.
* y = Maximum number of groups that the bot can be into at the same time.

I hope this help you ^ - ^

**Comment by SlavyanDesu** [comment]
Dan untuk merubah kata "Max groups reached!" bisa diganti di `BocchiBot/index.js`.
https://github.com/SlavyanDesu/BocchiBot/blob/7f634ac0b4c912b47bb3c57e290bfe4e58ca4028/index.js#L37
