### ISSUE TITLE
LIMIT BUG

### ISSUE THREAD

**Issue by squerenix** [SlavyanDesu/BocchiBot#278]
kak ada bug di limit, Limit sudah 0 tetep bisa menggunakan command, dan terkadang limit stuck No Drop

**Comment by VideFrelan** [comment]
> kak ada bug di limit, Limit sudah 0 tetep bisa menggunakan command, dan terkadang limit stuck No Drop

Pastikan isLimit sebagai penanda limit sudah habis, dan addLimit sebagai pengurang limit sudah ada di setiap case

**Comment by squerenix** [comment]
Minta contoh kak
