### ISSUE TITLE
Increase limit

### ISSUE THREAD

**Issue by powermx** [SlavyanDesu/BocchiBot#295]
Hello, how could I increase or reduce time for límit request.?

![IMG-20210323-WA0409](https://user-images.githubusercontent.com/29370715/112243422-1f294e00-8c13-11eb-8f4d-afe5e78f684e.jpg)
**Question**
What would you like to ask?

**Comment by powermx** [comment]
Where could i change that limit time?

**Comment by SlavyanDesu** [comment]
> Where could i change that limit time?

https://github.com/SlavyanDesu/BocchiBot/blob/65bf1fcb37cb17ca1b073e88a8c7b43117912ed9/message/index.js#L65
it's 12 hours in milliseconds

**Comment by SlavyanDesu** [comment]
`4.32e+7` equals `43200000`
i simplim

**Comment by SlavyanDesu** [comment]
`4.32e+7` equals `43200000`
you can use `18000000`
