### ISSUE TITLE
Cannot find module 'canvacord'

### ISSUE THREAD

**Issue by mantulity** [SlavyanDesu/BocchiBot#296]
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'canvacord'
Require stack:

bisa dibantu bagian mana yang salah ya?

**Comment by hardiantojek93** [comment]
> internal/modules/cjs/loader.js:883
> throw err;
> ^
> 
> Error: Cannot find module 'canvacord'
> Require stack:
> 
> bisa dibantu bagian mana yang salah ya?

npm i canvacord
