### ISSUE TITLE
Error pada command sticker

### ISSUE THREAD

**Issue by farrasrayhand** [SlavyanDesu/BocchiBot#297]
**Describe the bug**
Error saat menggunakan command $sticker

**Screenshots**
![image](https://user-images.githubusercontent.com/35839373/112486245-a9f67e00-8db6-11eb-8ac3-1c4343690225.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS

**Comment by SlavyanDesu** [comment]
duplicate of https://github.com/SlavyanDesu/BocchiBot/issues/248
silakan kunjungi issue tertera, terima kasih
