### ISSUE TITLE
$sgif not work

### ISSUE THREAD

**Issue by farrasrayhand** [SlavyanDesu/BocchiBot#298]
![image](https://user-images.githubusercontent.com/35839373/112562661-c1635480-8e12-11eb-88ec-09cd4fb71d94.png)
![image](https://user-images.githubusercontent.com/35839373/112562700-da6c0580-8e12-11eb-9ff0-0c0f2273689b.png)

**Comment by hardiantojek93** [comment]
> install + path ffmpeg mybe

**Comment by VideFrelan** [comment]
Update versi open-wa/wa-automate versi terbaru

```cmd
npm i @open-wa/wa-automate@latest
