### ISSUE TITLE
Downloading Patches

### ISSUE THREAD

**Issue by squerenix** [SlavyanDesu/BocchiBot#300]
how should I fix it when it says "Downloading Patches" in CMD? I wait endless.

**Comment by NaldoMota1** [comment]
update the open wa library

npm i --save @open-wa/wa-automate@latest

**Comment by VideFrelan** [comment]
> how should I fix it when it says "Downloading Patches" in CMD? I wait endless.

Hi, please update to the latest version of open-wa/wa-automate

```cmd
npm i @open-wa/wa-automate@latest
