### ISSUE TITLE
Can you help me!!

### ISSUE THREAD

**Issue by squerenix** [SlavyanDesu/BocchiBot#305]
![image](https://user-images.githubusercontent.com/52381026/113494326-7ed80100-9511-11eb-9d4e-e4de96d2f5e2.png)

**Comment by SlavyanDesu** [comment]
have you installed webpmux?

**Comment by SlavyanDesu** [comment]
well, im about to recode for the stickers command. it will no longer use manual webpmux, gonna use built-in sticker metadata instead

**Comment by SlavyanDesu** [comment]
@squerenix try to update the source code to the latest one
