### ISSUE TITLE
REQ

### ISSUE THREAD

**Issue by MrPawNO** [SlavyanDesu/BocchiBot#31]
Fitur youtubesearch(yts)
api dari vhtear

Thanks ngab

**Comment by SlavyanDesu** [comment]
Noted

**Comment by MrPawNO** [comment]
> Noted

acc pull ku ngab, itung-itung request sekalian berkontribusi :D

**Comment by SlavyanDesu** [comment]
> > Noted
> 
> acc pull ku ngab, itung-itung request sekalian berkontribusi :D

sudah. btw ini yt search ada documentationnya gak? soalnya apikey yang agan kasih gak bisa dipake

**Comment by MrPawNO** [comment]
> > > Noted
> > 
> > 
> > acc pull ku ngab, itung-itung request sekalian berkontribusi :D
> 
> sudah. btw ini yt search ada documentationnya gak? soalnya apikey yang agan kasih gak bisa dipake

ohiya baru diganti apikey nya, cek dm

**Comment by SlavyanDesu** [comment]
> Fitur youtubesearch(yts)
> api dari vhtear
> 
> Thanks ngab

Done~ https://github.com/SlavyanDesu/BocchiBot/commit/2f1c4228fcbb5075fa19ad44fb82bde3f7289679
