### ISSUE TITLE
internal/modules/cjs/loader.js:1015       throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);       ^

### ISSUE THREAD

**Issue by mioscape** [SlavyanDesu/BocchiBot#313]
**Question**
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /root/BocchiBot/node_modules/parse-ms/index.js
require() of ES modules is not supported.
require() of /root/BocchiBot/node_modules/parse-ms/index.js from /root/BocchiBot/message/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /root/BocchiBot/node_modules/parse-ms/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /root/BocchiBot/node_modules/parse-ms/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1015:13)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/BocchiBot/message/index.js:42:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  code: 'ERR_REQUIRE_ESM'
}
![image](https://user-images.githubusercontent.com/43681888/114410873-e8bd6e00-9bd5-11eb-85db-e53e12aa148b.png)

**Comment by shansekai** [comment]
> **Question**
> Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /root/BocchiBot/node_modules/parse-ms/index.js
> require() of ES modules is not supported.
> require() of /root/BocchiBot/node_modules/parse-ms/index.js from /root/BocchiBot/message/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
> Instead rename /root/BocchiBot/node_modules/parse-ms/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /root/BocchiBot/node_modules/parse-ms/package.json.
> 
> ```
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1015:13)
> at Module.load (internal/modules/cjs/loader.js:863:32)
> at Function.Module._load (internal/modules/cjs/loader.js:708:14)
> at Module.require (internal/modules/cjs/loader.js:887:19)
> at require (internal/modules/cjs/helpers.js:74:18)
> at Object.<anonymous> (/root/BocchiBot/message/index.js:42:12)
> at Module._compile (internal/modules/cjs/loader.js:999:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
> at Module.load (internal/modules/cjs/loader.js:863:32)
> at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
> ```
> 
> code: 'ERR_REQUIRE_ESM'
> }
> ![image](https://user-images.githubusercontent.com/43681888/114410873-e8bd6e00-9bd5-11eb-85db-e53e12aa148b.png)

Downgrade module "parse-ms" to 2.1.0

**Comment by mioscape** [comment]
> > **Question**
> > Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /root/BocchiBot/node_modules/parse-ms/index.js
> > require() of ES modules is not supported.
> > require() of /root/BocchiBot/node_modules/parse-ms/index.js from /root/BocchiBot/message/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
> > Instead rename /root/BocchiBot/node_modules/parse-ms/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /root/BocchiBot/node_modules/parse-ms/package.json.
> > ```
> > at Object.Module._extensions..js (internal/modules/cjs/loader.js:1015:13)
> > at Module.load (internal/modules/cjs/loader.js:863:32)
> > at Function.Module._load (internal/modules/cjs/loader.js:708:14)
> > at Module.require (internal/modules/cjs/loader.js:887:19)
> > at require (internal/modules/cjs/helpers.js:74:18)
> > at Object.<anonymous> (/root/BocchiBot/message/index.js:42:12)
> > at Module._compile (internal/modules/cjs/loader.js:999:30)
> > at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
> > at Module.load (internal/modules/cjs/loader.js:863:32)
> > at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
> > ```
> > 
> > 
> > code: 'ERR_REQUIRE_ESM'
> > }
> > ![image](https://user-images.githubusercontent.com/43681888/114410873-e8bd6e00-9bd5-11eb-85db-e53e12aa148b.png)
> 
> Downgrade module "parse-ms" to 2.1.0

How?

**Comment by mioscape** [comment]
> > **Question**
> > Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /root/BocchiBot/node_modules/parse-ms/index.js
> > require() of ES modules is not supported.
> > require() of /root/BocchiBot/node_modules/parse-ms/index.js from /root/BocchiBot/message/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
> > Instead rename /root/BocchiBot/node_modules/parse-ms/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /root/BocchiBot/node_modules/parse-ms/package.json.
> > ```
> > at Object.Module._extensions..js (internal/modules/cjs/loader.js:1015:13)
> > at Module.load (internal/modules/cjs/loader.js:863:32)
> > at Function.Module._load (internal/modules/cjs/loader.js:708:14)
> > at Module.require (internal/modules/cjs/loader.js:887:19)
> > at require (internal/modules/cjs/helpers.js:74:18)
> > at Object.<anonymous> (/root/BocchiBot/message/index.js:42:12)
> > at Module._compile (internal/modules/cjs/loader.js:999:30)
> > at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
> > at Module.load (internal/modules/cjs/loader.js:863:32)
> > at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
> > ```
> > 
> > 
> > code: 'ERR_REQUIRE_ESM'
> > }
> > ![image](https://user-images.githubusercontent.com/43681888/114410873-e8bd6e00-9bd5-11eb-85db-e53e12aa148b.png)
> 
> Downgrade module "parse-ms" to 2.1.0

Never mind, i'll search it. Thanks!
