### ISSUE TITLE
Please help me out?

### ISSUE THREAD

**Issue by DannySalvatore** [SlavyanDesu/BocchiBot#316]
Please make a video on how to generate QR code in termux!!
Please

**Comment by SlavyanDesu** [comment]
> Please make a video on how to generate QR code in termux!!
> Please

Sorry but open-wa doesn't support Termux

**Comment by Destiny-cpu** [comment]
> > Please make a video on how to generate QR code in termux!!
> > Please
> 
> Sorry but open-wa doesn't support Termux

Cant you change it from open wa to baileys so that handphone users can use it
