### ISSUE TITLE
Pregunta

### ISSUE THREAD

**Issue by nadiepop** [SlavyanDesu/BocchiBot#318]
¿cómo añado a bocchi a mi grupo de Whatsapp?

**Comment by Baguettou** [comment]
Hola, disculpa la respuesta tardía; BocchiBot no es un contacto o número específico de WhatsApp, sino que es un proyecto para que tú hagas tu propio ChatBot (aunque en realidad ya viene con comandos y funciones prediseñadas), su instalación es muy sencilla, la puedes revisar aquí: 

- [Requisitos](https://github.com/SlavyanDesu/BocchiBot#requirements) y luego revisa [ los pasos de instalación](https://github.com/SlavyanDesu/BocchiBot#installation) propiamente.

Cualquier duda déjanos saberlo y recuerda tener un buen día :D
