### ISSUE TITLE
How to stop the bot fom sending welcome and goodbye images

### ISSUE THREAD

**Issue by necrosome-lab** [SlavyanDesu/BocchiBot#330]
Hello.
I wonder if it's possible to stop the bot from sending the welcome and goodbye **images** because it satures the gallery of the group members.
I just want the welcome feature to send the welcoming **text** because i use it for members to read the group rules.
Thanks.

**Comment by 4NUR46** [comment]
Check index.js file of bot and comment the welcome and remove member function or just comment the variable where it gets the image of user and sent on group

**Comment by 4NUR46** [comment]
> Hello.
> I wonder if it's possible to stop the bot from sending the welcome and goodbye **images** because it satures the gallery of the group members.
> I just want the welcome feature to send the welcoming **text** because i use it for members to read the group rules.
> Thanks.

Check index.js file of bot and comment the welcome and remove member function or just comment the variable where it gets the image of user and sent on group
