### ISSUE TITLE
Help ngab:'v Balik² mulu setelah npm start bng

### ISSUE THREAD

**Issue by yoga875** [SlavyanDesu/BocchiBot#349]
**Question**
What would you like to ask?
Setelah npm start bolak balik mulu bng ga keluar qr nya

**Comment by gamingrkp** [comment]
> **Question**
> What would you like to ask?
> Setelah npm start bolak balik mulu bng ga keluar qr nya

Coba update npm i open-wa/wa-automate@latest, kalo masih error delete save data Ama logs
