### ISSUE TITLE
error help

### ISSUE THREAD

**Issue by romystuas** [SlavyanDesu/BocchiBot#35]
setiap npm start lalu browser launched dan yg trjdi malah kembali ke path BocchiBot
![Screenshot_5](https://user-images.githubusercontent.com/75922906/102003508-ebe54200-3d3a-11eb-9cdb-c94259a5cdae.png)

**Comment by MrPawNO** [comment]
> setiap npm start lalu browser launched dan yg trjdi malah kembali ke path BocchiBot
> ![Screenshot_5](https://user-images.githubusercontent.com/75922906/102003508-ebe54200-3d3a-11eb-9cdb-c94259a5cdae.png)

Ini keknya karena nodejs ga ngenalin path ente
mungkin lu pernah ngubah "path" di environment variable??

Pakai windows berapa?

Cari di google: "Default path environment for windows (windows lu brp)

Abis tu set path default nodejs nya

Caranya: Buka CMD/Gitbash -> Run as Admin dan tempelkan: SET PATH=C:\Program Files\nodejs;%PATH%

Semoga bisa solved ^^

**Comment by romystuas** [comment]
> > setiap npm start lalu browser launched dan yg trjdi malah kembali ke path BocchiBot
> > ![Screenshot_5](https://user-images.githubusercontent.com/75922906/102003508-ebe54200-3d3a-11eb-9cdb-c94259a5cdae.png)
> 
> Ini keknya karena nodejs ga ngenalin path ente
> mungkin lu pernah ngubah "path" di environment variable??
> 
> Pakai windows berapa?
> 
> Cari di google: "Default path environment for windows (windows lu brp)
> 
> Abis tu set path default nodejs nya
> 
> Caranya: Buka CMD/Gitbash -> Run as Admin dan tempelkan: SET PATH=C:\Program Files\nodejs;%PATH%
> 
> Semoga bisa solved ^^

solved bg mkshhhh banyakkkkk :1st_place_medal:
