### ISSUE TITLE
Multiple device WA Beta Belum bisa

### ISSUE THREAD

**Issue by zexry619** [SlavyanDesu/BocchiBot#353]
Halo gan, Kalo pake multiple device whatsapp beta emang belum bisa ya?Apa akan ada update?Lumayan enak pake multiple device, WAnya mati Botnya bisa tetap jalan.

**Comment by SlavyanDesu** [comment]
> Halo gan, Kalo pake multiple device whatsapp beta emang belum bisa ya?Apa akan ada update?Lumayan enak pake multiple device, WAnya mati Botnya bisa tetap jalan.

hai, multiple device itu kayak gimana contohnya ya? kalau buat bot aktif terus, kamu bisa sewa RDP atau VPS lalu jalanin terminal di situ

**Comment by zexry619** [comment]
Iya gan saya pakai RDP untuk botnya. Bisa coba install whatsapp beta gan terus join yang Multiple-device Beta nya. Jadi sekarang ada fitur, HP gak konek ke internet tapi whatsapp webnya masih tetap jalan. Kira kira begitu gan.
![image](https://user-images.githubusercontent.com/25785552/127834848-16cdb532-5efe-4741-91d4-a19feccf4b53.png)

**Comment by zexry619** [comment]
![image](https://user-images.githubusercontent.com/25785552/127835042-139d93a5-728d-4886-9500-e8dbc05e814e.png)

**Comment by zexry619** [comment]
Saya sudah coba scan qrnya dan bisa login tapi Botnya gak bales pesannya cuma di read aja gan.

**Comment by zexry619** [comment]
![image](https://user-images.githubusercontent.com/25785552/127835723-b80d57d7-954e-43c6-8563-5feba15ae9e3.png)
![image](https://user-images.githubusercontent.com/25785552/127835845-9dba598b-96ad-4eb4-b179-8a9605997eff.png)

**Comment by SlavyanDesu** [comment]
wah ini keren banget sih cuman sayangnya kita hanya bisa berharap library open-whatsapp ngegarap update ini. mungkin jikalau mau, kamu bisa open issue di repository [`open-wa/wa-automate-nodejs`](https://github.com/open-wa/wa-automate-nodejs)

**Comment by gamingrkp** [comment]
> Halo gan, Kalo pake multiple device whatsapp beta emang belum bisa ya?Apa akan ada update?Lumayan enak pake multiple device, WAnya mati Botnya bisa tetap jalan.

https://docs.openwa.dev/interfaces/api_model_config.ConfigObject.html#multiDevice

**Comment by zexry619** [comment]
> https://docs.openwa.dev/interfaces/api_model_config.ConfigObject.html#multiDevice

oh gitu oke gan
