### ISSUE TITLE
REQ

### ISSUE THREAD

**Issue by romystuas** [SlavyanDesu/BocchiBot#36]
mo req jg blh kah? :+1:  vhtear api missing person

**Comment by SlavyanDesu** [comment]
> mo req jg blh kah? 👍 vhtear api missing person

noted

**Comment by SlavyanDesu** [comment]
@romystuas done https://github.com/SlavyanDesu/BocchiBot/commit/7f99963dfb020ff08cfcd1a3190c368e5b57240f

**Comment by romystuas** [comment]
> @romystuas done [7f99963](https://github.com/SlavyanDesu/BocchiBot/commit/7f99963dfb020ff08cfcd1a3190c368e5b57240f)

ahhh thanks :DDDDDD
