### ISSUE TITLE
Welcome

### ISSUE THREAD

**Issue by badriyatus123** [SlavyanDesu/BocchiBot#362]
**Question**
What would you like to ask?

Untuk welcome apakah bisa hanya mengunakan text? 

contoh:
![gambar](https://user-images.githubusercontent.com/87899416/130310442-dec39a91-67da-40fe-9b27-e22faa16dc09.png)

**Comment by gamingrkp** [comment]
> **Question**
> What would you like to ask?
> 
> Untuk welcome apakah bisa hanya mengunakan text?
> 
> contoh:
> ![gambar](https://user-images.githubusercontent.com/87899416/130310442-dec39a91-67da-40fe-9b27-e22faa16dc09.png)

Bisa Diubah Sendiri Di Bagian [https://github.com/SlavyanDesu/BocchiBot/blob/master/index.js](url)

**Comment by badriyatus123** [comment]
> 
> 
> > **Question**
> > What would you like to ask?
> > Untuk welcome apakah bisa hanya mengunakan text?
> > contoh:
> > ![gambar](https://user-images.githubusercontent.com/87899416/130310442-dec39a91-67da-40fe-9b27-e22faa16dc09.png)
> 
> Bisa Diubah Sendiri Di Bagian index.js [sini](https://github.com/SlavyanDesu/BocchiBot/blob/master/index.js)

iya mas maksud nya contoh codingan sederhana nya gitu mas soal nya saya aga kurang paham struktur dari codingan bot ini

**Comment by gamingrkp** [comment]
> > > **Question**
> > > What would you like to ask?
> > > Untuk welcome apakah bisa hanya mengunakan text?
> > > contoh:
> > > ![gambar](https://user-images.githubusercontent.com/87899416/130310442-dec39a91-67da-40fe-9b27-e22faa16dc09.png)
> > 
> > 
> > Bisa Diubah Sendiri Di Bagian index.js [sini](https://github.com/SlavyanDesu/BocchiBot/blob/master/index.js)
> 
> iya mas maksud nya contoh codingan sederhana nya gitu mas soal nya saya aga kurang paham struktur dari codingan bot ini

`if (event.action === 'add' && event.who !== botNumbers && isWelcome) {
                const pic = await bocchi.getProfilePicFromServer(event.who)
                if (pic === undefined) {
                    var picx = 'https://i.ibb.co/Tq7d7TZ/age-hananta-495-photo.png'
                } else {
                    picx = pic
                }
                await bocchi.sendText(event.chat, `Welcome ${pushname}! Di Grub ${name}`)`

**Comment by gamingrkp** [comment]
> > > **Question**
> > > What would you like to ask?
> > > Untuk welcome apakah bisa hanya mengunakan text?
> > > contoh:
> > > ![gambar](https://user-images.githubusercontent.com/87899416/130310442-dec39a91-67da-40fe-9b27-e22faa16dc09.png)
> > 
> > 
> > Bisa Diubah Sendiri Di Bagian index.js [sini](https://github.com/SlavyanDesu/BocchiBot/blob/master/index.js)
> 
> iya mas maksud nya contoh codingan sederhana nya gitu mas soal nya saya aga kurang paham struktur dari codingan bot ini

```if (event.action === 'add' && event.who !== botNumbers && isWelcome) {
                const pic = await bocchi.getProfilePicFromServer(event.who)
                if (pic === undefined) {
                    var picx = 'https://i.ibb.co/Tq7d7TZ/age-hananta-495-photo.png'
                } else {
                    picx = pic
                }
                await bocchi.sendText(event.chat, `Welcome ${pushname}! Di Grub ${name}`)```

**Comment by gamingrkp** [comment]
> > > **Question**
> > > What would you like to ask?
> > > Untuk welcome apakah bisa hanya mengunakan text?
> > > contoh:
> > > ![gambar](https://user-images.githubusercontent.com/87899416/130310442-dec39a91-67da-40fe-9b27-e22faa16dc09.png)
> > 
> > 
> > Bisa Diubah Sendiri Di Bagian index.js [sini](https://github.com/SlavyanDesu/BocchiBot/blob/master/index.js)
> 
> iya mas maksud nya contoh codingan sederhana nya gitu mas soal nya saya aga kurang paham struktur dari codingan bot ini

```if (event.action === 'add' && event.who !== botNumbers && isWelcome) {
                await bocchi.sendText(event.chat, `Welcome ${pushname}! Di Grub ${name}`)```

**Comment by badriyatus123** [comment]
Oke bang thanks work
