### ISSUE TITLE
WELCOME IN OWNER

### ISSUE THREAD

**Issue by badriyatus123** [SlavyanDesu/BocchiBot#363]
**Question**
What would you like to ask?

ini saya setting nomer saya jadi owner pada bot tapi kenapa ya pas saya coba aktifkan welcome itu tidak ada respown dari bot tetpai saya coba mengunakan nomer yang bukan owner grup itu bisa mengunakan fitur welcome dan bot respown 

untuk fitur lain belum saya coba baru welcome aja
Terimakasih.

![gambar](https://user-images.githubusercontent.com/87899416/130351781-3e7b3480-520d-4773-b8fc-2f779925984a.png)

**Comment by gamingrkp** [comment]
> **Question**
> What would you like to ask?
> 
> ini saya setting nomer saya jadi owner pada bot tapi kenapa ya pas saya coba aktifkan welcome itu tidak ada respown dari bot tetpai saya coba mengunakan nomer yang bukan owner grup itu bisa mengunakan fitur welcome dan bot respown
> 
> untuk fitur lain belum saya coba baru welcome aja
> Terimakasih.
> 
> ![gambar](https://user-images.githubusercontent.com/87899416/130351781-3e7b3480-520d-4773-b8fc-2f779925984a.png)

ini owner pada bot atau owner pada grup

**Comment by badriyatus123** [comment]
> 
> 
> > **Question**
> > What would you like to ask?
> > ini saya setting nomer saya jadi owner pada bot tapi kenapa ya pas saya coba aktifkan welcome itu tidak ada respown dari bot tetpai saya coba mengunakan nomer yang bukan owner grup itu bisa mengunakan fitur welcome dan bot respown
> > untuk fitur lain belum saya coba baru welcome aja
> > Terimakasih.
> > ![gambar](https://user-images.githubusercontent.com/87899416/130351781-3e7b3480-520d-4773-b8fc-2f779925984a.png)
> 
> ini owner pada bot atau owner pada grup

udah work mas ga tau kenapa dah di restar bisa lagi

ada masalah lagi #sgif kadang bisa kadang ngga mas kenapa ya

FOTO:
![gambar](https://user-images.githubusercontent.com/87899416/130354568-73d8466f-5dd2-4b09-9ea5-e897ccab45ea.png)

LOG:
![gambar](https://user-images.githubusercontent.com/87899416/130354574-9af30a89-63a3-4d9d-a099-d5a6afa10e86.png)

**Comment by badriyatus123** [comment]
kebetulan text respon nya saya ganti

**Comment by gamingrkp** [comment]
> > > **Question**
> > > What would you like to ask?
> > > ini saya setting nomer saya jadi owner pada bot tapi kenapa ya pas saya coba aktifkan welcome itu tidak ada respown dari bot tetpai saya coba mengunakan nomer yang bukan owner grup itu bisa mengunakan fitur welcome dan bot respown
> > > untuk fitur lain belum saya coba baru welcome aja
> > > Terimakasih.
> > > ![gambar](https://user-images.githubusercontent.com/87899416/130351781-3e7b3480-520d-4773-b8fc-2f779925984a.png)
> > 
> > 
> > ini owner pada bot atau owner pada grup
> 
> udah work mas ga tau kenapa dah di restar bisa lagi
> 
> ada masalah lagi #sgif kadang bisa kadang ngga mas kenapa ya
> 
> FOTO:
> ![gambar](https://user-images.githubusercontent.com/87899416/130354568-73d8466f-5dd2-4b09-9ea5-e897ccab45ea.png)
> 
> LOG:
> ![gambar](https://user-images.githubusercontent.com/87899416/130354574-9af30a89-63a3-4d9d-a099-d5a6afa10e86.png)

Sgif Harus Caption Untuk Sekarang Nanti Saya Contrib Lagi aja

**Comment by gamingrkp** [comment]
udah semua kan ?

**Comment by badriyatus123** [comment]
tapi di 

> 
> 
> > > > **Question**
> > > > What would you like to ask?
> > > > ini saya setting nomer saya jadi owner pada bot tapi kenapa ya pas saya coba aktifkan welcome itu tidak ada respown dari bot tetpai saya coba mengunakan nomer yang bukan owner grup itu bisa mengunakan fitur welcome dan bot respown
> > > > untuk fitur lain belum saya coba baru welcome aja
> > > > Terimakasih.
> > > > ![gambar](https://user-images.githubusercontent.com/87899416/130351781-3e7b3480-520d-4773-b8fc-2f779925984a.png)
> > > 
> > > 
> > > ini owner pada bot atau owner pada grup
> > 
> > 
> > udah work mas ga tau kenapa dah di restar bisa lagi
> > ada masalah lagi #sgif kadang bisa kadang ngga mas kenapa ya
> > FOTO:
> > ![gambar](https://user-images.githubusercontent.com/87899416/130354568-73d8466f-5dd2-4b09-9ea5-e897ccab45ea.png)
> > LOG:
> > ![gambar](https://user-images.githubusercontent.com/87899416/130354574-9af30a89-63a3-4d9d-a099-d5a6afa10e86.png)
> 
> Sgif Harus Caption Untuk Sekarang

owh oke oke bang berarti ga ada fix nya ya biar kalo ga di caption dia bakalan muncul notif contoh "video harus di caption #sgif  agar dapat di proses"

**Comment by gamingrkp** [comment]
> tapi di
> 
> > > > > **Question**
> > > > > What would you like to ask?
> > > > > ini saya setting nomer saya jadi owner pada bot tapi kenapa ya pas saya coba aktifkan welcome itu tidak ada respown dari bot tetpai saya coba mengunakan nomer yang bukan owner grup itu bisa mengunakan fitur welcome dan bot respown
> > > > > untuk fitur lain belum saya coba baru welcome aja
> > > > > Terimakasih.
> > > > > ![gambar](https://user-images.githubusercontent.com/87899416/130351781-3e7b3480-520d-4773-b8fc-2f779925984a.png)
> > > > 
> > > > 
> > > > ini owner pada bot atau owner pada grup
> > > 
> > > 
> > > udah work mas ga tau kenapa dah di restar bisa lagi
> > > ada masalah lagi #sgif kadang bisa kadang ngga mas kenapa ya
> > > FOTO:
> > > ![gambar](https://user-images.githubusercontent.com/87899416/130354568-73d8466f-5dd2-4b09-9ea5-e897ccab45ea.png)
> > > LOG:
> > > ![gambar](https://user-images.githubusercontent.com/87899416/130354574-9af30a89-63a3-4d9d-a099-d5a6afa10e86.png)
> > 
> > 
> > Sgif Harus Caption Untuk Sekarang
> 
> owh oke oke bang berarti ga ada fix nya ya biar kalo ga di caption dia bakalan muncul notif contoh "video harus di caption #sgif agar dapat di proses"

next update udh dibenerin

**Comment by badriyatus123** [comment]
> 
> 
> > tapi di
> > > > > > **Question**
> > > > > > What would you like to ask?
> > > > > > ini saya setting nomer saya jadi owner pada bot tapi kenapa ya pas saya coba aktifkan welcome itu tidak ada respown dari bot tetpai saya coba mengunakan nomer yang bukan owner grup itu bisa mengunakan fitur welcome dan bot respown
> > > > > > untuk fitur lain belum saya coba baru welcome aja
> > > > > > Terimakasih.
> > > > > > ![gambar](https://user-images.githubusercontent.com/87899416/130351781-3e7b3480-520d-4773-b8fc-2f779925984a.png)
> > > > > 
> > > > > 
> > > > > ini owner pada bot atau owner pada grup
> > > > 
> > > > 
> > > > udah work mas ga tau kenapa dah di restar bisa lagi
> > > > ada masalah lagi #sgif kadang bisa kadang ngga mas kenapa ya
> > > > FOTO:
> > > > ![gambar](https://user-images.githubusercontent.com/87899416/130354568-73d8466f-5dd2-4b09-9ea5-e897ccab45ea.png)
> > > > LOG:
> > > > ![gambar](https://user-images.githubusercontent.com/87899416/130354574-9af30a89-63a3-4d9d-a099-d5a6afa10e86.png)
> > > 
> > > 
> > > Sgif Harus Caption Untuk Sekarang
> > 
> > 
> > owh oke oke bang berarti ga ada fix nya ya biar kalo ga di caption dia bakalan muncul notif contoh "video harus di caption #sgif agar dapat di proses"
> 
> next update udh dibenerin

thanks mas
