### ISSUE TITLE
req

### ISSUE THREAD

**Issue by romystuas** [SlavyanDesu/BocchiBot#37]
valentine vhtear jg bang maap ngerepotin :v
foto pertama ngmbl foto profil sender :V

**Comment by romystuas** [comment]
> valentine vhtear jg bang maap ngerepotin :v

foto pertama ngml foto profil sender :V

**Comment by SlavyanDesu** [comment]
> foto pertama ngmbl foto profil sender :V

ini maksudnya gimana?

**Comment by romystuas** [comment]
> > foto pertama ngmbl foto profil sender :V
> 
> ini maksudnya gimana?

kn t1= url1 , t2 = url2

kalau t2 = foto yg diupload sender
t1 = profile sender

**Comment by romystuas** [comment]
jdi kalau sender up foto dengan caption #valentine = t2

untuk t1 ngambil dari profile dia :D

**Comment by romystuas** [comment]
maap klau penjelasan nya ribet @SlavyanDesu

**Comment by SlavyanDesu** [comment]
> maap klau penjelasan nya ribet @SlavyanDesu

wkwkwk, gapapa ntar saya bikinin

**Comment by romystuas** [comment]
> > maap klau penjelasan nya ribet @SlavyanDesu
> 
> wkwkwk, gapapa ntar saya bikinin

rendah hati sekale, tetaplah rendah hati wkwkwk

**Comment by SlavyanDesu** [comment]
@romystuas done https://github.com/SlavyanDesu/BocchiBot/commit/6399d68fee114e25028cdd7d7e14fc7e504410be

**Comment by romystuas** [comment]
> jdi kalau sender up foto dengan caption #valentine = t2
> 
> untuk t1 ngambil dari profile dia :D

tq <3
