### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by danielraffiando** [SlavyanDesu/BocchiBot#375]
**Question**
What would you like to ask?

**Solusinya bang, ini abis ** `npm start` muncul notice ini

> PS C:\Users\Administrator\BocchiBot> npm start
> bocchibot@1.0.0 start
> node index.js

> C:\Users\Administrator\BocchiBot\message\index.js:31
> const fetch = require('node-fetch')
>               ^
> 
> Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\Administrator\BocchiBot\node_modules\node-fetch\src\index.js fr
> om C:\Users\Administrator\BocchiBot\message\index.js not supported.
> Instead change the require of C:\Users\Administrator\BocchiBot\node_modules\node-fetch\src\index.js in C:\Users\Administ
> rator\BocchiBot\message\index.js to a dynamic import() which is available in all CommonJS modules.
>    at Object.<anonymous> (C:\Users\Administrator\BocchiBot\message\index.js:31:15)
>     at Object.<anonymous> (C:\Users\Administrator\BocchiBot\index.js:7:20) {
>   code: 'ERR_REQUIRE_ESM'
> }

**Comment by danielraffiando** [comment]
Solved, tambahin `"type": "module",` di package.json, dibawah ` "main": "index.js",`

**Comment by powermx** [comment]
Any ideas to solve this error ?

**Comment by gamingrkp** [comment]
> Any ideas to solve this error ?

Already fix see readme
