### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by romystuas** [SlavyanDesu/BocchiBot#38]
sudah di reply foto, di upload dengan caption jg sudah

tetapi ada pesan error di terminal: "ERROR MISSING URL"

**Comment by SlavyanDesu** [comment]
![Screenshot_20201213-221811](https://user-images.githubusercontent.com/28254882/102015987-342f4f00-3d91-11eb-89b6-d200ba78e347.jpg)
?

**Comment by SlavyanDesu** [comment]
Coba di

**Comment by SlavyanDesu** [comment]
Coba di private chat

**Comment by SlavyanDesu** [comment]
Soalnya keknya kita harus kesimpen dulu datanya mungkin (?)

**Comment by romystuas** [comment]
> Mungkin nomor kita harus ke-record sama botnya (?)

![Screenshot_6](https://user-images.githubusercontent.com/75922906/102016118-dcddae80-3d91-11eb-9f7b-e25f34d828a3.png)
tetap aja bg

**Comment by romystuas** [comment]
> Mungkin nomor kita harus ke-record sama botnya (?)

error wktu ngmbl profile kita kh??

pakai ini g bs bang?
var pic = await bocchi.getProfilePicFromServer(sender.id)
 if (pic == undefined) {
                    var pfp = errorurl 
                } else {
                    var pfp = pic
                }

**Comment by SlavyanDesu** [comment]
> > Mungkin nomor kita harus ke-record sama botnya (?)
> 
> error wktu ngmbl profile kita kh??
> 
> pakai ini g bs bang?
> var pic = await bocchi.getProfilePicFromServer(sender.id)
> if (pic == undefined) {
> var pfp = errorurl
> } else {
> var pfp = pic
> }

wait

**Comment by SlavyanDesu** [comment]
> > Mungkin nomor kita harus ke-record sama botnya (?)
> 
> error wktu ngmbl profile kita kh??
> 
> pakai ini g bs bang?
> var pic = await bocchi.getProfilePicFromServer(sender.id)
> if (pic == undefined) {
> var pfp = errorurl
> } else {
> var pfp = pic
> }

ok sip, pake method itu juga bisa. tinggal nyari bentuk datanya base64 string atau buffer, bakal fix secepatnya~

**Comment by MrPawNO** [comment]
> > > Mungkin nomor kita harus ke-record sama botnya (?)
> > 
> > 
> > error wktu ngmbl profile kita kh??
> > pakai ini g bs bang?
> > var pic = await bocchi.getProfilePicFromServer(sender.id)
> > if (pic == undefined) {
> > var pfp = errorurl
> > } else {
> > var pfp = pic
> > }
> 
> ok sip, pake method itu juga bisa. tinggal nyari bentuk datanya base64 string atau buffer, bakal fix secepatnya~

Itu juga bisa kubuat jadi profile info, mau tak pull ngab?

**Comment by SlavyanDesu** [comment]
> > > > Mungkin nomor kita harus ke-record sama botnya (?)
> > > 
> > > 
> > > error wktu ngmbl profile kita kh??
> > > pakai ini g bs bang?
> > > var pic = await bocchi.getProfilePicFromServer(sender.id)
> > > if (pic == undefined) {
> > > var pfp = errorurl
> > > } else {
> > > var pfp = pic
> > > }
> > 
> > 
> > ok sip, pake method itu juga bisa. tinggal nyari bentuk datanya base64 string atau buffer, bakal fix secepatnya~
> 
> Itu juga bisa kubuat jadi profile info, mau tak pull ngab?

gasken

**Comment by romystuas** [comment]
> > > Mungkin nomor kita harus ke-record sama botnya (?)
> > 
> > 
> > error wktu ngmbl profile kita kh??
> > pakai ini g bs bang?
> > var pic = await bocchi.getProfilePicFromServer(sender.id)
> > if (pic == undefined) {
> > var pfp = errorurl
> > } else {
> > var pfp = pic
> > }
> 
> ok sip, pake method itu juga bisa. tinggal nyari bentuk datanya base64 string atau buffer, bakal fix secepatnya~

d tunggu yak :D

**Comment by SlavyanDesu** [comment]
yap, sedang nyari cara ini buat ngambil data foto profilnya. soalnya api vhtear entah kenapa nggak nerima foto dari link whatsapp, udah nyoba make bent juga malah hasilnya object hadeh wkwk

**Comment by romystuas** [comment]
> yap, sedang nyari cara ini buat ngambil data foto profilnya. soalnya api vhtear entah kenapa nggak nerima foto dari link whatsapp, udah nyoba make bent juga malah hasilnya object hadeh wkwk

![Screenshot_8](https://user-images.githubusercontent.com/75922906/102019539-ac543f80-3da6-11eb-9821-a7f25da35b9f.png)

wkwk gmn yha cuma bisa kasih smngat

**Comment by SlavyanDesu** [comment]
> > yap, sedang nyari cara ini buat ngambil data foto profilnya. soalnya api vhtear entah kenapa nggak nerima foto dari link whatsapp, udah nyoba make bent juga malah hasilnya object hadeh wkwk
> 
> ![Screenshot_8](https://user-images.githubusercontent.com/75922906/102019539-ac543f80-3da6-11eb-9821-a7f25da35b9f.png)
> 
> wkwk gmn yha cuma bisa kasih smngat

nah iya, itu si vhtear malah ngasih error code 204 wkwk

**Comment by SlavyanDesu** [comment]
@romystuas dicoba https://github.com/SlavyanDesu/BocchiBot/commit/30da13e3dc5064f440b407eaaaa8f0b3cb17bf89

**Comment by SlavyanDesu** [comment]
jangan lupa buat
```bash
> npm install
> npm update
```
soalnya tadi saya nambah module biar foto dari link whatsapp jadi buffer
