### ISSUE TITLE
BocchiBot dependecies problem

### ISSUE THREAD

**Issue by GodMaker-boop** [SlavyanDesu/BocchiBot#385]
**Question**
What would you like to ask?
I've been having this problem with my bocchibot
```
axios  <=0.21.1
Severity: high
Incorrect Comparison in axios - https://github.com/advisories/GHSA-cph5-m8f7-6c5x
Server-Side Request Forgery in Axios - https://github.com/advisories/GHSA-4w2v-q235-vp99
fix available via `npm audit fix --force`
Will install @open-wa/wa-automate@4.23.6, which is a breaking change
node_modules/@open-wa/wa-automate/node_modules/axios
node_modules/@open-wa/wa-decrypt/node_modules/axios
  @open-wa/wa-automate  <=3.1.0
  Depends on vulnerable versions of @open-wa/wa-decrypt
  Depends on vulnerable versions of axios
  node_modules/@open-wa/wa-automate
  @open-wa/wa-decrypt  1.1.1 - 2.0.1
  Depends on vulnerable versions of axios
  node_modules/@open-wa/wa-decrypt

6 vulnerabilities (3 moderate, 3 high)
```

**Comment by gamingrkp** [comment]
> **Question** What would you like to ask? I've been having this problem with my bocchibot
> 
> ```
> axios  <=0.21.1
> Severity: high
> Incorrect Comparison in axios - https://github.com/advisories/GHSA-cph5-m8f7-6c5x
> Server-Side Request Forgery in Axios - https://github.com/advisories/GHSA-4w2v-q235-vp99
> fix available via `npm audit fix --force`
> Will install @open-wa/wa-automate@4.23.6, which is a breaking change
> node_modules/@open-wa/wa-automate/node_modules/axios
> node_modules/@open-wa/wa-decrypt/node_modules/axios
>   @open-wa/wa-automate  <=3.1.0
>   Depends on vulnerable versions of @open-wa/wa-decrypt
>   Depends on vulnerable versions of axios
>   node_modules/@open-wa/wa-automate
>   @open-wa/wa-decrypt  1.1.1 - 2.0.1
>   Depends on vulnerable versions of axios
>   node_modules/@open-wa/wa-decrypt
> 
> 6 vulnerabilities (3 moderate, 3 high)
> ```

npm install axios@latest?? i cant find your error xd i reinstall bocchi and same like normal

**Comment by GodMaker-boop** [comment]
> > **Question** What would you like to ask? I've been having this problem with my bocchibot
> > ```
> > axios  <=0.21.1
> > Severity: high
> > Incorrect Comparison in axios - https://github.com/advisories/GHSA-cph5-m8f7-6c5x
> > Server-Side Request Forgery in Axios - https://github.com/advisories/GHSA-4w2v-q235-vp99
> > fix available via `npm audit fix --force`
> > Will install @open-wa/wa-automate@4.23.6, which is a breaking change
> > node_modules/@open-wa/wa-automate/node_modules/axios
> > node_modules/@open-wa/wa-decrypt/node_modules/axios
> >   @open-wa/wa-automate  <=3.1.0
> >   Depends on vulnerable versions of @open-wa/wa-decrypt
> >   Depends on vulnerable versions of axios
> >   node_modules/@open-wa/wa-automate
> >   @open-wa/wa-decrypt  1.1.1 - 2.0.1
> >   Depends on vulnerable versions of axios
> >   node_modules/@open-wa/wa-decrypt
> > 
> > 6 vulnerabilities (3 moderate, 3 high)
> > ```
> 
> npm install axios@latest?? i cant find your error xd i reinstall bocchi and same like normal

the problem is, when i'm trying to install the dependecies it says this:
```
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

```

**Comment by gamingrkp** [comment]
> > > **Question** What would you like to ask? I've been having this problem with my bocchibot
> > > ```
> > > axios  <=0.21.1
> > > Severity: high
> > > Incorrect Comparison in axios - https://github.com/advisories/GHSA-cph5-m8f7-6c5x
> > > Server-Side Request Forgery in Axios - https://github.com/advisories/GHSA-4w2v-q235-vp99
> > > fix available via `npm audit fix --force`
> > > Will install @open-wa/wa-automate@4.23.6, which is a breaking change
> > > node_modules/@open-wa/wa-automate/node_modules/axios
> > > node_modules/@open-wa/wa-decrypt/node_modules/axios
> > >   @open-wa/wa-automate  <=3.1.0
> > >   Depends on vulnerable versions of @open-wa/wa-decrypt
> > >   Depends on vulnerable versions of axios
> > >   node_modules/@open-wa/wa-automate
> > >   @open-wa/wa-decrypt  1.1.1 - 2.0.1
> > >   Depends on vulnerable versions of axios
> > >   node_modules/@open-wa/wa-decrypt
> > > 
> > > 6 vulnerabilities (3 moderate, 3 high)
> > > ```
> > 
> > 
> > npm install axios@latest?? i cant find your error xd i reinstall bocchi and same like normal
> 
> the problem is, when i'm trying to install the dependecies it says this:
> 
> ```
> npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> ```

its okay ur bot will be fine

**Comment by GodMaker-boop** [comment]
> > > > **Question** What would you like to ask? I've been having this problem with my bocchibot
> > > > ```
> > > > axios  <=0.21.1
> > > > Severity: high
> > > > Incorrect Comparison in axios - https://github.com/advisories/GHSA-cph5-m8f7-6c5x
> > > > Server-Side Request Forgery in Axios - https://github.com/advisories/GHSA-4w2v-q235-vp99
> > > > fix available via `npm audit fix --force`
> > > > Will install @open-wa/wa-automate@4.23.6, which is a breaking change
> > > > node_modules/@open-wa/wa-automate/node_modules/axios
> > > > node_modules/@open-wa/wa-decrypt/node_modules/axios
> > > >   @open-wa/wa-automate  <=3.1.0
> > > >   Depends on vulnerable versions of @open-wa/wa-decrypt
> > > >   Depends on vulnerable versions of axios
> > > >   node_modules/@open-wa/wa-automate
> > > >   @open-wa/wa-decrypt  1.1.1 - 2.0.1
> > > >   Depends on vulnerable versions of axios
> > > >   node_modules/@open-wa/wa-decrypt
> > > > 
> > > > 6 vulnerabilities (3 moderate, 3 high)
> > > > ```
> > > 
> > > 
> > > npm install axios@latest?? i cant find your error xd i reinstall bocchi and same like normal
> > 
> > 
> > the problem is, when i'm trying to install the dependecies it says this:
> > ```
> > npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
> > npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> > npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> > npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> > npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> > npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> > ```
> 
> its okay ur bot will be fine

i'll be testing it and checking if it's all good thanks for this great bot btw!

**Comment by GodMaker-boop** [comment]
hey, why are some commands sending Error!

**Comment by gamingrkp** [comment]
> hey, why are some commands sending Error!

what commands?

**Comment by ov3rsp1der** [comment]
I managed to install and start in Ubuntu, after logging in the device the last message is localhost is running, where can I see the commands? what else am I missing? Thanks

**Comment by gamingrkp** [comment]
> I managed to install and start in Ubuntu, after logging in the device the last message is localhost is running, where can I see the commands? what else am I missing? Thanks

Thats not command... Just make localhost for heroku user...

**Comment by ov3rsp1der** [comment]
> > I managed to install and start in Ubuntu, after logging in the device the last message is localhost is running, where can I see the commands? what else am I missing? Thanks
> 
> Thats not command... Just make localhost for heroku user...

Thanks for answering, what I was referring to was how to interact with the bot from whatsapp (I already found out, sorry I'm new to bots) what I was trying to find now is the way for the bot not to crop the images when make stickers, but in the code I am not finding that line, I am suspecting that it has to do with the api

**Comment by gamingrkp** [comment]
> > > I managed to install and start in Ubuntu, after logging in the device the last message is localhost is running, where can I see the commands? what else am I missing? Thanks
> > 
> > 
> > Thats not command... Just make localhost for heroku user...
> 
> Thanks for answering, what I was referring to was how to interact with the bot from whatsapp (I already found out, sorry I'm new to bots) what I was trying to find now is the way for the bot not to crop the images when make stickers, but in the code I am not finding that line, I am suspecting that it has to do with the api

try stikerp command

**Comment by debaji-db** [comment]
> > > > I managed to install and start in Ubuntu, after logging in the device the last message is localhost is running, where can I see the commands? what else am I missing? Thanks
> > > 
> > > 
> > > Thats not command... Just make localhost for heroku user...
> > 
> > 
> > Thanks for answering, what I was referring to was how to interact with the bot from whatsapp (I already found out, sorry I'm new to bots) what I was trying to find now is the way for the bot not to crop the images when make stickers, but in the code I am not finding that line, I am suspecting that it has to do with the api
> 
> try stikerp command

I am having one issue ,plse fix it if possible
