### ISSUE TITLE
Node Fetch and chalk error

### ISSUE THREAD

**Issue by iamherok** [SlavyanDesu/BocchiBot#398]
I think they stopped there support for require()(node fetch and chalk)
And can u use npm packages coz some APIs r not working
(Can I get your wa group link)

**Comment by Urbaexyz** [comment]
> I think they stopped there support for require()(node fetch and chalk) And can u use npm packages coz some APIs r not working (Can I get your wa group link)

```npm i --save node-fetch@3.1.0```

**Comment by Urbaexyz** [comment]
> I think they stopped there support for require()(node fetch and chalk) And can u use npm packages coz some APIs r not working (Can I get your wa group link)

```npm i --save node-fetch@2.6.6```

**Comment by Urbaexyz** [comment]
but when you type ```npm start```
it will show bug lol, my repo have same problem too

**Comment by iamherok** [comment]
> > I think they stopped there support for require()(node fetch and chalk) And can u use npm packages coz some APIs r not working (Can I get your wa group link)
> 
> `npm i --save node-fetch@2.6.6`

Thnx

**Comment by gamingrkp** [comment]
> I think they stopped there support for require()(node fetch and chalk) And can u use npm packages coz some APIs r not working (Can I get your wa group link)

fixed
