### ISSUE TITLE
Changing Command Detection Method

### ISSUE THREAD

**Issue by rafaelmoris-hash** [SlavyanDesu/BocchiBot#40]
```
let antilink = JSON.parse(fs.readFileSync('./database/antilink.json'))

//PROTECT
        const isDetectorLink = antilink.includes(chatId)
        // END HELPER FUNCTION
        if (isGroupMsg && !isGroupAdmins){
            if (chats.match(/(https:\/\/chat.whatsapp.com)/gi)) {
                const check = await bocchi.inviteInfo(chats);
                if (!check) {
                    return
                } else {
                    bocchi.reply(from, `*「 GROUP LINK DETECTOR 」*\nKamu mengirimkan link grup chat, maaf kamu di kick dari grup :(`, id).then(() => {
                        bocchi.removeParticipant(groupId, sender.id)
                    })
                }
            }
        }

case 'antilink':
                if (!isGroupMsg) return bocchi.reply(from, `Perintah ini hanya bisa di gunakan dalam group!`, id)
                if (!isGroupAdmins) return bocchi.reply(from, `Perintah ini hanya bisa di gunakan oleh Admin group!`, id)
                if (!isBotGroupAdmins) return bocchi.reply(from, `Perintah ini hanya bisa di gunakan jika Bot menjadi Admin!`, id)
                if (args[0] == 'on') {
                    var cek = antilink.includes(chatId);
                    if(cek){
                        return bocchi.reply(from, `*「 ANTI GROUP LINK 」*\nPerhatian Untuk Member Grup ${name} Tercinta\nJika Ingin Send Link Harap Izin Ke Admin`, id)
                    } else {
                        antilink.push(chatId)
                        fs.writeFileSync('./database/antilink.json', JSON.stringify(antilink))
                        bocchi.reply(from, `*「 ANTI GROUP LINK 」*\nPerhatian Untuk Member Grup ${name} Tercinta\nJika Ingin Send Link Harap Izin Ke Admin`, id)
                    }
                } else if (args[0] == 'off') {
                    var cek = antilink.includes(chatId);
                    if(!cek){
                        return bocchi.reply(from, `*「 ANTI GROUP LINK 」*\nPerhatian Untuk Member Grup ${name} Tercinta\nJika Ingin Send Link Harap Izin Ke Admin`, id)
                    } else {
                        let nixx = antilink.indexOf(chatId)
                        antilink.splice(nixx, 1)
                        fs.writeFileSync('./database/antilink.json', JSON.stringify(antilink))
                        bocchi.reply(from, `*「 ANTI GROUP LINK 」*\nPerhatian Untuk Member Grup ${name} Tercinta\nJika Ingin Send Link Harap Izin Ke Admin`, id)
                    }
                } else {
                    bocchi.reply(from, `Pilih enable atau disable udin!`, id)
                } 
                break
```

pas ngetes ngirim linkgrup bot nya ndak ada respon sama sekali

**Comment by SlavyanDesu** [comment]
> ```
> let antilink = JSON.parse(fs.readFileSync('./database/antilink.json'))
> 
> //PROTECT
>         const isDetectorLink = antilink.includes(chatId)
>         // END HELPER FUNCTION
>         if (isGroupMsg && !isGroupAdmins){
>             if (chats.match(/(https:\/\/chat.whatsapp.com)/gi)) {
>                 const check = await bocchi.inviteInfo(chats);
>                 if (!check) {
>                     return
>                 } else {
>                     bocchi.reply(from, `*「 GROUP LINK DETECTOR 」*\nKamu mengirimkan link grup chat, maaf kamu di kick dari grup :(`, id).then(() => {
>                         bocchi.removeParticipant(groupId, sender.id)
>                     })
>                 }
>             }
>         }
> 
> case 'antilink':
>                 if (!isGroupMsg) return bocchi.reply(from, `Perintah ini hanya bisa di gunakan dalam group!`, id)
>                 if (!isGroupAdmins) return bocchi.reply(from, `Perintah ini hanya bisa di gunakan oleh Admin group!`, id)
>                 if (!isBotGroupAdmins) return bocchi.reply(from, `Perintah ini hanya bisa di gunakan jika Bot menjadi Admin!`, id)
>                 if (args[0] == 'on') {
>                     var cek = antilink.includes(chatId);
>                     if(cek){
>                         return bocchi.reply(from, `*「 ANTI GROUP LINK 」*\nPerhatian Untuk Member Grup ${name} Tercinta\nJika Ingin Send Link Harap Izin Ke Admin`, id)
>                     } else {
>                         antilink.push(chatId)
>                         fs.writeFileSync('./database/antilink.json', JSON.stringify(antilink))
>                         bocchi.reply(from, `*「 ANTI GROUP LINK 」*\nPerhatian Untuk Member Grup ${name} Tercinta\nJika Ingin Send Link Harap Izin Ke Admin`, id)
>                     }
>                 } else if (args[0] == 'off') {
>                     var cek = antilink.includes(chatId);
>                     if(!cek){
>                         return bocchi.reply(from, `*「 ANTI GROUP LINK 」*\nPerhatian Untuk Member Grup ${name} Tercinta\nJika Ingin Send Link Harap Izin Ke Admin`, id)
>                     } else {
>                         let nixx = antilink.indexOf(chatId)
>                         antilink.splice(nixx, 1)
>                         fs.writeFileSync('./database/antilink.json', JSON.stringify(antilink))
>                         bocchi.reply(from, `*「 ANTI GROUP LINK 」*\nPerhatian Untuk Member Grup ${name} Tercinta\nJika Ingin Send Link Harap Izin Ke Admin`, id)
>                     }
>                 } else {
>                     bocchi.reply(from, `Pilih enable atau disable udin!`, id)
>                 } 
>                 break
> ```
> 
> pas ngetes ngirim linkgrup bot nya ndak ada respon sama sekali

ini anti-link dari sc siapa?
coba liat properties `chatId` nya, udah didefine belum?

**Comment by rafaelmoris-hash** [comment]
> > ```
> > let antilink = JSON.parse(fs.readFileSync('./database/antilink.json'))
> > 
> > //PROTECT
> >         const isDetectorLink = antilink.includes(chatId)
> >         // END HELPER FUNCTION
> >         if (isGroupMsg && !isGroupAdmins){
> >             if (chats.match(/(https:\/\/chat.whatsapp.com)/gi)) {
> >                 const check = await bocchi.inviteInfo(chats);
> >                 if (!check) {
> >                     return
> >                 } else {
> >                     bocchi.reply(from, `*「 GROUP LINK DETECTOR 」*\nKamu mengirimkan link grup chat, maaf kamu di kick dari grup :(`, id).then(() => {
> >                         bocchi.removeParticipant(groupId, sender.id)
> >                     })
> >                 }
> >             }
> >         }
> > 
> > case 'antilink':
> >                 if (!isGroupMsg) return bocchi.reply(from, `Perintah ini hanya bisa di gunakan dalam group!`, id)
> >                 if (!isGroupAdmins) return bocchi.reply(from, `Perintah ini hanya bisa di gunakan oleh Admin group!`, id)
> >                 if (!isBotGroupAdmins) return bocchi.reply(from, `Perintah ini hanya bisa di gunakan jika Bot menjadi Admin!`, id)
> >                 if (args[0] == 'on') {
> >                     var cek = antilink.includes(chatId);
> >                     if(cek){
> >                         return bocchi.reply(from, `*「 ANTI GROUP LINK 」*\nPerhatian Untuk Member Grup ${name} Tercinta\nJika Ingin Send Link Harap Izin Ke Admin`, id)
> >                     } else {
> >                         antilink.push(chatId)
> >                         fs.writeFileSync('./database/antilink.json', JSON.stringify(antilink))
> >                         bocchi.reply(from, `*「 ANTI GROUP LINK 」*\nPerhatian Untuk Member Grup ${name} Tercinta\nJika Ingin Send Link Harap Izin Ke Admin`, id)
> >                     }
> >                 } else if (args[0] == 'off') {
> >                     var cek = antilink.includes(chatId);
> >                     if(!cek){
> >                         return bocchi.reply(from, `*「 ANTI GROUP LINK 」*\nPerhatian Untuk Member Grup ${name} Tercinta\nJika Ingin Send Link Harap Izin Ke Admin`, id)
> >                     } else {
> >                         let nixx = antilink.indexOf(chatId)
> >                         antilink.splice(nixx, 1)
> >                         fs.writeFileSync('./database/antilink.json', JSON.stringify(antilink))
> >                         bocchi.reply(from, `*「 ANTI GROUP LINK 」*\nPerhatian Untuk Member Grup ${name} Tercinta\nJika Ingin Send Link Harap Izin Ke Admin`, id)
> >                     }
> >                 } else {
> >                     bocchi.reply(from, `Pilih enable atau disable udin!`, id)
> >                 } 
> >                 break
> > ```
> > 
> > 
> > pas ngetes ngirim linkgrup bot nya ndak ada respon sama sekali
> 
> ini anti-link dari sc siapa?
> coba liat properties `chatId` nya, udah didefine belum?

nemu bang di elaina, pas d aplikasikan di bot ini ga respon

const { type, id, from, t, sender, isGroupMsg, chat, chatId, caption, isMedia, mimetype, quotedMsg, quotedMsgObj, mentionedJidList } = message

udeh terdefine kok`

**Comment by SlavyanDesu** [comment]
coba ganti variabel `chats` ke `body`.
terus kalau bisa dan ada error, kirim aja sini

**Comment by rafaelmoris-hash** [comment]
> coba ganti variabel `chats` ke `body`.
> terus kalau bisa dan ada error, kirim aja sini

ngk error bro, ttp gada respon

**Comment by SlavyanDesu** [comment]
```js
const _antilink = JSON.parse(fs.readFileSync('./database/antilink.json'))
const isDetectorOn = _antilink.includes(chat.id)

// Anti-link detector function
if (isGroupMsg && !isGroupAdmins) {
    if (body.match(/(https:\/\/chat.whatsapp.com)/gi)) {
        const isInviteLink = await bocchi.inviteInfo(body)
        if (!isInviteLink) {
            return
        } else {
            await bocchi.reply(from, `*「 GROUP LINK DETECTOR 」*\nKamu mengirimkan link grup chat, maaf kamu di kick dari grup :(`, id)
                .then(async () => {
                    await bocchi.removeParticipant(groupId, sender.id)
                })
        }
    }
}

// Command
case 'antilink':
    if (!isGroupMsg) return await bocchi.reply(from, `Perintah ini hanya bisa di gunakan dalam group!`, id)
    if (!isGroupAdmins) return await bocchi.reply(from, `Perintah ini hanya bisa di gunakan oleh Admin group!`, id)
    if (!isBotGroupAdmins) return await bocchi.reply(from, `Perintah ini hanya bisa di gunakan jika Bot menjadi Admin!`, id)
    if (args[0] ==== 'on') {
        if (isDetectorOn) return await bocchi.reply(from, 'Anti-link sudah diaktifkan sebelumnya!', id)
        _antilink.push(chat.id)
        fs.writeFileSync('./database/antilink.json', JSON.stringify(_antilink))
        await bocchi.reply(from, `*「 ANTI GROUP LINK 」*\nPerhatian Untuk Member Grup ${name} Tercinta\nJika Ingin Send Link Harap Izin Ke Admin`, id)
    } else if (args[0] === 'off') {
        _antilink.splice(chat.id, 1)
        fs.writeFileSync('./database/antilink.json', JSON.stringify(_antilink))
        await bocchi.reply(from, `*「 ANTI GROUP LINK 」*\nPerhatian Untuk Member Grup ${name} Tercinta\nJika Ingin Send Link Harap Izin Ke Admin`, id)
    } else {
        await bocchi.reply(from, 'Masukkan parameter *on* atau *off*!', id)
    }
break
```
@rafaelmoris-hash coba

**Comment by rafaelmoris-hash** [comment]
> ```js
> const _antilink = JSON.parse(fs.readFileSync('./database/antilink.json'))
> const isDetectorOn = _antilink.includes(chat.id)
> 
> // Anti-link detector function
> if (isGroupMsg && !isGroupAdmins) {
>     if (body.match(/(https:\/\/chat.whatsapp.com)/gi)) {
>         const isInviteLink = await bocchi.inviteInfo(body)
>         if (!isInviteLink) {
>             return
>         } else {
>             await bocchi.reply(from, `*「 GROUP LINK DETECTOR 」*\nKamu mengirimkan link grup chat, maaf kamu di kick dari grup :(`, id)
>                 .then(async () => {
>                     await bocchi.removeParticipant(groupId, sender.id)
>                 })
>         }
>     }
> }
> 
> // Command
> case 'antilink':
>     if (!isGroupMsg) return await bocchi.reply(from, `Perintah ini hanya bisa di gunakan dalam group!`, id)
>     if (!isGroupAdmins) return await bocchi.reply(from, `Perintah ini hanya bisa di gunakan oleh Admin group!`, id)
>     if (!isBotGroupAdmins) return await bocchi.reply(from, `Perintah ini hanya bisa di gunakan jika Bot menjadi Admin!`, id)
>     if (args[0] === 'on') {
>         if (isDetectorOn) return await bocchi.reply(from, 'Anti-link sudah diaktifkan sebelumnya!', id)
>         _antilink.push(chat.id)
>         fs.writeFileSync('./database/antilink.json', JSON.stringify(_antilink))
>         await bocchi.reply(from, `*「 ANTI GROUP LINK 」*\nPerhatian Untuk Member Grup ${name} Tercinta\nJika Ingin Send Link Harap Izin Ke Admin`, id)
>     } else if (args[0] === 'off') {
>         _antilink.splice(chat.id, 1)
>         fs.writeFileSync('./database/antilink.json', JSON.stringify(_antilink))
>         await bocchi.reply(from, `*「 ANTI GROUP LINK 」*\nPerhatian Untuk Member Grup ${name} Tercinta\nJika Ingin Send Link Harap Izin Ke Admin`, id)
>     } else {
>         await bocchi.reply(from, 'Masukkan parameter *on* atau *off*!', id)
>     }
> break
> ```
> 
> @rafaelmoris-hash coba

![Screenshot_9](https://user-images.githubusercontent.com/75946163/102037220-37f5bc80-3df7-11eb-89d1-f6fde94396bf.png)
undefined bro

**Comment by SlavyanDesu** [comment]
> > ```js
> > const _antilink = JSON.parse(fs.readFileSync('./database/antilink.json'))
> > const isDetectorOn = _antilink.includes(chat.id)
> > 
> > // Anti-link detector function
> > if (isGroupMsg && !isGroupAdmins) {
> >     if (body.match(/(https:\/\/chat.whatsapp.com)/gi)) {
> >         const isInviteLink = await bocchi.inviteInfo(body)
> >         if (!isInviteLink) {
> >             return
> >         } else {
> >             await bocchi.reply(from, `*「 GROUP LINK DETECTOR 」*\nKamu mengirimkan link grup chat, maaf kamu di kick dari grup :(`, id)
> >                 .then(async () => {
> >                     await bocchi.removeParticipant(groupId, sender.id)
> >                 })
> >         }
> >     }
> > }
> > 
> > // Command
> > case 'antilink':
> >     if (!isGroupMsg) return await bocchi.reply(from, `Perintah ini hanya bisa di gunakan dalam group!`, id)
> >     if (!isGroupAdmins) return await bocchi.reply(from, `Perintah ini hanya bisa di gunakan oleh Admin group!`, id)
> >     if (!isBotGroupAdmins) return await bocchi.reply(from, `Perintah ini hanya bisa di gunakan jika Bot menjadi Admin!`, id)
> >     if (args[0] === 'on') {
> >         if (isDetectorOn) return await bocchi.reply(from, 'Anti-link sudah diaktifkan sebelumnya!', id)
> >         _antilink.push(chat.id)
> >         fs.writeFileSync('./database/antilink.json', JSON.stringify(_antilink))
> >         await bocchi.reply(from, `*「 ANTI GROUP LINK 」*\nPerhatian Untuk Member Grup ${name} Tercinta\nJika Ingin Send Link Harap Izin Ke Admin`, id)
> >     } else if (args[0] === 'off') {
> >         _antilink.splice(chat.id, 1)
> >         fs.writeFileSync('./database/antilink.json', JSON.stringify(_antilink))
> >         await bocchi.reply(from, `*「 ANTI GROUP LINK 」*\nPerhatian Untuk Member Grup ${name} Tercinta\nJika Ingin Send Link Harap Izin Ke Admin`, id)
> >     } else {
> >         await bocchi.reply(from, 'Masukkan parameter *on* atau *off*!', id)
> >     }
> > break
> > ```
> > 
> > 
> > @rafaelmoris-hash coba
> 
> ![Screenshot_9](https://user-images.githubusercontent.com/75946163/102037220-37f5bc80-3df7-11eb-89d1-f6fde94396bf.png)
> undefined bro

Ini pastiin ditaro setelah `chat` didefine

**Comment by SlavyanDesu** [comment]
Kalau masih gabisa, kirim sini sc nya tapi jangan sampe semuanya juga. Setidaknya yang berhubungan sama issue aja

**Comment by rafaelmoris-hash** [comment]
> ```js
> // Command
> case 'antilink':
>     if (!isGroupMsg) return await bocchi.reply(from, `Perintah ini hanya bisa di gunakan dalam group!`, id)
>     if (!isGroupAdmins) return await bocchi.reply(from, `Perintah ini hanya bisa di gunakan oleh Admin group!`, id)
>     if (!isBotGroupAdmins) return await bocchi.reply(from, `Perintah ini hanya bisa di gunakan jika Bot menjadi Admin!`, id)
>     if (args[0] === 'on') {
>         if (isDetectorOn) return await bocchi.reply(from, 'Anti-link sudah diaktifkan sebelumnya!', id)
>         _antilink.push(chat.id)
>         fs.writeFileSync('./database/antilink.json', JSON.stringify(_antilink))
>         await bocchi.reply(from, `*「 ANTI GROUP LINK 」*\nPerhatian Untuk Member Grup ${name} Tercinta\nJika Ingin Send Link Harap Izin Ke Admin`, id)
>     } else if (args[0] === 'off') {
>         _antilink.splice(chat.id, 1)
>         fs.writeFileSync('./database/antilink.json', JSON.stringify(_antilink))
>         await bocchi.reply(from, `*「 ANTI GROUP LINK 」*\nPerhatian Untuk Member Grup ${name} Tercinta\nJika Ingin Send Link Harap Izin Ke Admin`, id)
>     } else {
>         await bocchi.reply(from, 'Masukkan parameter *on* atau *off*!', id)
>     }
> break
> ```

ttp bro ndak ada respon bot

**Comment by SlavyanDesu** [comment]
Coba kirim sini sc nya

**Comment by rafaelmoris-hash** [comment]
> Coba kirim sini sc nya

sama kek yg kamu buat bro

**Comment by TobyG74** [comment]
wkwkwk asal copy sih jadi error kan

> > ```js
> > // Command
> > case 'antilink':
> >     if (!isGroupMsg) return await bocchi.reply(from, `Perintah ini hanya bisa di gunakan dalam group!`, id)
> >     if (!isGroupAdmins) return await bocchi.reply(from, `Perintah ini hanya bisa di gunakan oleh Admin group!`, id)
> >     if (!isBotGroupAdmins) return await bocchi.reply(from, `Perintah ini hanya bisa di gunakan jika Bot menjadi Admin!`, id)
> >     if (args[0] === 'on') {
> >         if (isDetectorOn) return await bocchi.reply(from, 'Anti-link sudah diaktifkan sebelumnya!', id)
> >         _antilink.push(chat.id)
> >         fs.writeFileSync('./database/antilink.json', JSON.stringify(_antilink))
> >         await bocchi.reply(from, `*「 ANTI GROUP LINK 」*\nPerhatian Untuk Member Grup ${name} Tercinta\nJika Ingin Send Link Harap Izin Ke Admin`, id)
> >     } else if (args[0] === 'off') {
> >         _antilink.splice(chat.id, 1)
> >         fs.writeFileSync('./database/antilink.json', JSON.stringify(_antilink))
> >         await bocchi.reply(from, `*「 ANTI GROUP LINK 」*\nPerhatian Untuk Member Grup ${name} Tercinta\nJika Ingin Send Link Harap Izin Ke Admin`, id)
> >     } else {
> >         await bocchi.reply(from, 'Masukkan parameter *on* atau *off*!', id)
> >     }
> > break
> > ```
> 
> ttp bro ndak ada respon bot

**Comment by rafaelmoris-hash** [comment]
> wkwkwk asal copy sih jadi error kan
> 
> > > ```js
> > > // Command
> > > case 'antilink':
> > >     if (!isGroupMsg) return await bocchi.reply(from, `Perintah ini hanya bisa di gunakan dalam group!`, id)
> > >     if (!isGroupAdmins) return await bocchi.reply(from, `Perintah ini hanya bisa di gunakan oleh Admin group!`, id)
> > >     if (!isBotGroupAdmins) return await bocchi.reply(from, `Perintah ini hanya bisa di gunakan jika Bot menjadi Admin!`, id)
> > >     if (args[0] === 'on') {
> > >         if (isDetectorOn) return await bocchi.reply(from, 'Anti-link sudah diaktifkan sebelumnya!', id)
> > >         _antilink.push(chat.id)
> > >         fs.writeFileSync('./database/antilink.json', JSON.stringify(_antilink))
> > >         await bocchi.reply(from, `*「 ANTI GROUP LINK 」*\nPerhatian Untuk Member Grup ${name} Tercinta\nJika Ingin Send Link Harap Izin Ke Admin`, id)
> > >     } else if (args[0] === 'off') {
> > >         _antilink.splice(chat.id, 1)
> > >         fs.writeFileSync('./database/antilink.json', JSON.stringify(_antilink))
> > >         await bocchi.reply(from, `*「 ANTI GROUP LINK 」*\nPerhatian Untuk Member Grup ${name} Tercinta\nJika Ingin Send Link Harap Izin Ke Admin`, id)
> > >     } else {
> > >         await bocchi.reply(from, 'Masukkan parameter *on* atau *off*!', id)
> > >     }
> > > break
> > > ```
> > 
> > 
> > ttp bro ndak ada respon bot

iy bro udh dibilang aku ngmbl dari botmu, bntu fix bro

**Comment by TobyG74** [comment]
join grup wa nya

**Comment by SlavyanDesu** [comment]
sc nya toby sama sc gw gak sama dibagian ngedeteksi command-nya, di sini lebih tepatnya:
https://github.com/SlavyanDesu/BocchiBot/blob/0ff8e864f547a1ec03a12e0d1393f7fb978ed8ab/message/index.js#L51-L55
ntar, gw ganti methodnya. untuk sekarang gw masukin ke to-do list dulu dan nikmatin aja command yang ada
@TobyG74 kalau mau bantu juga bole wkwkwk

**Comment by rafaelmoris-hash** [comment]
> sc nya toby sama sc gw gak sama dibagian ngedeteksi command-nya, di sini lebih tepatnya:
> https://github.com/SlavyanDesu/BocchiBot/blob/0ff8e864f547a1ec03a12e0d1393f7fb978ed8ab/message/index.js#L51-L55
> 
> 
> ntar, gw ganti methodnya. untuk sekarang gw masukin ke to-do list dulu dan nikmatin aja command yang ada
> @TobyG74 kalau mau bantu juga bole wkwkwk

oke bg tq

**Comment by rafaelmoris-hash** [comment]
> sc nya toby sama sc gw gak sama dibagian ngedeteksi command-nya, di sini lebih tepatnya:
> https://github.com/SlavyanDesu/BocchiBot/blob/0ff8e864f547a1ec03a12e0d1393f7fb978ed8ab/message/index.js#L51-L55
> 
> 
> ntar, gw ganti methodnya. untuk sekarang gw masukin ke to-do list dulu dan nikmatin aja command yang ada
> @TobyG74 kalau mau bantu juga bole wkwkwk

udh bro?? :v

**Comment by SlavyanDesu** [comment]
> > sc nya toby sama sc gw gak sama dibagian ngedeteksi command-nya, di sini lebih tepatnya:
> > https://github.com/SlavyanDesu/BocchiBot/blob/0ff8e864f547a1ec03a12e0d1393f7fb978ed8ab/message/index.js#L51-L55
> > 
> > ntar, gw ganti methodnya. untuk sekarang gw masukin ke to-do list dulu dan nikmatin aja command yang ada
> > @TobyG74 kalau mau bantu juga bole wkwkwk
> 
> udh bro?? :v

Belom lah

**Comment by SlavyanDesu** [comment]
@rafaelmoris-hash dicoba https://github.com/SlavyanDesu/BocchiBot/commit/46cae2ed75654f75030f526d451256a309e02d80

**Comment by SlavyanDesu** [comment]
jangan lupa close issue kalau gak ada masalah lagi ya

**Comment by rafaelmoris-hash** [comment]
> jangan lupa close issue kalau gak ada masalah lagi ya



> jangan lupa close issue kalau gak ada masalah lagi ya

![IMG_20201215_123319](https://user-images.githubusercontent.com/75946163/102175261-c5a5da80-3ed1-11eb-907d-1ec140400f00.jpg)
Yg share link bkn admin dan jg bkn ownerbot ttp gd respon bg

**Comment by SlavyanDesu** [comment]
> > jangan lupa close issue kalau gak ada masalah lagi ya
> 
> > jangan lupa close issue kalau gak ada masalah lagi ya
> 
> ![IMG_20201215_123319](https://user-images.githubusercontent.com/75946163/102175261-c5a5da80-3ed1-11eb-907d-1ec140400f00.jpg)
> Yg share link bkn admin dan jg bkn ownerbot ttp gd respon bg

Botnya udah jadi admin?

**Comment by SlavyanDesu** [comment]
Di gw work

**Comment by rafaelmoris-hash** [comment]
> Di gw work

bot admin

semua cara udh ku ikuti bro
kecuali ini:
![Screenshot_1](https://user-images.githubusercontent.com/75946163/102176462-07d01b80-3ed4-11eb-9e80-4bd7b9419a58.png)

**Comment by SlavyanDesu** [comment]
> > Di gw work
> 
> bot admin
> 
> semua cara udh ku ikuti bro
> kecuali ini:
> ![Screenshot_1](https://user-images.githubusercontent.com/75946163/102176462-07d01b80-3ed4-11eb-9e80-4bd7b9419a58.png)

coba join grup sini buat test [sini](https://chat.whatsapp.com/GIIFTUGFcxuLL50meUraq1)

**Comment by rafaelmoris-hash** [comment]
> > > Di gw work
> > 
> > 
> > bot admin
> > semua cara udh ku ikuti bro
> > kecuali ini:
> > ![Screenshot_1](https://user-images.githubusercontent.com/75946163/102176462-07d01b80-3ed4-11eb-9e80-4bd7b9419a58.png)
> 
> coba join grup [sini](https://chat.whatsapp.com/GIIFTUGFcxuLL50meUraq1) buat test

Ok bg sudah ku git pull origin master, work, mksh banyak

**Comment by SlavyanDesu** [comment]
@rafaelmoris-hash harap update ke sc terbaru, soalnya yang awal tadi ada kesalahan
