### ISSUE TITLE
I want to see how it looks 

### ISSUE THREAD

**Issue by Cyberkingcr7** [SlavyanDesu/BocchiBot#401]
Hi @SlavyanDesu can you please share the group link I would like to see how the bot looks like... And I couldn't deploy it due to something I couldn't understand.

**Comment by Cyberkingcr7** [comment]
Indeed

**Comment by gamingrkp** [comment]
> Hi @SlavyanDesu can you please share the group link I would like to see how the bot looks like... And I couldn't deploy it due to something I couldn't understand.

what you not understand ?
