### ISSUE TITLE
valentine error

### ISSUE THREAD

**Issue by romystuas** [SlavyanDesu/BocchiBot#41]
![Screenshot_10](https://user-images.githubusercontent.com/75922906/102039491-89547a80-3dfc-11eb-94c3-2384e33c1298.png)
lngsng crash wkwk asli ngakak aku bg

**Comment by SlavyanDesu** [comment]
> ![Screenshot_10](https://user-images.githubusercontent.com/75922906/102039491-89547a80-3dfc-11eb-94c3-2384e33c1298.png)
> lngsng crash wkwk asli ngakak aku bg

Hadeh geming

**Comment by SlavyanDesu** [comment]
Direstart aja dulu sc nya, sebelumya gw kek gitu. Keknya function `uploadImages()` gak kuat dipake lebih dari 1x mungkin

**Comment by SlavyanDesu** [comment]
Gw sebelumnya dapet error kek gitu juga

**Comment by romystuas** [comment]
> Direstart aja dulu sc nya, sebelumya gw kek gitu. Keknya function `uploadImages()` gak kuat dipake lebih dari 1x mungkin

Di restart gimana bg, sudah ku CTRL C + npm start lagi 3x

**Comment by SlavyanDesu** [comment]
@MrPawNO mang, coba dites command valentine. Di gw work

**Comment by SlavyanDesu** [comment]
> > Direstart aja dulu sc nya, sebelumya gw kek gitu. Keknya function `uploadImages()` gak kuat dipake lebih dari 1x mungkin
> 
> Di restart gimana bg, sudah ku CTRL C + npm start lagi 3x

Jir, dah seneng seneng kirain solved eh ternyata masih error

**Comment by MrPawNO** [comment]
> @MrPawNO mang, coba dites command valentine. Di gw work

Sami'un gan obj error juga

**Comment by SlavyanDesu** [comment]
@romystuas coba update sc, udah ganti function `uploadImages()`

**Comment by romystuas** [comment]
> @romystuas coba update sc, udah ganti function `uploadImages()`

bisa bg alhamdulillah wkwkwk tqtqtq jgn lupa ngopi dan ngehentai bg biar seger abis ngoding

**Comment by SlavyanDesu** [comment]
> > @romystuas coba update sc, udah ganti function `uploadImages()`
> 
> bisa bg alhamdulillah wkwkwk tqtqtq jgn lupa ngopi dan ngehentai bg biar seger abis ngoding

awokowakaowk, mantab
