### ISSUE TITLE
puppeter error

### ISSUE THREAD

**Issue by debaji-db** [SlavyanDesu/BocchiBot#410]
**Question**
What would you like to ask?

D:\ruka v2.0\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'models')
    at Object.window.<computed>.<computed> [as sendImage] (__puppeteer_evaluation_script__:1:164004)
    at ExecutionContext._evaluateInternal (D:\ruka v2.0\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (D:\ruka v2.0\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)

**Comment by debaji-db** [comment]
> 

how to fix this??

**Comment by SlavyanDesu** [comment]
it's puppeteer's problem, please head to their repo

**Comment by debaji-db** [comment]
> it's puppeteer's problem, please head to their repo

Then ?

**Comment by gamingrkp** [comment]
> > it's puppeteer's problem, please head to their repo
> 
> Then ?

Just update npm i @open-wa/wa-automate@latest

**Comment by gamingrkp** [comment]
> > > > it's puppeteer's problem, please head to their repo
> > > 
> > > 
> > > Then ?
> > 
> > 
> > Just update npm i @open-wa/wa-automate@latest if still erorr just go open wa discord server thats error from open wa not from bocchi repo
> 
> Brother its still error .after updating 😿

What u trying to do what command?

**Comment by debaji-db** [comment]
> > > > > it's puppeteer's problem, please head to their repo
> > > > 
> > > > 
> > > > Then ?
> > > 
> > > 
> > > Just update npm i @open-wa/wa-automate@latest if still erorr just go open wa discord server thats error from open wa not from bocchi repo
> > 
> > 
> > Brother its still error .after updating 😿
> 
> What u trying to do what command?

After bot starts , this error comes and terminates node.js ..i cnt start my bot ,give tour Whstap no. Let me show u ss there

**Comment by gamingrkp** [comment]
> > > > > > it's puppeteer's problem, please head to their repo
> > > > > 
> > > > > 
> > > > > Then ?
> > > > 
> > > > 
> > > > Just update npm i @open-wa/wa-automate@latest if still erorr just go open wa discord server thats error from open wa not from bocchi repo
> > > 
> > > 
> > > Brother its still error .after updating 😿
> > 
> > 
> > What u trying to do what command?
> 
> After bot starts , this error comes and terminates node.js ..i cnt start my bot ,give tour Whstap no. Let me show u ss there

Dm me discord ohsyme#1181
