### ISSUE TITLE
cant use command $play, $ytmp4 and some command with same error like this

### ISSUE THREAD

**Issue by X3NNN** [SlavyanDesu/BocchiBot#417]
![image](https://user-images.githubusercontent.com/93273094/162077944-b45c8a90-d2af-4335-afc2-c5276c08516f.png)

Tidak bisa download lagu, video, dan ada juga laporan anoboy, dan lolivid, any idea to solve this ?

**Comment by X3NNN** [comment]
![image](https://user-images.githubusercontent.com/93273094/162078447-edf120df-5af7-4658-bc53-3970e54135a3.png)
dan kadang juga seperti ini muncul

**Comment by gamingrkp** [comment]
> ![image](https://user-images.githubusercontent.com/93273094/162077944-b45c8a90-d2af-4335-afc2-c5276c08516f.png)
> 
> Tidak bisa download lagu, video, dan ada juga laporan anoboy, dan lolivid, any idea to solve this ?

coba diganti ke api lolhuman deh

**Comment by X3NNN** [comment]
> > ![image](https://user-images.githubusercontent.com/93273094/162077944-b45c8a90-d2af-4335-afc2-c5276c08516f.png)
> > Tidak bisa download lagu, video, dan ada juga laporan anoboy, dan lolivid, any idea to solve this ?
> 
> coba diganti ke api lolhuman deh

![image](https://user-images.githubusercontent.com/93273094/162586429-8304dfe7-590e-4166-a316-2f7f95005c66.png)
tiap mau regist apikey lolhuman kek gini kluarnya

**Comment by gamingrkp** [comment]
> 

coba https://zenzapi.xyz

**Comment by gamingrkp** [comment]
> > > ![image](https://user-images.githubusercontent.com/93273094/162077944-b45c8a90-d2af-4335-afc2-c5276c08516f.png)
> > > Tidak bisa download lagu, video, dan ada juga laporan anoboy, dan lolivid, any idea to solve this ?
> > 
> > 
> > coba diganti ke api lolhuman deh
> 
> ![image](https://user-images.githubusercontent.com/93273094/162586429-8304dfe7-590e-4166-a316-2f7f95005c66.png) tiap mau regist apikey lolhuman kek gini kluarnya

coba https://zenzapi.xyz
