### ISSUE TITLE
ttg

### ISSUE THREAD

**Issue by rafaelmoris-hash** [SlavyanDesu/BocchiBot#42]
ttg nya kok double ya broo..
![IMG_20201214_143633](https://user-images.githubusercontent.com/75946163/102053323-22de5500-3e1a-11eb-99f4-735eb02a5ee2.jpg)

**Comment by SlavyanDesu** [comment]
![Untitled](https://user-images.githubusercontent.com/28254882/102053686-b879e480-3e1a-11eb-87e6-3e1703cf9d2a.png)
ini error dari wa-automate, yang sticker to giphy juga sama. ada kesalahan saat resizing ukuran gifnya. kalau di pc, fine fine aja

**Comment by SlavyanDesu** [comment]
![Untitled](https://user-images.githubusercontent.com/28254882/102053985-40f88500-3e1b-11eb-98b9-dbd299b0c233.png)
ini mah issue di wa-automate nya sob, gak bener saat resizing gif nya. kalau di pc fine fine aja
