### ISSUE TITLE
Help ngab

### ISSUE THREAD

**Issue by Suryapardana** [SlavyanDesu/BocchiBot#43]
**Question**
What would you like to ask?

![Screenshot_2020-12-14-18-05-42-112_com microsoft rdc android](https://user-images.githubusercontent.com/47344288/102074736-cbe77880-3e37-11eb-8762-696b7ff8ce00.jpg)

**Comment by SlavyanDesu** [comment]
```bash
> npm install node-gyp -g
> npm install --global --production windows-build-tools
```

**Comment by SlavyanDesu** [comment]
https://github.com/JoshuaWise/better-sqlite3/blob/master/docs/troubleshooting.md

**Comment by Suryapardana** [comment]
Saat npm start, no mode quick.db?

**Comment by Suryapardana** [comment]
![Screenshot_2020-12-14-18-57-59-309_com microsoft rdc android](https://user-images.githubusercontent.com/47344288/102078981-72367c80-3e3e-11eb-8057-38bd3b139198.jpg)

**Comment by SlavyanDesu** [comment]
Itu mas ada file `database/nsfw.json` gak? Di errornya tertulis kalau file `nsfw.json` gak ketemu

**Comment by Suryapardana** [comment]
Gaada mas

**Comment by MrPawNO** [comment]
> Gaada mas

Buat file nsfw.json, isi file nya taruh "[]" tanpa tanda kutip
save di database

**Comment by Suryapardana** [comment]
File database hilang semua sehabis install yg diatas

**Comment by SlavyanDesu** [comment]
> File database hilang semua sehabis install yg diatas

Kalau males bikin satu satu
```bash
> git pull origin master
```

**Comment by MrPawNO** [comment]
> File database hilang semua sehabis install yg diatas

ya buat file baru aja, ikutin sama kek cara bikin nsfw.json

**Comment by MrPawNO** [comment]
> > File database hilang semua sehabis install yg diatas
> 
> Kalau males bikin satu satu
> 
> ```shell
> > git pull origin master
> ```

wkwkwk ga sampe 5 file jangan males
