### ISSUE TITLE
Error: node_modules/canvas/build/Release/librsvg-2.so.2: cannot read file data

### ISSUE THREAD

**Issue by zinzui12345** [SlavyanDesu/BocchiBot#435]
>$ npm start

\> bocchibot@0.7.0 start /mnt/96DE4AF9DE4AD163/BocchiBot
\> node index.js

internal/modules/cjs/loader.js:807
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /mnt/96DE4AF9DE4AD163/BocchiBot/node_modules/canvas/build/Release/librsvg-2.so.2: cannot read file data
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/mnt/96DE4AF9DE4AD163/BocchiBot/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bocchibot@0.7.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bocchibot@0.7.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hikaru/.npm/_logs/2022-06-26T15_49_40_768Z-debug.log

**Comment by gamingrkp** [comment]
> > $ npm start
> 
> > bocchibot@0.7.0 start /mnt/96DE4AF9DE4AD163/BocchiBot > node index.js
> 
> internal/modules/cjs/loader.js:807 return process.dlopen(module, path.toNamespacedPath(filename)); ^
> 
> Error: /mnt/96DE4AF9DE4AD163/BocchiBot/node_modules/canvas/build/Release/librsvg-2.so.2: cannot read file data at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3) at Module.require (internal/modules/cjs/loader.js:692:17) at require (internal/modules/cjs/helpers.js:25:18) at Object. (/mnt/96DE4AF9DE4AD163/BocchiBot/node_modules/canvas/lib/bindings.js:3:18) at Module._compile (internal/modules/cjs/loader.js:778:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) at Module.load (internal/modules/cjs/loader.js:653:32) npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! bocchibot@0.7.0 start: `node index.js` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the bocchibot@0.7.0 start script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in: npm ERR! /home/hikaru/.npm/_logs/2022-06-26T15_49_40_768Z-debug.log

U use termux ? Rdp? Or smth?

**Comment by zinzui12345** [comment]
> U use termux ? Rdp? Or smth?

ubuntu desktop

**Comment by ohsyme** [comment]
> > U use termux ? Rdp? Or smth?
> 
> ubuntu desktop

try delete node_modules + package lock json and npm i again if still not work idk
