### ISSUE TITLE
scheduled message

### ISSUE THREAD

**Issue by salsawij** [SlavyanDesu/BocchiBot#436]
is scheduled message possible? what to use to make this work

**Comment by salsawij** [comment]
var cron = require('node-cron');
async function start() {
cron.schedule('10 * * * *', () => {
await conn.sendMessage(msg.from, "Hi sayang");
}
start();
)};
start();

i tried this, but it doesn't seem to be working, i'm not sure where I wrote it wrong

**Comment by ohsyme** [comment]
> async function start() {

wait what is that baileys????????

**Comment by salsawij** [comment]
yes

**Comment by ohsyme** [comment]
> yes

bocchi is open wa lmfao since when baileys

**Comment by salsawij** [comment]
well, a friend of mine told me that the code is pretty similar, so

**Comment by ohsyme** [comment]
> so the scheduled message code can't be implemented in baileys?

u still can in baileys there is m.from = m.from ( group id ) try get manual group id use console log

**Comment by salsawij** [comment]
what do i do then? is the code below usable or not?

**Comment by ohsyme** [comment]
> what do i do then? is the code below usable or not?

var cron = require('node-cron');
async function start() {
cron.schedule('10 * * * *', () => {
await conn.sendMessage('group id put here', "Hi sayang");
}
)};
start();

**Comment by ohsyme** [comment]
> > what do i do then? is the code below usable or not?
> 
> var cron = require('node-cron'); async function start() { cron.schedule('10 * * * *', () => { await conn.sendMessage('group id put here', "Hi sayang"); } )}; start();

![image](https://user-images.githubusercontent.com/49177554/176637226-5e9b916d-b6b5-40d0-b02a-4e6b32b2e906.png)
group id must be like this ( same open wa and baileys )

**Comment by ohsyme** [comment]
> ohh alright, thank you!! I've been using openwa for 1 to 2 weeks, but the it's very heavy in size. So i chose to use baileys since then openwa is easier than baileys tbh

```js
var cron = require('node-cron');

  var task = cron.schedule('* * * * *', () =>  {
    console.log('will execute every minute until stopped');
task.stop(); 

}, {
    // sisanya basic crontab ada di google
    // https://nodecron.com/docs/
    // node cron bsa ngikutin dari pc lu

    // kalo scheduled dibawah ini gw setting biar dia ngikutin jam indonesia kalo dibuat false dia jadi ngikutin time rdp lu
    //semua tentang cron ada di google ok

    // https://crontab.guru


    // Enable scheduled option
    scheduled: true,
    // Define china timezone
    timezone: 'Asia/Jakarta',
});
```
