### ISSUE TITLE
error bang mohon bantu

### ISSUE THREAD

**Issue by irf5455** [SlavyanDesu/BocchiBot#44]
FetchError: invalid json response body at https://api.vhtear.com/valentine?t1=#v
alentine%20babi%20&t2=ayam&l1=https://telegra.ph/file/8237aaad3d45a4123dba3.jpg&
l2=https://telegra.ph/file/2225977ac9f80fea91e29.jpg&apikey=myapikey reason: U
nexpected token < in JSON at position 0
    at c:\New-Sinchan-Bot-main\node_modules\node-fetch\lib\index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  type: 'invalid-json'
}

gmna ya

**Comment by irf5455** [comment]
mohon bantuannya ngab
:)

**Comment by MrPawNO** [comment]
> FetchError: invalid json response body at https://api.vhtear.com/valentine?t1=#v
> alentine%20babi%20&t2=ayam&l1=https://telegra.ph/file/8237aaad3d45a4123dba3.jpg&
> l2=https://telegra.ph/file/2225977ac9f80fea91e29.jpg&apikey=myapikey reason: U
> nexpected token < in JSON at position 0
> at c:\New-Sinchan-Bot-main\node_modules\node-fetch\lib\index.js:272:32
> at processTicksAndRejections (internal/process/task_queues.js:93:5) {
> type: 'invalid-json'
> }
> 
> gmna ya

apikey punya?

**Comment by irf5455** [comment]
> > FetchError: invalid json response body at https://api.vhtear.com/valentine?t1=#v
> > alentine%20babi%20&t2=ayam&l1=https://telegra.ph/file/8237aaad3d45a4123dba3.jpg&
> > l2=https://telegra.ph/file/2225977ac9f80fea91e29.jpg&apikey=myapikey reason: U
> > nexpected token < in JSON at position 0
> > at c:\New-Sinchan-Bot-main\node_modules\node-fetch\lib\index.js:272:32
> > at processTicksAndRejections (internal/process/task_queues.js:93:5) {
> > type: 'invalid-json'
> > }
> > gmna ya
> 
> apikey punya?

aku tutup

**Comment by irf5455** [comment]
> > FetchError: invalid json response body at https://api.vhtear.com/valentine?t1=#v
> > alentine%20babi%20&t2=ayam&l1=https://telegra.ph/file/8237aaad3d45a4123dba3.jpg&
> > l2=https://telegra.ph/file/2225977ac9f80fea91e29.jpg&apikey=myapikey reason: U
> > nexpected token < in JSON at position 0
> > at c:\New-Sinchan-Bot-main\node_modules\node-fetch\lib\index.js:272:32
> > at processTicksAndRejections (internal/process/task_queues.js:93:5) {
> > type: 'invalid-json'
> > }
> > gmna ya
> 
> apikey punya?

ku tutupin

**Comment by MrPawNO** [comment]
> FetchError: invalid json response body at https://api.vhtear.com/valentine?t1=#v
> alentine%20babi%20&t2=ayam&l1=https://telegra.ph/file/8237aaad3d45a4123dba3.jpg&
> l2=https://telegra.ph/file/2225977ac9f80fea91e29.jpg&apikey=myapikey reason: U
> nexpected token < in JSON at position 0
> at c:\New-Sinchan-Bot-main\node_modules\node-fetch\lib\index.js:272:32
> at processTicksAndRejections (internal/process/task_queues.js:93:5) {
> type: 'invalid-json'
> }
> 
> gmna ya

Ini maksudnya gimana kok ada tanda pagar "#" setelah t1

perintah nya dah bener?

**Comment by MrPawNO** [comment]
coba buka fun.js terus cek modul valentine nya, kirim sini

**Comment by irf5455** [comment]
![image](https://user-images.githubusercontent.com/72920582/102082029-ca23b200-3e43-11eb-82aa-aae711232db0.png)

**Comment by irf5455** [comment]
nih b

> coba buka fun.js terus cek modul valentine nya, kirim sini

nih bang

**Comment by MrPawNO** [comment]
> nih b
> 
> > coba buka fun.js terus cek modul valentine nya, kirim sini
> 
> nih bang

mana modul valentine nya

atau situ balikin ke aslinya aja

`git pull origin master`

**Comment by irf5455** [comment]
bisa ngab
gw  Berusaha sendiri tdi:v
mkasih ya

**Comment by MrPawNO** [comment]
> bisa ngab
> gw Berusaha sendiri tdi:v
> mkasih ya

sip, jangan lupa close issue
