### ISSUE TITLE
Cara Biar Ga bisa di add ke Group

### ISSUE THREAD

**Issue by herdypad** [SlavyanDesu/BocchiBot#440]
**Question**
Cara Biar Ga Asal Masuk Group pengaturannnya dimana yah

**Comment by herdypad** [comment]
di wa udah di seting biar ga bisa di add di group
tapi pas jalanin bot jadi bisa di add ke grouo

**Comment by Sansekai** [comment]
> di wa udah di seting biar ga bisa di add di group tapi pas jalanin bot jadi bisa di add ke grouo

Dia mungkin pakai fitur .join saran ku yah hapus/block aja case .join nya
