### ISSUE TITLE
level

### ISSUE THREAD

**Issue by xiaomipenboy** [SlavyanDesu/BocchiBot#45]
tambahkan fiturr level banggg kalau user ngirim pesan pada group, exp bertambah sampai memenuhi syarat naik level!

**Comment by SlavyanDesu** [comment]
> tambahkan fiturr level banggg kalau user ngirim pesan pada group, exp bertambah sampai memenuhi syarat naik level!

saya research dulu ya, semoga aja otak ku ini nyampe wkwkwkwk

**Comment by TobyG74** [comment]
https://github.com/Koolwiza/Leveling-System
contoh leveling dari bot dc, gunain module canvas

**Comment by SlavyanDesu** [comment]
> https://github.com/Koolwiza/Leveling-System
> contoh leveling dari bot dc, gunain module canvas

buat sistem leveling udah buat make quick.db, tinggal buat rank card. thanks anyway

**Comment by rafaelmoris-hash** [comment]
> > https://github.com/Koolwiza/Leveling-System
> > contoh leveling dari bot dc, gunain module canvas
> 
> buat sistem leveling udah make quick.db, tinggal buat rank card. thanks anyway

kutunggu jg wkwkwkw

**Comment by rafaelmoris-hash** [comment]
ini github auto rame kalau ada feature leveling

**Comment by rafaelmoris-hash** [comment]
ini github auto rame kalau ada feature leveling

**Comment by SlavyanDesu** [comment]
> ini github auto rame kalau ada feature leveling

Wkakakaka aamiin

**Comment by SlavyanDesu** [comment]
Gw juga ngerjainnya saat punya waktu luang juga sih, insya Allah hari ini selesai <strike>kalau gak males</strike>

**Comment by rafaelmoris-hash** [comment]
> Gw juga ngerjainnya saat punya waktu luang juga sih, insya Allah hari ini selesai kalau gak males

ogheyy ndak sabar wkwkwkwk

**Comment by SlavyanDesu** [comment]
dicoba https://github.com/SlavyanDesu/BocchiBot/commit/1bd4bce0c34d757d75c94c12ad454c586bc71505
inget ini masih dalam tahap *ALPHA* artinya belum bener-bener stabil dan masih banyak dalam tahap pengembangan, di build kali ini belum ada rank card, masih cuma text statis aja buat ceknya

**Comment by SlavyanDesu** [comment]
https://github.com/SlavyanDesu/BocchiBot/commit/151ec04bc369e2f8c131ff0bebcecc65506fb331 dah support rankcards

**Comment by SlavyanDesu** [comment]
semoga vps/rdp/server kalian sanggup write dan read message setiap grup ya, wkwkwk soalnya berat
