### ISSUE TITLE
play bug

### ISSUE THREAD

**Issue by 777days** [SlavyanDesu/BocchiBot#451]
Searching for suecideboys in YouTube...
TypeError: Cannot read properties of undefined (reading 'split')
    at /root/BocchiBot.1/message/index.js:1760:48
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Slavecode** [comment]
> Searching for suecideboys in YouTube... TypeError: Cannot read properties of undefined (reading 'split') at /root/BocchiBot.1/message/index.js:1760:48 at processTicksAndRejections (node:internal/process/task_queues:96:5)

Maybe the API is Dead

**Comment by SlavyanDesu** [comment]
@777days The API has been offline for a long time. Instead, I use the ytdl-core module to download videos from YouTube.
[Check this commit](https://github.com/SlavyanDesu/BocchiBot/commit/ea824115f31658ac9e3f22a2f02747de360cc149#diff-5dd0b44fba48c924feeb8df9da40dc4f1e2ce79dbd17e11e7bdc60b8ad90acdb).
