### ISSUE TITLE
How To Fix ?

### ISSUE THREAD

**Issue by kaewkoontawee** [SlavyanDesu/BocchiBot#458]
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::8080
    at Server.setupListenHandle [as _listen2] (node:net:1432:16)
    at listenInCluster (node:net:1480:12)
    at Server.listen (node:net:1568:7)
    at Function.listen (C:\Users\ACER\Desktop\BocchiBot\node_modules\express\lib\application.js:635:24)
    at start (C:\Users\ACER\Desktop\BocchiBot\index.js:29:9)
    at C:\Users\ACER\Desktop\BocchiBot\index.js:169:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1459:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 8080
}

**Comment by ohsyme** [comment]
> node:events:491 throw er; // Unhandled 'error' event ^
> 
> Error: listen EADDRINUSE: address already in use :::8080 at Server.setupListenHandle [as _listen2] (node:net:1432:16) at listenInCluster (node:net:1480:12) at Server.listen (node:net:1568:7) at Function.listen (C:\Users\ACER\Desktop\BocchiBot\node_modules\express\lib\application.js:635:24) at start (C:\Users\ACER\Desktop\BocchiBot\index.js:29:9) at C:\Users\ACER\Desktop\BocchiBot\index.js:169:23 at processTicksAndRejections (node:internal/process/task_queues:96:5) Emitted 'error' event on Server instance at: at emitErrorNT (node:net:1459:8) at processTicksAndRejections (node:internal/process/task_queues:83:21) { code: 'EADDRINUSE', errno: -4091, syscall: 'listen', address: '::', port: 8080 }

Restart ur pc

**Comment by SlavyanDesu** [comment]
> node:events:491 throw er; // Unhandled 'error' event ^
> 
> Error: listen EADDRINUSE: address already in use :::8080 at Server.setupListenHandle [as _listen2] (node:net:1432:16) at listenInCluster (node:net:1480:12) at Server.listen (node:net:1568:7) at Function.listen (C:\Users\ACER\Desktop\BocchiBot\node_modules\express\lib\application.js:635:24) at start (C:\Users\ACER\Desktop\BocchiBot\index.js:29:9) at C:\Users\ACER\Desktop\BocchiBot\index.js:169:23 at processTicksAndRejections (node:internal/process/task_queues:96:5) Emitted 'error' event on Server instance at: at emitErrorNT (node:net:1459:8) at processTicksAndRejections (node:internal/process/task_queues:83:21) { code: 'EADDRINUSE', errno: -4091, syscall: 'listen', address: '::', port: 8080 }

Please update the repository to latest version. Thanks.
