### ISSUE TITLE
doujin downloader

### ISSUE THREAD

**Issue by ikisadiasa** [SlavyanDesu/BocchiBot#46]
Gratisin command downloader doujin lah
👍👍

**Comment by LeviathanH** [comment]
> Gratisin command downloader doujin lah
> 👍👍

di github lain ada bro..., kalau ga mau ribet
@ikisadiasa

**Comment by SlavyanDesu** [comment]
Maaf gak bisa, silakan nyontek repo lain atau ngulik sendiri.
