### ISSUE TITLE
quick.db ERR

### ISSUE THREAD

**Issue by rafaelmoris-hash** [SlavyanDesu/BocchiBot#47]
AKU sdh install python dan taruh di folder C:\Program Files(x86)

![Screenshot_2](https://user-images.githubusercontent.com/75946163/102339635-05e78480-3fc8-11eb-8766-67ff70406aa0.png)

klw blh mnta tutor penginstalan yg baik & benar bg

**Comment by SlavyanDesu** [comment]
> AKU sdh install python dan taruh di folder C:\Program Files(x86)
> 
> ![Screenshot_2](https://user-images.githubusercontent.com/75946163/102339635-05e78480-3fc8-11eb-8766-67ff70406aa0.png)
> 
> klw blh mnta tutor penginstalan yg baik & benar bg

Set di PATH, di environment variable. Pas install python juga biasanya di bawah ada `Install to PATH`

**Comment by SlavyanDesu** [comment]
Uninstall, install lagi, centang install to PATH coba

**Comment by rafaelmoris-hash** [comment]
> Uninstall, install lagi, centang install to PATH coba

sbntr bang..

**Comment by rafaelmoris-hash** [comment]
> Uninstall, install lagi, centang install to PATH coba

![Screenshot_5](https://user-images.githubusercontent.com/75946163/102340989-c91c8d00-3fc9-11eb-9753-fadf166f2cef.png)


![Screenshot_4](https://user-images.githubusercontent.com/75946163/102340915-adb18200-3fc9-11eb-8718-504e615e564c.png)

sdh install ulang dan option nya seperti gbr diatas tetapi msih error

**Comment by irf5455** [comment]
hmm yang ditunggu akhirnya datang
auto fork lah

**Comment by rafaelmoris-hash** [comment]
tolong ksh tau hal apa saja yg hrs dilakukan bg daru nol

> > Uninstall, install lagi, centang install to PATH coba
> 
> ![Screenshot_5](https://user-images.githubusercontent.com/75946163/102340989-c91c8d00-3fc9-11eb-9753-fadf166f2cef.png)
> 
> ![Screenshot_4](https://user-images.githubusercontent.com/75946163/102340915-adb18200-3fc9-11eb-8718-504e615e564c.png)
> 
> sdh install ulang dan option nya seperti gbr diatas tetapi msih error

**Comment by SlavyanDesu** [comment]
https://geek-university.com/python/add-python-to-the-windows-path/ coba set manual aja sob

**Comment by SlavyanDesu** [comment]
Pastiin juga sudah restart cmd, alias tutup buka lagi

**Comment by rafaelmoris-hash** [comment]
> https://geek-university.com/python/add-python-to-the-windows-path/ coba set manual aja sob

tpi option instalasi python ku diatas udh benar kah bg???

**Comment by irf5455** [comment]
> > https://geek-university.com/python/add-python-to-the-windows-path/ coba set manual aja sob
> 
> tpi option instalasi python ku diatas udh benar kah bg???

add path ae

**Comment by SlavyanDesu** [comment]
> > https://geek-university.com/python/add-python-to-the-windows-path/ coba set manual aja sob
> 
> tpi option instalasi python ku diatas udh benar kah bg???

Sudah, tapi kalau saya install python nya nggak yang custom.

**Comment by SlavyanDesu** [comment]
> hmm yang ditunggu akhirnya datang
> auto fork lah

Nungguin apa nihh

**Comment by irf5455** [comment]
add python 3.9 path itu centang

> > hmm yang ditunggu akhirnya datang
> > auto fork lah
> 
> Nungguin apa nihh

leveling ngab:v

**Comment by SlavyanDesu** [comment]
> add python 3.9 path itu centang
> 
> > > hmm yang ditunggu akhirnya datang
> > > auto fork lah
> > 
> > 
> > Nungguin apa nihh
> 
> leveling ngab:v

Semoga stabil dah wkwk

**Comment by irf5455** [comment]
> > add python 3.9 path itu centang
> > > > hmm yang ditunggu akhirnya datang
> > > > auto fork lah
> > > 
> > > 
> > > Nungguin apa nihh
> > 
> > 
> > leveling ngab:v
> 
> Semoga stabil dah wkwk

amin amin :v:

**Comment by rafaelmoris-hash** [comment]
> > > https://geek-university.com/python/add-python-to-the-windows-path/ coba set manual aja sob
> > 
> > 
> > tpi option instalasi python ku diatas udh benar kah bg???
> 
> Sudah, tapi kalau saya install python nya nggak yang custom.

udh ku set path, malah npm not recognized haduhhhh

**Comment by SlavyanDesu** [comment]
Lah kok? Itu edit path atau nambah path? Diedit mas

**Comment by SlavyanDesu** [comment]
Kalau mau gini aja, fresh install. Install lagi semua requirements, lalu git clone dari awal. Btw kok baru kali ini aja errorny, kemarin tumben bisa

**Comment by AlvioAdjiJanuar** [comment]
Kalo error 
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS 
Gimana

**Comment by SlavyanDesu** [comment]
https://github.com/JoshuaWise/better-sqlite3/blob/master/docs/troubleshooting.md
Ini mas sudah saya taro di readme

**Comment by SlavyanDesu** [comment]
> Kalo error
> gyp ERR! find VS
> gyp ERR! find VS msvs_version not set from command line or npm config
> gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
> gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
> gyp ERR! find VS looking for Visual Studio 2015
> gyp ERR! find VS - not found
> gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
> gyp ERR! find VS
> gyp ERR! find VS **************************************************************
> gyp ERR! find VS You need to install the latest version of Visual Studio
> gyp ERR! find VS including the "Desktop development with C++" workload.
> gyp ERR! find VS For more information consult the documentation at:
> gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
> gyp ERR! find VS **************************************************************
> gyp ERR! find VS
> Gimana

Kalau diliat dari errornya, mas harus install visual studio 2017 dengan workload Desktop Development with C++

**Comment by SlavyanDesu** [comment]
Coba launch ini di CMD/Powershell (run as admin):
```bash
npm install --global windows-build-tools
```

**Comment by rafaelmoris-hash** [comment]
> Kalau mau gini aja, fresh install. Install lagi semua requirements, lalu git clone dari awal. Btw kok baru kali ini aja errorny, kemarin tumben bisa

Sudah ku install ulang node dan Python, sekarang masalah mlah di VS Code sama kek yg diatasku wkkwwkk

**Comment by SlavyanDesu** [comment]
Sama berarti. Liat itu di errornya, butuh latest Visual Studio lalu didalemnya download Desktop Development with C++, ukurannya kalau gak salah saya dowbload 1.20 GB. Wkwkwk, gininih malesnya make sqlite

**Comment by SlavyanDesu** [comment]
> Coba launch ini di CMD/Powershell (run as admin):
> 
> ```shell
> npm install --global windows-build-tools
> ```

Atau coba aja ini dulu

**Comment by rafaelmoris-hash** [comment]
> Sama berarti. Liat itu di errornya, butuh latest Visual Studio lalu didalemnya download Desktop Development with C++, ukurannya kalau gak salah saya dowbload 1.20 GB. Wkwkwk, gininih malesnya make sqlite

wkwkwk alhamdulillah inet ku cepat, baru download Dekstop Development with C++ nya, dan lagi instalasi package semoga gada masalah tmbhan wkkwkk

**Comment by rafaelmoris-hash** [comment]
> > Coba launch ini di CMD/Powershell (run as admin):
> > ```shell
> > npm install --global windows-build-tools
> > ```
> 
> Atau coba aja ini dulu

klw ini error bnyk bg

**Comment by AlvioAdjiJanuar** [comment]
> Sama berarti. Liat itu di errornya, butuh latest Visual Studio lalu didalemnya download Desktop Development with C++, ukurannya kalau gak salah saya dowbload 1.20 GB. Wkwkwk, gininih malesnya make sqlite

Serius Kalo Yang make ini lama ga 
npm install --global windows-build-tools

**Comment by SlavyanDesu** [comment]
> > Sama berarti. Liat itu di errornya, butuh latest Visual Studio lalu didalemnya download Desktop Development with C++, ukurannya kalau gak salah saya dowbload 1.20 GB. Wkwkwk, gininih malesnya make sqlite
> 
> Serius Kalo Yang make ini lama ga
> npm install --global windows-build-tools

Kayaknya sama aja sih sob, kelebihan make itu karena otomatis install tools yang dibutuhkan

**Comment by SlavyanDesu** [comment]
Kepencet jir
Btw, kemarin saya juga error kayak gini ampe stress kwkwkwk

**Comment by rafaelmoris-hash** [comment]
> > > Sama berarti. Liat itu di errornya, butuh latest Visual Studio lalu didalemnya download Desktop Development with C++, ukurannya kalau gak salah saya dowbload 1.20 GB. Wkwkwk, gininih malesnya make sqlite
> > 
> > 
> > Serius Kalo Yang make ini lama ga
> > npm install --global windows-build-tools
> 
> Kayaknya sama aja sih sob, kelebihan make itu karena otomatis install tools yang dibutuhkan

trs berkembang dan rendah hati brooo.., aku star + fork krna ni git selalu update & ownernya baik hahahaha

**Comment by AlvioAdjiJanuar** [comment]
> > > Sama berarti. Liat itu di errornya, butuh latest Visual Studio lalu didalemnya download Desktop Development with C++, ukurannya kalau gak salah saya dowbload 1.20 GB. Wkwkwk, gininih malesnya make sqlite
> > 
> > 
> > Serius Kalo Yang make ini lama ga
> > npm install --global windows-build-tools
> 
> Kayaknya sama aja sih sob, kelebihan make itu karena otomatis install tools yang dibutuhkan

Starting installation...
Please restart this script from an administrative PowerShell!
The build tools cannot be installed without administrative rights.
To fix, right-click on PowerShell and run "as Administrator".
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! windows-build-tools@5.2.2 postinstall: `node ./dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the windows-build-tools@5.2.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Error gini :(

**Comment by AlvioAdjiJanuar** [comment]
Pas lagi npm install --global windows-build-tools

**Comment by irf5455** [comment]
> > > > Sama berarti. Liat itu di errornya, butuh latest Visual Studio lalu didalemnya download Desktop Development with C++, ukurannya kalau gak salah saya dowbload 1.20 GB. Wkwkwk, gininih malesnya make sqlite
> > > 
> > > 
> > > Serius Kalo Yang make ini lama ga
> > > npm install --global windows-build-tools
> > 
> > 
> > Kayaknya sama aja sih sob, kelebihan make itu karena otomatis install tools yang dibutuhkan
> 
> trs berkembang dan rendah hati brooo.., aku star + fork krna ni git selalu update & ownernya baik hahahaha

betul tuh bro:v

**Comment by irf5455** [comment]
> Pas lagi npm install --global windows-build-tools

kok gw ngga error tak, tinggal centang add path doang, udh itu aja gaada lagi yg di edit edit

**Comment by SlavyanDesu** [comment]
> Pas lagi npm install --global windows-build-tools

Run as administrator dulu sobat

**Comment by rafaelmoris-hash** [comment]
Alhamdulillah work, aku ada sedikit saran.. liat issue lain brooo

**Comment by SlavyanDesu** [comment]
> Alhamdulillah work, aku ada sedikit saran.. liat issue lain brooo

Syukroonn
