### ISSUE TITLE
Installing bot

### ISSUE THREAD

**Issue by WanXdOffc** [SlavyanDesu/BocchiBot#479]
**Question**
Halo, ini kenapa ya? Saya ingin mencoba SC ini, saya masih pemula maaf hehe :v

![Screenshot_20230201-161132](https://user-images.githubusercontent.com/121989438/215995814-e1296edb-4919-4e9c-b87f-040fcc832c5c.jpg)
![Screenshot_20230201-161121](https://user-images.githubusercontent.com/121989438/215995830-4b0b6585-ad9e-4791-8d7b-0a12f24f857c.jpg)

**Comment by SlavyanDesu** [comment]
Coba install Google Chrome di server-nya, kalau nggak support bisa ganti `useChrome` ke `false`
https://github.com/SlavyanDesu/BocchiBot/blob/26977dd947f3002ab56ae856204a496f0dd23fd2/tools/index.js#L62-L82

**Comment by SlavyanDesu** [comment]
Kekurangannya jadi nggak bisa kirim video secara langsung, jadi yang ke kirim bakal dalam bentuk dokumen/file.

**Comment by WanXdOffc** [comment]
Waduh biar bisa tanpa di false in kek gimana🙃

**Comment by SlavyanDesu** [comment]
> Waduh biar bisa tanpa di false in kek gimana🙃

Install Chrome coba, beda ya sama Chromium

**Comment by WanXdOffc** [comment]
Caranya gimana @SlavyanDesu

**Comment by SlavyanDesu** [comment]
OS apa?

**Comment by WanXdOffc** [comment]
OS apa?

**Comment by WanXdOffc** [comment]
@SlavyanDesu panelnya linux

**Comment by WanXdOffc** [comment]
@SlavyanDesu aku tidak tau OS nya, aku make panel amgeekz.site

**Comment by SlavyanDesu** [comment]
> @SlavyanDesu aku tidak tau OS nya, aku make panel amgeekz.site

```
sudo apt-get install libssl1.0.0 libssl-dev --reinstall
```

Coba run ini dulu lalu start bot-nya. Kalau masih nggak bisa, coba install Google Chrome.

```sh
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo add-apt-repository "deb http://dl.google.com/linux/chrome/deb/ stable main"
sudo apt update
sudo apt install google-chrome-stable
```

**Comment by WanXdOffc** [comment]
Caranya? Ini di command nya tulis gini?

**Comment by WanXdOffc** [comment]
![Screenshot_20230201-201351](https://user-imags.githubusercontent.com/121989438/216039696-834cd6ba-22e8-4827-85cb-39dd4fbafd5a.jpg) 
@SlavyanDesu

**Comment by WanXdOffc** [comment]
![Screenshot_20230201-201351](https://user-images.githubusercontent.com/121989438/216039831-aabd7f19-045f-40d9-84fd-8cd208635161.jpg)

@SlavyanDesu

**Comment by SlavyanDesu** [comment]
Iya coba run satu-satu.

**Comment by WanXdOffc** [comment]
![Screenshot_20230201-202443](https://user-images.githubusercontent.com/121989438/216042031-245454f5-a7d2-4d4a-8f81-1fa5bb68882c.jpg)

@SlavyanDesu ?

**Comment by WanXdOffc** [comment]
![Screenshot_20230201-202844](https://user-images.githubusercontent.com/121989438/216042602-e129f3dc-5a36-47f3-8021-07070d0cd666.jpg)
@SlavyanDesu

**Comment by SlavyanDesu** [comment]
@WanXdOffc hmm, ini beneran linux? Kok `wget` dan `sudo` nggak bisa di run ya. Coba tanya ke admin-nya, bisa installin Chrome ngga.

**Comment by WanXdOffc** [comment]
@SlavyanDesu katanya gatau

**Comment by SlavyanDesu** [comment]
Wadaw, aku juga jadi nggak bisa bantu. Aku udah coba juga nyoba deploy di panel-nya, masih nggak bisa.

**Comment by WanXdOffc** [comment]
Terus bisanya run di apa?, Next kalo bisa dibuat bisa di panel pterodactly

**Comment by SlavyanDesu** [comment]
> Terus bisanya run di apa?, Next kalo bisa dibuat bisa di panel pterodactly

Asalkan ada Chrome sama bisa pakai Chromium bisa run. Kalau buat kompabilitas library bisa request ke [`wa-automate-nodejs`](https://github.com/open-wa/wa-automate-nodejs) langsung.

**Comment by SlavyanDesu** [comment]
Aku liat Pterodactyl bisa run `apt`, mungkin bisa deploy di situ. Aku belum pernah pakai panel kayak gitu.

**Comment by WanXdOffc** [comment]
Terus run dimana @SlavyanDesu

**Comment by AnymPedia** [comment]
Mending run di VPS nya langsung @WanXdOffc

**Comment by SlavyanDesu** [comment]
Issue closed ya
