### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by rafaelmoris-hash** [SlavyanDesu/BocchiBot#48]
Setiap user bisa liat leaderboard top 10 level,exp semua user broo

**Comment by SlavyanDesu** [comment]
Oke... Nanti ya, mau liat kestabilan leveling dulu kwkwk

**Comment by rafaelmoris-hash** [comment]
> Oke... Nanti ya, mau liat kestabilan leveling dulu kwkwk

aku lvl 6 masa di levelcard, rank nya 6 bg kwkwkwk

**Comment by rafaelmoris-hash** [comment]
> > Oke... Nanti ya, mau liat kestabilan leveling dulu kwkwk
> 
> aku lvl 1 ga naik-naik bg, rank malah naik ke 10..,

**Comment by SlavyanDesu** [comment]
> > > Oke... Nanti ya, mau liat kestabilan leveling dulu kwkwk
> > 
> > 
> > aku lvl 1 ga naik-naik bg, rank malah naik ke 10..,

rank? perasaan belom kubikin fitur rank
di mananya ya?

**Comment by rafaelmoris-hash** [comment]
cb ketik level bg

disamping kiri level ada rank

seharusnya semakin tinggi level, semakin rendah rank

**Comment by rafaelmoris-hash** [comment]
> cb ketik level bg
> 
> disamping kiri level ada rank
> 
> seharusnya semakin tinggi level, semakin rendah rank

di levelcard

**Comment by SlavyanDesu** [comment]
anjir baru ngeh bentar wwkwkwkwkwk

**Comment by rafaelmoris-hash** [comment]
> anjir baru ngeh bentar wwkwkwkwkwk

trs jg wktu naik level gd reply 'selamat kamu naik level' dari bot

**Comment by SlavyanDesu** [comment]
> > anjir baru ngeh bentar wwkwkwkwkwk
> 
> trs jg wktu naik level gd reply 'selamat kamu naik level' dari bot

buat rank nya udah ku fix, buat bot yang gak respon nanti ini lagi ku cek

**Comment by rafaelmoris-hash** [comment]
> > > anjir baru ngeh bentar wwkwkwkwkwk
> > 
> > 
> > trs jg wktu naik level gd reply 'selamat kamu naik level' dari bot
> 
> buat rank nya udah ku fix, buat bot yang gak respon nanti ini lagi ku cek

bot nya dah respon bg,, tpi masa setiap ada yg chat sekali naik 1 level, cepet banget

**Comment by SlavyanDesu** [comment]
> > > > anjir baru ngeh bentar wwkwkwkwkwk
> > > 
> > > 
> > > trs jg wktu naik level gd reply 'selamat kamu naik level' dari bot
> > 
> > 
> > buat rank nya udah ku fix, buat bot yang gak respon nanti ini lagi ku cek
> 
> bot nya dah respon bg,, tpi masa setiap ada yg chat sekali naik 1 level, cepet banget

nah ini setting aja sendiri gan, kurangin aja angkanya di sini:
https://github.com/SlavyanDesu/BocchiBot/blob/c856c9140d3bd80ce3806d4491f4825bd6702d23/message/index.js#L87

**Comment by rafaelmoris-hash** [comment]
> > > > > anjir baru ngeh bentar wwkwkwkwkwk
> > > > 
> > > > 
> > > > trs jg wktu naik level gd reply 'selamat kamu naik level' dari bot
> > > 
> > > 
> > > buat rank nya udah ku fix, buat bot yang gak respon nanti ini lagi ku cek
> > 
> > 
> > bot nya dah respon bg,, tpi masa setiap ada yg chat sekali naik 1 level, cepet banget
> 
> nah ini setting aja sendiri gan, kurangin aja angkanya di sini:
> https://github.com/SlavyanDesu/BocchiBot/blob/c856c9140d3bd80ce3806d4491f4825bd6702d23/message/index.js#L87

Yg d krngin mana bg, angka 5 atau 10

**Comment by SlavyanDesu** [comment]
> > > > > > anjir baru ngeh bentar wwkwkwkwkwk
> > > > > 
> > > > > 
> > > > > trs jg wktu naik level gd reply 'selamat kamu naik level' dari bot
> > > > 
> > > > 
> > > > buat rank nya udah ku fix, buat bot yang gak respon nanti ini lagi ku cek
> > > 
> > > 
> > > bot nya dah respon bg,, tpi masa setiap ada yg chat sekali naik 1 level, cepet banget
> > 
> > 
> > nah ini setting aja sendiri gan, kurangin aja angkanya di sini:
> > https://github.com/SlavyanDesu/BocchiBot/blob/c856c9140d3bd80ce3806d4491f4825bd6702d23/message/index.js#L87
> 
> Yg d krngin mana bg, angka 5 atau 10

bebas ngab, btw itu kenapa jadi cepet naik levelnya karena gw salah ngetik wkwkwkwkwkkw

**Comment by SlavyanDesu** [comment]
ini aku lagi fix bentar

**Comment by SlavyanDesu** [comment]
sip dah fix

**Comment by SlavyanDesu** [comment]
> > > > > anjir baru ngeh bentar wwkwkwkwkwk
> > > > 
> > > > 
> > > > trs jg wktu naik level gd reply 'selamat kamu naik level' dari bot
> > > 
> > > 
> > > buat rank nya udah ku fix, buat bot yang gak respon nanti ini lagi ku cek
> > 
> > 
> > bot nya dah respon bg,, tpi masa setiap ada yg chat sekali naik 1 level, cepet banget
> 
> nah ini setting aja sendiri gan, kurangin aja angkanya di sini:
> https://github.com/SlavyanDesu/BocchiBot/blob/c856c9140d3bd80ce3806d4491f4825bd6702d23/message/index.js#L87

```js
const xpAdd = Math.floor(Math.random() * 10) + 500
/** 
 * Kalau 500 diganti, berarti setiap message itu xp nya 500 dan 10 itu maksudnya nambahin puluhan di antara angka 0 sampe 10.
 * Jadi ini hasilnya bakal sekitar 500, 501, 502 dan seterusny sampe 510.
 */
```

**Comment by SlavyanDesu** [comment]
@rafaelmoris-hash semoga ngerti ya

**Comment by rafaelmoris-hash** [comment]
> @rafaelmoris-hash semoga ngerti ya

siap bg ngerti tencuu, ditunggu leaderboard wkwkwkw

**Comment by rafaelmoris-hash** [comment]
> @rafaelmoris-hash semoga ngerti ya

broo seharusnya leveling nya jngn pergrup aku coba grup A level 30 pas aktifin di Grup B malah level 1

dibikin keseluruhan aja supaya bisa ada leaderboard

**Comment by SlavyanDesu** [comment]
> > @rafaelmoris-hash semoga ngerti ya
> 
> broo seharusnya leveling nya jngn pergrup aku coba grup A level 30 pas aktifin di Grup B malah level 1
> 
> dibikin keseluruhan aja supaya bisa ada leaderboard

wah kalau itu gimana yah, soalnya bot di discord juga kek gitu sih

**Comment by selyxn** [comment]
> > > @rafaelmoris-hash semoga ngerti ya
> > 
> > 
> > broo seharusnya leveling nya jngn pergrup aku coba grup A level 30 pas aktifin di Grup B malah level 1
> > dibikin keseluruhan aja supaya bisa ada leaderboard
> 
> wah kalau itu gimana yah, soalnya bot di discord juga kek gitu sih

bot sebelah leaderboard nya kseluruhan broo, maap btw bawa-bawa bot sebelah wwkwk

**Comment by rafaelmoris-hash** [comment]
> > > > @rafaelmoris-hash semoga ngerti ya
> > > 
> > > 
> > > broo seharusnya leveling nya jngn pergrup aku coba grup A level 30 pas aktifin di Grup B malah level 1
> > > dibikin keseluruhan aja supaya bisa ada leaderboard
> > 
> > 
> > wah kalau itu gimana yah, soalnya bot di discord juga kek gitu sih
> 
> bot sebelah leaderboard nya kseluruhan broo, maap btw bawa-bawa bot sebelah wwkwk

suek... anda ngikutin saranku

**Comment by SlavyanDesu** [comment]
yaudah saya buat global based leveling

**Comment by SlavyanDesu** [comment]
global based udah, tinggal stuck buat leaderboard :')

**Comment by rafaelmoris-hash** [comment]
> global based udah, tinggal stuck buat leaderboard :')

cemangat bg <3

**Comment by rafaelmoris-hash** [comment]
> global based udah, tinggal stuck buat leaderboard :')

bgg ini saya ketik #level 
tpi yg keluar di levelcard level 3
sedangkan botna reply "Selamat kamu telah naik ke level 30"

btw cara reset db level gmnah?

**Comment by SlavyanDesu** [comment]
> > global based udah, tinggal stuck buat leaderboard :')
> 
> bgg ini saya ketik #level
> tpi yg keluar di levelcard level 3
> sedangkan botna reply "Selamat kamu telah naik ke level 30"
> 
> btw cara reset db level gmnah?

Hapus file `json.sqlite`

**Comment by rafaelmoris-hash** [comment]
> > > global based udah, tinggal stuck buat leaderboard :')
> > 
> > 
> > bgg ini saya ketik #level
> > tpi yg keluar di levelcard level 3
> > sedangkan botna reply "Selamat kamu telah naik ke level 30"
> > btw cara reset db level gmnah?
> 
> Hapus file `json.sqlite`

dimana bg file nya

**Comment by SlavyanDesu** [comment]
Di folder bot, di awal

**Comment by MrPawNO** [comment]
> > global based udah, tinggal stuck buat leaderboard :')
> 
> bgg ini saya ketik #level
> tpi yg keluar di levelcard level 3
> sedangkan botna reply "Selamat kamu telah naik ke level 30"
> 
> btw cara reset db level gmnah?

di case level, sendtext nya hapus aja menurutku

**Comment by SlavyanDesu** [comment]
Boleh aja sih dihapus pemberitahuan naik levelnya, tapi kekurangannya kita jadi gak tau naik level atau nggak

**Comment by MrPawNO** [comment]
> Boleh aja sih dihapus pemberitahuan naik levelnya, tapi kekurangannya kita jadi gak tau naik level atau nggak

Udah gw coba, tetep ada pemberitahuan naik level kok ngab kalo exp memenuhi

**Comment by MrPawNO** [comment]
Kan yang dihapus waktu user ngetik case level

**Comment by SlavyanDesu** [comment]
Yang bagian mana sob?
https://github.com/SlavyanDesu/BocchiBot/blob/302e675a37b775fa613d9ec87e8b15b618506595/message/index.js#L143-L179

**Comment by MrPawNO** [comment]
> Yang bagian mana sob?
> https://github.com/SlavyanDesu/BocchiBot/blob/302e675a37b775fa613d9ec87e8b15b618506595/message/index.js#L143-L179

![Screenshot_8](https://user-images.githubusercontent.com/13583912/102496577-28ea6500-40aa-11eb-9a17-08aa79f7b737.png)

Kok beda ngab, tadi sebelumnya dibawah const refetchLevel ada await client reply

**Comment by MrPawNO** [comment]
![Screenshot_9](https://user-images.githubusercontent.com/13583912/102496724-5b945d80-40aa-11eb-8d05-28b351f98d00.png)
Line 94 w hapus

**Comment by SlavyanDesu** [comment]
oooo i seee

**Comment by SlavyanDesu** [comment]
@rafaelmoris-hash @selyxn dicoba, minimal harus 10 user yang punya level ya kan mintanya top 10. rapihin aja listnya mau dikerenin kek apa kek, saya gak jago gituan wwkwkwkwk

**Comment by rafaelmoris-hash** [comment]
> @rafaelmoris-hash @selyxn dicoba [5d2a54c](https://github.com/SlavyanDesu/BocchiBot/commit/5d2a54c9ff6bedffc8c37d66634a89c9a2c7cb9e) , minimal harus 10 user yang punya level ya kan mintanya top 10. rapihin aja listnya mau dikerenin kek apa kek, saya gak jago gituan wwkwkwkwk

itu leaderboard list ny dibikin pushname,currentlevel & current xp lh bg kwkwkwk ndak pandai aku
