### ISSUE TITLE
Block words/symbols from chats

### ISSUE THREAD

**Issue by minein4** [SlavyanDesu/BocchiBot#482]
**Question**
Hello i have a group chat for my college and sometimes things get a bit to spicy so id love to know if there is a way to make it auto delete words/symbols automatically from a group chat.

Thanks

**Comment by SlavyanDesu** [comment]
Yes, there's a way to do that. For convenience, I'm going to set this issue to a feature request. I'm gonna add a command to do the job.
Usage will be look like this:
```
.blockwords [the_words]
```

**Comment by SlavyanDesu** [comment]
Done #484.
This is how to use it.
https://github.com/SlavyanDesu/BocchiBot/blob/c065c4550855153f74ff951aa9a18be6638e56cf/message/text/lang/eng.js#L789-L792
