### ISSUE TITLE
personal error with leveling system

### ISSUE THREAD

**Issue by fsrastdyyf** [SlavyanDesu/BocchiBot#490]
Hi, i was using this template, but when I send a message, the xp system gives an error 
(TypeError: Cannot read properties of undefined (reading 'getLevelingLevel')
    at C:\Users\Home\Desktop\dvstBot-main\index.js:81:44
    at Client.<anonymous> (C:\Users\Home\Desktop\dvstBot-main\node_modules\@open-wa\wa-automate\dist\api\Client.js:803:92)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Home\Desktop\dvstBot-main\node_modules\@open-wa\wa-automate\dist\api\Client.js:28:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5))
    
    I have modified something in the code, and i deleted things, but i can't understand where is the error... 
    I put the interested part of the code
    
    
    Level.js: (that it's the same)
    `const fs = require('fs-extra')

/**
 * Get user ID from db.
 * @param {string} userId
 * @param {object} _dir
 * @returns {string}
 */
const getLevelingId = (userId, _dir) => {
    let pos = null
    let found = false
    Object.keys(_dir).forEach((i) => {
        if (_dir[i].id === userId) {
            pos = i
            found = true
        }
    })
    if (found === false && pos === null) {
        const obj = { id: userId, xp: 0, level: 1 }
        _dir.push(obj)
        fs.writeFileSync('./database/user/level.json', JSON.stringify(_dir))
        return userId
    } else {
        return _dir[pos].id
    }
}

const getLevelingLevel = (userId, _dir) => {
    let pos = null
    let found = false
    Object.keys(_dir).forEach((i) => {
        if (_dir[i].id === userId) {
            pos = i
            found = true
        }
    })
    if (found === false && pos === null) {
        const obj = { id: userId, xp: 0, level: 1 }
        _dir.push(obj)
        fs.writeFileSync('./database/user/level.json', JSON.stringify(_dir))
        return 1
    } else {
        return _dir[pos].level
    }
}

/**
 * Get user XP from db.
 * @param {string} userId
 * @param {object} _dir
 * @returns {number}
 */
const getLevelingXp = (userId, _dir) => {
    let pos = null
    let found = false
    Object.keys(_dir).forEach((i) => {
        if (_dir[i].id === userId) {
            pos = i
            found = true
        }
    })
    if (found === false && pos === null) {
        const obj = { id: userId, xp: 0, level: 1 }
        _dir.push(obj)
        fs.writeFileSync('./database/user/level.json', JSON.stringify(_dir))
        return 0
    } else {
        return _dir[pos].xp
    }
}

/**
 * Add user level to db.
 * @param {string} userId
 * @param {number} amount
 * @param {object} _dir
 */
const addLevelingLevel = (userId, amount, _dir) => {
    let position = null
    Object.keys(_dir).forEach((i) => {
        if (_dir[i].id === userId) {
            position = i
        }
    })
    if (position !== null) {
        _dir[position].level += amount
        fs.writeFileSync('./database/user/level.json', JSON.stringify(_dir))
    }
}

/**
 * Add user XP to db.
 * @param {string} userId
 * @param {number} amount
 * @param {object} _dir
 */
const addLevelingXp = (userId, amount, _dir) => {
    let position = null
    Object.keys(_dir).forEach((i) => {
        if (_dir[i].id === userId) {
            position = i
        }
    })
    if (position !== null) {
        _dir[position].xp += amount
        fs.writeFileSync('./database/user/level.json', JSON.stringify(_dir))
    }
}

/**
 * Get user rank.
 * @param {string} userId
 * @param {object} _dir
 * @returns {number}
 */
const getUserRank = (userId, _dir) => {
    let position = null
    let found = false
    _dir.sort((a, b) => (a.xp < b.xp) ? 1 : -1)
    Object.keys(_dir).forEach((i) => {
        if (_dir[i].id === userId) {
            position = i
            found = true
        }
    })
    if (found === false && position === null) {
        const obj = { id: userId, xp: 0, level: 1 }
        _dir.push(obj)
        fs.writeFileSync('./database/user/level.json', JSON.stringify(_dir))
        return 99
    } else {
        return position + 1
    }
}

// Cooldown XP gains to prevent spam
const xpGain = new Set()

/**
 * Check is user exist in set.
 * @param {string} userId
 * @returns {boolean}
 */
const isGained = (userId) => {
    return !!xpGain.has(userId)
}

/**
 * Add user in set and delete it when it's 1 minute.
 * @param {string} userId
 */
const addCooldown = (userId) => {

    if (!userId || typeof userId !== 'string') {
        return;}

    xpGain.add(userId)
    setTimeout(() => {
        return xpGain.delete(userId)
    }, 60000) // Each minute
}

module.exports = {
    getLevelingId,
    getLevelingLevel,
    getLevelingXp,
    addLevelingLevel,
    addLevelingXp,
    getUserRank,
    isGained,
    addCooldown
}`

Index.js:
`bot.onMessage(async message => {
    
        const { id, from, isGroupMsg, chat, caption } = message
        const _leveling = JSON.parse(fs.readFileSync('./database/group/leveling.json'))
        const groupId = isGroupMsg ? chat.groupMetadata.id : ''
        const isLevelingOn = isGroupMsg ? _leveling.includes(groupId) : false
        const { level } = require('./level.js')
        const _level = JSON.parse(fs.readFileSync('./database/user/level.json'))
        let { body } = message
            
            // Leveling [BETA] by Slavyan
        if (isGroupMsg && isLevelingOn) {
            try {
                
                const currentLevel = level.getLevelingLevel(message.author, _level)
                const amountXp = Math.floor(Math.random() * (15 - 25 + 1) + 15)
                const requiredXp = 5 * Math.pow(currentLevel, 2) + 50 * currentLevel + 100
                level.addLevelingXp(message.author, amountXp, _level)
                if (requiredXp <= level.getLevelingXp(message.author, _level)) {
                    level.addLevelingLevel(message.author, 1, _level)
                    const userLevel = level.getLevelingLevel(message.author, _level)
                    const fetchXp = 5 * Math.pow(userLevel, 2) + 50 * userLevel + 100
                    const pushname = message.sender.pushname;
                    await bot.reply(message.from, `*── 「 LEVEL UP 」 ──*\n\n➸ *Name*: ${pushname}\n➸ *XP*: ${level.getLevelingXp(message.author, _level)} / ${fetchXp}\n➸ *Level*: ${currentLevel} -> ${level.getLevelingLevel(message.author, _level)} 🆙 \n\n\n-BocchiBot`, id)
                }
            } catch (err) {
                console.error(err)
            }
        }`
        
        bot is the session for @open-wa/wa-automate
        sometimes i use the whatsapp-web.js library
        
        Thanks

**Comment by SlavyanDesu** [comment]
This can be fixed by copying [function](https://github.com/SlavyanDesu/BocchiBot/tree/master/function) folder into your bot folder.

**Comment by SlavyanDesu** [comment]
The bot directory structure would be like this.
```
Bot-name
├── function
├─ index.js
rest of directory 
```
