### ISSUE TITLE
Stuck Authenticating

### ISSUE THREAD

**Issue by anantorisqy** [SlavyanDesu/BocchiBot#492]
Hallo Om gw coba host di vps linux tapi stuck di Authenticating gimana ?

**Comment by SlavyanDesu** [comment]
Halo @anantorisqy. Bisa kasih log lengkapnya?

**Comment by anantorisqy** [comment]
✓ Use this easy pre-filled link to report an issue: https://github.com/open-wa/wa-automate-nodejs/issues/new?template=bug_report.yaml&d_info=%7B%0A%20%20%22WA_VERSION%22:%20%222.2310.5%22,%0A%20%20%22WA_AUTOMATE_VERSION%22:%20%224.58.0%22,%0A%20%20%22BROWSER_VERSION%22:%20%22HeadlessChrome/110.0.5481.177%22,%0A%20%20%22START_TS%22:%201678234824756,%0A%20%20%22RAM_INFO%22:%20%22Total:%202.08%20GB%20%7C%20Free:%200.64%20GB%22,%0A%20%20%22PPTR_VERSION%22:%20%2219.7.3%22,%0A%20%20%22LATEST_VERSION%22:%20true,%0A%20%20%22CLI%22:%20false%0A%7D&enviro=-%20OS:%20Linux%205.4%0A-%20Node:%2019.7.0%0A-%20npm:%209.6.0&labels=MD
✓ Launch inject: 596ms
🌖  Authenticating
 
Stuck di situ terus

**Comment by SlavyanDesu** [comment]
> ✓ Use this easy pre-filled link to report an issue: https://github.com/open-wa/wa-automate-nodejs/issues/new?template=bug_report.yaml&d_info=%7B%0A%20%20%22WA_VERSION%22:%20%222.2310.5%22,%0A%20%20%22WA_AUTOMATE_VERSION%22:%20%224.58.0%22,%0A%20%20%22BROWSER_VERSION%22:%20%22HeadlessChrome/110.0.5481.177%22,%0A%20%20%22START_TS%22:%201678234824756,%0A%20%20%22RAM_INFO%22:%20%22Total:%202.08%20GB%20%7C%20Free:%200.64%20GB%22,%0A%20%20%22PPTR_VERSION%22:%20%2219.7.3%22,%0A%20%20%22LATEST_VERSION%22:%20true,%0A%20%20%22CLI%22:%20false%0A%7D&enviro=-%20OS:%20Linux%205.4%0A-%20Node:%2019.7.0%0A-%20npm:%209.6.0&labels=MD ✓ Launch inject: 596ms 🌖 Authenticating
> 
> Stuck di situ terus

Nomor udah diganti di bagian `config.json`?
