### ISSUE TITLE
Ytmp3/4

### ISSUE THREAD

**Issue by uukdesu** [SlavyanDesu/BocchiBot#5]
command yt responnya "IP anda xx.xxx.xxx.xxx tidak diizinkan" itu gmn ya?

**Comment by SlavyanDesu** [comment]
> command yt responnya "IP anda xx.xxx.xxx.xxx tidak diizinkan" itu gmn ya?

Set API static dulu di [sini](https://api.i-tech.id/settings/profile) ya sob
