### ISSUE TITLE
halo

### ISSUE THREAD

**Issue by selyxn** [SlavyanDesu/BocchiBot#50]
![Screenshot_7](https://user-images.githubusercontent.com/69533502/102358253-e3626500-3fe1-11eb-80c1-dd40f9a50b8a.png)

gimana noh ada user yg ngirim stiker di grup/pc ...,, console mengeluarkan output error

**Comment by SlavyanDesu** [comment]
itu sc terbaru atau lama?

**Comment by selyxn** [comment]
> itu sc terbaru atau lama?

terbaru

**Comment by MrPawNO** [comment]
> ![Screenshot_7](https://user-images.githubusercontent.com/69533502/102358253-e3626500-3fe1-11eb-80c1-dd40f9a50b8a.png)
> 
> gimana noh ada user yg ngirim stiker di grup/pc ...,, console mengeluarkan output error

Di sc ane gaada code inviteInfo
situ masukin code sembarangan kah?

**Comment by selyxn** [comment]
> > ![Screenshot_7](https://user-images.githubusercontent.com/69533502/102358253-e3626500-3fe1-11eb-80c1-dd40f9a50b8a.png)
> > gimana noh ada user yg ngirim stiker di grup/pc ...,, console mengeluarkan output error
> 
> Di sc ane gaada code inviteInfo
> situ masukin code sembarangan kah?

hooh bener akowkowokowk

**Comment by SlavyanDesu** [comment]
fixed?

**Comment by selyxn** [comment]
> fixed?

belum

**Comment by SlavyanDesu** [comment]
```bash
> git pull origin master
```
