### ISSUE TITLE
Bot dieksekusi di cmd, saya mengirim perintah dan tidak ada yang terjadi.

### ISSUE THREAD

**Issue by gabrielwsy** [SlavyanDesu/BocchiBot#51]
Halo, saya mengalami masalah, saya menjalankan perintah, perintah muncul di cmd, tetapi tidak ada yang terjadi, saya sudah mengirim beberapa perintah dan tidak ada yang terjadi. Bisakah Anda memberi tahu saya apa itu bisa ?!
![image](https://user-images.githubusercontent.com/40281950/102372427-f18e9200-3f9d-11eb-9461-005d59a85438.png)

**Comment by SlavyanDesu** [comment]
> Halo, saya mengalami masalah, saya menjalankan perintah, perintah muncul di cmd, tetapi tidak ada yang terjadi, saya sudah mengirim beberapa perintah dan tidak ada yang terjadi. Bisakah Anda memberi tahu saya apa itu bisa ?!
> ![image](https://user-images.githubusercontent.com/40281950/102372427-f18e9200-3f9d-11eb-9461-005d59a85438.png)

That's very strange, did you somehow change something to the code?

**Comment by SlavyanDesu** [comment]
using english is ok btw

**Comment by irf5455** [comment]
@SlavyanDesu aku gatau klo kamu itu cewe apa cowo,  tapi aku mau nanya, kok pas di gc yang berbeda xp nya ga muncul,  dan klo kita ngetik $level pun kaga ada yg muncul

**Comment by SlavyanDesu** [comment]
> @SlavyanDesu aku gatau klo kamu itu cewe apa cowo, tapi aku mau nanya, kok pas di gc yang berbeda xp nya ga muncul, dan klo kita ngetik $level pun kaga ada yg muncul

soalnya ini nge-store xp nya per-grup. tadi ada yang request minta biar di grup lain juga bisa, yaudah ini lagi buat kok

**Comment by irf5455** [comment]
> > @SlavyanDesu aku gatau klo kamu itu cewe apa cowo, tapi aku mau nanya, kok pas di gc yang berbeda xp nya ga muncul, dan klo kita ngetik $level pun kaga ada yg muncul
> 
> soalnya ini nge-store xp nya per-grup. tadi ada yang request minta biar di grup lain juga bisa, yaudah ini lagi buat kok

siap

**Comment by gabrielwsy** [comment]
> > Halo, saya mengalami masalah, saya menjalankan perintah, perintah muncul di cmd, tetapi tidak ada yang terjadi, saya sudah mengirim beberapa perintah dan tidak ada yang terjadi. Bisakah Anda memberi tahu saya apa itu bisa ?!
> > ![image](https://user-images.githubusercontent.com/40281950/102372427-f18e9200-3f9d-11eb-9461-005d59a85438.png)
> 
> That's very strange, did you somehow change something to the code?

hello, I managed to solve the problem. I had deleted the old version to reinstall again, only that I had forgotten to restart the pc after installing, I just restarted and it is working normally.
I'm sorry for the confusion and thank you very much for your attention.
