### ISSUE TITLE
Armbian-Linux

### ISSUE THREAD

**Issue by whatdefood** [SlavyanDesu/BocchiBot#511]
**Apakah ini juga bisa berjalan normal di armbian-linux?**
Aku udah coba di armbian(base ubuntu) dan mendapatkan massalah seperti ini:

![image](https://user-images.githubusercontent.com/122113333/230755881-6801077a-38c6-4e29-b5a8-8ed58650c22e.png)
![image](https://user-images.githubusercontent.com/122113333/230755971-405b7be3-9ec7-48bf-a534-cf2c1740cf87.png)

Seperti yang ku tanyakan, apa ini bisa dijalankan diOS armbian?
jika bisa, minta tolong bantu aku untuk menyelesaikan error ini :)

tetapi jika memang tidak bisa, saya berharap ada pengembangan lanjut untuk itu :). 

**Terimakasih**

**Comment by SlavyanDesu** [comment]
Oalah itu contributor lupa masukkin async di promise await, nanti saya fix setelah pulang.

**Comment by SlavyanDesu** [comment]
Dicoba update dulu, udah saya tambahin.
```bash
$ git pull
```

**Comment by whatdefood** [comment]
> Dicoba update dulu, udah saya tambahin.
> 
> ```shell
> $ git pull
> ```


Maaf tapi masih belum bisa 
(apa benar seperti ini?)

![image](https://user-images.githubusercontent.com/122113333/230756910-98aef49a-0e14-4252-a89d-ee1d3f8f81f8.png)

**Comment by Piyoxz** [comment]
> 

tambahkan async seperti ini di function/quizizz js 
![image](https://user-images.githubusercontent.com/102013178/230757666-c5fd6649-7289-4dee-90ab-5d641fa66ecf.png)

**Comment by whatdefood** [comment]
Terimakasih, sudah fixs sekarang

![image](https://user-images.githubusercontent.com/122113333/230761159-1e85b0c0-3a45-43f9-88cd-e7483e06b1a3.png)

Tapi bot ngga ngrespon sama sekali saat ditest menggunakan command-command yang ada :)

Bahkan pada status linked device, bertuliskan last active 2.52 pm (bukan "active")
Apakah ada solusi untuk ini ? 

![image](https://user-images.githubusercontent.com/122113333/230761288-33ac3a8b-e215-4f2c-8c92-46366df460f4.png)
**Terimakasih**

**Comment by Piyoxz** [comment]
> Bahkan pada status linked device, bertuliskan last active 2.52 pm (bukan "active")

Coba di scan ulang

**Comment by whatdefood** [comment]
> > Bahkan pada status linked device, bertuliskan last active 2.52 pm (bukan "active")
> 
> Coba di scan ulang

udah berulang ulang dicoba scan, selalu seperti itu

**Comment by whatdefood** [comment]
> > > Bahkan pada status linked device, bertuliskan last active 2.52 pm (bukan "active")
> > 
> > 
> > Coba di scan ulang
> 
> udah berulang ulang dicoba scan, selalu seperti itu

**sudah FIXS, dengan mengganti chrome ke chromium-browser :) Terimakasih**
