### ISSUE TITLE
Error In case 'level'

### ISSUE THREAD

**Issue by AlvioAdjiJanuar** [SlavyanDesu/BocchiBot#52]
Kenapa begini terus yak 
[EROR] Error: Level data must be a number, received object!
    at Rank.setLevel (C:\Users\Piyobot\node_modules\canvacord\src\Rank.js:367:45)
    at HandleMsg (C:\Users\Piyobot\HandleMsg.js:361:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by irf5455** [comment]
> Kenapa begini terus yak
> [EROR] Error: Level data must be a number, received object!
> at Rank.setLevel (C:\Users\Piyobot\node_modules\canvacord\src\Rank.js:367:45)
> at HandleMsg (C:\Users\Piyobot\HandleMsg.js:361:22)
> at runMicrotasks ()
> at processTicksAndRejections (internal/process/task_queues.js:93:5)

ya begitu kalo di grup yang berbeda

**Comment by AlvioAdjiJanuar** [comment]
Berbeda apa ?

**Comment by MrPawNO** [comment]
> Kenapa begini terus yak
> [EROR] Error: Level data must be a number, received object!
> at Rank.setLevel (C:\Users\Piyobot\node_modules\canvacord\src\Rank.js:367:45)
> at HandleMsg (C:\Users\Piyobot\HandleMsg.js:361:22)
> at runMicrotasks ()
> at processTicksAndRejections (internal/process/task_queues.js:93:5)

Itu data nya kosong
Di enable dulu leveling nya, nunggu user nambah exp baru bisa case level

**Comment by irf5455** [comment]
> > Kenapa begini terus yak
> > [EROR] Error: Level data must be a number, received object!
> > at Rank.setLevel (C:\Users\Piyobot\node_modules\canvacord\src\Rank.js:367:45)
> > at HandleMsg (C:\Users\Piyobot\HandleMsg.js:361:22)
> > at runMicrotasks ()
> > at processTicksAndRejections (internal/process/task_queues.js:93:5)
> 
> Itu data nya kosong
> Di enable dulu leveling nya, nunggu user nambah exp baru bisa case level

ohh pas gw coba, yang gaada pp gabisa

**Comment by AlvioAdjiJanuar** [comment]
Khusus yang pp wa nya ke public gitu ?

**Comment by irf5455** [comment]
> Khusus yang pp wa nya ke public gitu ?

yap tadi we nyoba ga pake pp, error jadinya
pas gw pasang pp, bisa

**Comment by SlavyanDesu** [comment]
fixed https://github.com/SlavyanDesu/BocchiBot/commit/601a7d7c82142095ac967ec8bdd9c19c7f0f65ce
