### ISSUE TITLE
suggesting to add new feature

### ISSUE THREAD

**Issue by Satouchii** [SlavyanDesu/BocchiBot#522]
1. rpg system
2. economy system
3. leaderboard
4. more downloader commands
5. nsfw commands

just suggesting but can you add it? :P

**Comment by SlavyanDesu** [comment]
I'll do my best. But for the NSFW commands it used to be available but I decided to remove it, if you want to see the previous version go check here.

https://github.com/SlavyanDesu/BocchiBot/tree/8ec4b02ee4e32f3eb8fd37366f18a39c8a72cbf9/lib

**Comment by ohsyme** [comment]
Sebenernya gw malas 🗿

**Comment by Satouchii** [comment]
> Sebenernya gw malas 🗿

jgnlh malas min :v

**Comment by ohsyme** [comment]
> > Sebenernya gw malas moyai
> 
> jgnlh malas min :v

Gw memprediksi yang kepake cuma fitur downloader doang 🗿

**Comment by ohsyme** [comment]
gw kerjain pas slapyan udh bikin handler + rubah jdi tees

**Comment by Satouchii** [comment]
> gw kerjain pas slapyan udh bikin handler + rubah jdi tees

Mantep min :v

**Comment by ohsyme** [comment]
gaada perkembangan ampe skrng :V

**Comment by SlavyanDesu** [comment]
> gaada perkembangan ampe skrng :V

The library is dead lmao
