### ISSUE TITLE
Cara install di termux gimana?


### ISSUE THREAD

**Issue by DimazRizky** [SlavyanDesu/BocchiBot#545]
Bang cara install bot nya di termux gimana?

**Comment by ENisTod** [comment]
Bang cara install bot nya di termux gimana?

**Comment by ohsyme** [comment]
> Bang cara install bot nya di termux gimana?

pake proot-distro install ubuntu tapi ntar hp panas karna puppeteer agak berat mending beli vps/rdp

**Comment by DimazRizky** [comment]
Oke thanks bang
