### ISSUE TITLE
Cannot read property 'xp' of undefined

### ISSUE THREAD

**Issue by AlvioAdjiJanuar** [SlavyanDesu/BocchiBot#55]
Kok setiap ada yang ngechat di grup atau di grup ada yang gunain menu 
pasti muncul gini 
TypeError: Cannot read property 'xp' of undefined
    at HandleMsg (C:\Users\Lenovo\Piyobot\HandleMsg.js:318:47)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
TypeError: Cannot read property 'xp' of undefined
    at HandleMsg (C:\Users\Lenovo\Piyobot\HandleMsg.js:318:47)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Itu gimana mas

**Comment by rahmat225** [comment]
Bagaimana caranya menginstall quick.db saya sudah pasang quick.db di packge.json tetapi kaya gini kalau saya npm i malah terdapat error tidak dapat menemukan modul 'quick.db'??

**Comment by SlavyanDesu** [comment]
> Kok setiap ada yang ngechat di grup atau di grup ada yang gunain menu
> pasti muncul gini
> TypeError: Cannot read property 'xp' of undefined
> at HandleMsg (C:\Users\Lenovo\Piyobot\HandleMsg.js:318:47)
> at processTicksAndRejections (internal/process/task_queues.js:93:5)
> TypeError: Cannot read property 'xp' of undefined
> at HandleMsg (C:\Users\Lenovo\Piyobot\HandleMsg.js:318:47)
> at processTicksAndRejections (internal/process/task_queues.js:93:5)
> Itu gimana mas

Nanti saya cek ya

**Comment by SlavyanDesu** [comment]
> Bagaimana caranya menginstall quick.db saya sudah pasang quick.db di packge.json tetapi kaya gini kalau saya npm i malah terdapat error tidak dapat menemukan modul 'quick.db'??

Hapus folder `.node_modules`, terus install lagi

**Comment by rafaelmoris-hash** [comment]
> > Kok setiap ada yang ngechat di grup atau di grup ada yang gunain menu
> > pasti muncul gini
> > TypeError: Cannot read property 'xp' of undefined
> > at HandleMsg (C:\Users\Lenovo\Piyobot\HandleMsg.js:318:47)
> > at processTicksAndRejections (internal/process/task_queues.js:93:5)
> > TypeError: Cannot read property 'xp' of undefined
> > at HandleMsg (C:\Users\Lenovo\Piyobot\HandleMsg.js:318:47)
> > at processTicksAndRejections (internal/process/task_queues.js:93:5)
> > Itu gimana mas
> 
> Nanti saya cek ya

saya jg gitu bro btw

**Comment by AlvioAdjiJanuar** [comment]
> > Kok setiap ada yang ngechat di grup atau di grup ada yang gunain menu
> > pasti muncul gini
> > TypeError: Cannot read property 'xp' of undefined
> > at HandleMsg (C:\Users\Lenovo\Piyobot\HandleMsg.js:318:47)
> > at processTicksAndRejections (internal/process/task_queues.js:93:5)
> > TypeError: Cannot read property 'xp' of undefined
> > at HandleMsg (C:\Users\Lenovo\Piyobot\HandleMsg.js:318:47)
> > at processTicksAndRejections (internal/process/task_queues.js:93:5)
> > Itu gimana mas
> 
> Nanti saya cek ya

Okeey

**Comment by rahmat225** [comment]
> > Bagaimana caranya menginstall quick.db saya sudah pasang quick.db di packge.json tetapi kaya gini kalau saya npm i malah terdapat error tidak dapat menemukan modul 'quick.db'??
> 
> Hapus folder `.node_modules`, terus install lagi
itu quick db di install pake npm atau quick.db nya di taro package.json??

**Comment by SlavyanDesu** [comment]
Kemungkinan si user punya level di file `json.sqlite`, tapi kan xp nya bukan berbentuk database lagi sekarang mah. Udah di-store dalam bentuk file JSON, kemarin baru ganti metode storing-nya. Keknya dengan menghapus kedua file database `json.sqlite` sama `xp.json` bisa solved. Kalau masih gak bisa, nanti saya lanjut cek lagi.

**Comment by SlavyanDesu** [comment]
> > > Bagaimana caranya menginstall quick.db saya sudah pasang quick.db di packge.json tetapi kaya gini kalau saya npm i malah terdapat error tidak dapat menemukan modul 'quick.db'??
> > 
> > 
> > Hapus folder `.node_modules`, terus install lagi
> > itu quick db di install pake npm atau quick.db nya di taro package.json??

```bash
> npm install quick.db
```

**Comment by rafaelmoris-hash** [comment]
> Kemungkinan si user punya level di file `json.sqlite`, tapi kan xp nya bukan berbentuk database lagi sekarang mah. Udah di-store dalam bentuk file JSON, kemarin baru ganti metode storing-nya. Keknya dengan menghapus kedua file database `json.sqlite` sama `xp.json` bisa solved. Kalau masih gak bisa, nanti saya lanjut cek lagi.

leaderbord dong bg pakai pushname,currentxp,dan currentlvl

**Comment by SlavyanDesu** [comment]
@AlvioAdjiJanuar dicoba update sc, kalau masih error, hapus file `json.sqlite` sama isi file `xp.json`

**Comment by SlavyanDesu** [comment]
Apakah sudah solved?

**Comment by AlvioAdjiJanuar** [comment]
> Apakah sudah solved? ane gk bisaa :)

**Comment by SlavyanDesu** [comment]
> > Apakah sudah solved? ane gk bisaa :)

errornya beda lagi atau nggak?

**Comment by AlvioAdjiJanuar** [comment]
> > > Apakah sudah solved? ane gk bisaa :)
> 
> errornya beda lagi atau nggak?

gk muncul di xp json

**Comment by SlavyanDesu** [comment]
join group aja biar enak https://chat.whatsapp.com/LTTm0HGvFRu7uU23mr7ZaR

**Comment by SlavyanDesu** [comment]
# Announcement
Silakan update source code ke versi terbaru.
```bash
> git pull orgin master
```

# Changelog
* Mengganti method storing data dari menggunakan `Quick.db` ke JSON array object, karena banyak mengeluh error.
* Register kini hadir dengan model storing yang lebih simpel dengan JSON array object.
* Update string bahasa Inggris.
* Tersedia [group WhatsApp](https://chat.whatsapp.com/LTTm0HGvFRu7uU23mr7ZaR) untuk live support.
* Refactoring.

# Note
Ini akan menghapus data register dan XP/level user, jika kalian tidak ingin menghilangkannya kalian bisa copy data-data tersebut lalu memasukannya lagi secara manual. It can be helped though, sorry.
