### ISSUE TITLE
Config.json telephonenumber

### ISSUE THREAD

**Issue by Johannes099** [SlavyanDesu/BocchiBot#554]
Hey there, 
I'm now trying to get the Bot run the 5th time. 
This time, i have the problem, that in the config.json in the Bot-Owner"" field, im not quite sure, how to put the phonenumber of the bot inside, i mean why is there an "@" and where to put the country-code, it looks like regx , but if it would be, than 1st why would i have to edit it, and 2nd, how would the bot know than, what number it sould use. 
I also wonderd if i should install/ clone the repo also into C:\ or into the standard path.? 
 Thank you for your help. 
  Johannes

**Comment by SlavyanDesu** [comment]
Let's say I live in Indonesia which is the country code is +62 and my phone number is +6281234567890, simply change this field to `6281234567890@c.us`.
https://github.com/SlavyanDesu/BocchiBot/blob/fbec180e9d642728de72d3df7387e56ea9145769/config.json#L2
