### ISSUE TITLE
Packages blocking each other from updating | package.json & packages-lock.json

### ISSUE THREAD

**Issue by Johannes099** [SlavyanDesu/BocchiBot#555]
Hey there,
Im sorry for my 2nd bug report, but this one is very important, and if this wont get fixed, you cant use the bot.
If you want to install the dependencys (npm install) you get many errors, and npm wants you to do npm audit , npm audit fix, and npm audit fix --force, to repair it, but, and here it comes, the version requirements in the package.json and package-lock.json are blocking each other from installing / fixing them, because some dependencys require a newer version, but since some packages are give for Example "2.3.0" ( i dont think that this exists in the code but its just an example) so npm automaticly downgrades the package again, but sine other packages require a other version, so I guess you get the point. Also the package ""request" is no longer supportet by the maintance, but I think with the right versions of the oter packages (( like the newest of though-cookie, which is one of the best exampels for the downgrading issiue) it shouldnt be a problem. 
 Please Fix this Problem very soon and reach out to me for (you wont need help because your good) but if you need it with repleacing code parts, just tell me. 
Theank you for your help. 
Johannes

**Comment by SlavyanDesu** [comment]
Thanks for letting me know, you can do a pull request if you want.

I'm not quite sure if the main library (wa-automate-nodejs) still working or not because the author is no longer maintaining the library due to a strike from Meta.

**Comment by Johennesofi** [comment]
Hey, 
Thank you for your quck reply, i figuerd out and spend the last hours (( i started befor this post), butt the last problem i cantsolve. I configured alll packages right, but the last 5 moderated serverity vulnerabilities i cant solve ( the oneS with the request, ) so the last errorr, is your Task pleas, here is thee new package-lock.json and package.json script. 
 Johannes

[package-lock.json](https://github.com/SlavyanDesu/BocchiBot/files/13452624/package-lock.json)
[package.json](https://github.com/SlavyanDesu/BocchiBot/files/13452625/package.json)

**Comment by Johennesofi** [comment]
also, here is the link to the error, the other solouton would be, to write a patch for the request ( not the @cypress/request) package but I dont know how.  ? 
 So yea, Thank you for your help @SlavyanDesu , 
 Johannnes

**Comment by SlavyanDesu** [comment]
Hi.
Thanks for figuring it out. I will check it out later.

**Comment by Johennesofi** [comment]
Yea, thx , i kinda solved it, but where , can i configure the "" commands" ? Like the .menu likes

**Comment by SlavyanDesu** [comment]
Pretty sure it's `.help`. Sorry for the late reply, I don't even know is it still working or not.

**Comment by Johannes099** [comment]
No, in the meanwhile i fixed it by manually changing all versions but 200moderatate errors
