### ISSUE TITLE
leaderboard

### ISSUE THREAD

**Issue by rafaelmoris-hash** [SlavyanDesu/BocchiBot#56]
itu leaderboard list ny dibikin pushname,currentlevel & current xp lh bg kwkwkwk ndak pandai aku @SlavyanDesu

**Comment by SlavyanDesu** [comment]
@MrPawNO mang, tau gak caranya ngambil pushname dari nomor?

**Comment by rafaelmoris-hash** [comment]
klau getXp untuk leaderboard gmn bg @SlavyanDesu

**Comment by SlavyanDesu** [comment]
nanti ya sob, aku mau fix error yang lain dulu

**Comment by SlavyanDesu** [comment]
@rafaelmoris-hash done sob buat yang xp, update sc

**Comment by SlavyanDesu** [comment]
kalau pushname aku gatau masih newbie wkwkwk

**Comment by rafaelmoris-hash** [comment]
> @rafaelmoris-hash done sob buat yang xp, update sc

![IMG_20201218_170641](https://user-images.githubusercontent.com/75946163/102601980-74a51900-4153-11eb-9649-135df2e85a4f.jpg)

Napa ya ini bg XP ga sesuai dengan rank

**Comment by rafaelmoris-hash** [comment]
apa sy harus reset dlu?

**Comment by SlavyanDesu** [comment]
> apa sy harus reset dlu?

Disortirnya dari level sih

**Comment by rafaelmoris-hash** [comment]
> > apa sy harus reset dlu?
> 
> Disortirnya dari level sih

dlm arti gsh pke XP di leaderboard bg?

**Comment by SlavyanDesu** [comment]
> > @rafaelmoris-hash done sob buat yang xp, update sc
> 
> ![IMG_20201218_170641](https://user-images.githubusercontent.com/75946163/102601980-74a51900-4153-11eb-9649-135df2e85a4f.jpg)
> 
> Napa ya ini bg XP ga sesuai dengan rank

method udah diganti

**Comment by SlavyanDesu** [comment]
coba update ngab

**Comment by rafaelmoris-hash** [comment]
> coba update ngab

keren bg mntap

**Comment by SlavyanDesu** [comment]
Work?

**Comment by rafaelmoris-hash** [comment]
> Work?

yoi

**Comment by MrPawNO** [comment]
> @MrPawNO mang, tau gak caranya ngambil pushname dari nomor?

Nanti kucoba ngab

**Comment by SlavyanDesu** [comment]
> > @MrPawNO mang, tau gak caranya ngambil pushname dari nomor?
> 
> Nanti kucoba ngab

Ditunggu sob
