### ISSUE TITLE
Error in bocchi.onGlobalParicipantsChanged

### ISSUE THREAD

**Issue by AlvioAdjiJanuar** [SlavyanDesu/BocchiBot#57]
const pic = await bocchi.getProfilePicFromServer(event.who)
                if (pic === '' || pic === undefined) pic = 'https://i.imgur.com/UxvMPUz.png' 
error disininya mas

**Comment by SlavyanDesu** [comment]
Error lognya apa?

**Comment by AlvioAdjiJanuar** [comment]
Kek ada yang masuk ke grup tapi yang kena semuanya
Botnya langsung ngirim foto semua anggota grup dan selamat datang 
gitu lah pokoknya

**Comment by SlavyanDesu** [comment]
wah parah sih, tapi udah saya ganti method nya

**Comment by SlavyanDesu** [comment]
dicoba sc baru

**Comment by AlvioAdjiJanuar** [comment]
uhm
