### ISSUE TITLE
eror pas npm i gmn atasinya

### ISSUE THREAD

**Issue by akujeleksad** [SlavyanDesu/BocchiBot#58]
**Question**
What would you like to ask?

C:\BocchiBot-master\node_modules\better-sqlite3>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:302:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:314:5)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:456:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\BocchiBot-master\node_modules\better-sqlite3
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.1.1 build-release: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the better-sqlite3@7.1.1 build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Asus\AppData\Roaming\npm-cache\_logs\2020-12-18T07_33_17_872Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.1.1 install: `prebuild-install || npm run build-release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the better-sqlite3@7.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Asus\AppData\Roaming\npm-cache\_logs\2020-12-18T07_33_18_887Z-debug.log

C:\BocchiBot-master>--python="C:\Path\To\python.exe
'--python' is not recognized as an internal or external command,
operable program or batch file.

**Comment by SlavyanDesu** [comment]
> **Question**
> What would you like to ask?
> 
> C:\BocchiBot-master\node_modules\better-sqlite3>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild --release ) else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )
> gyp ERR! find Python
> gyp ERR! find Python Python is not set from command line or npm configuration
> gyp ERR! find Python Python is not set from environment variable PYTHON
> gyp ERR! find Python checking if "python" can be used
> gyp ERR! find Python - "python" is not in PATH or produced an error
> gyp ERR! find Python checking if "python2" can be used
> gyp ERR! find Python - "python2" is not in PATH or produced an error
> gyp ERR! find Python checking if "python3" can be used
> gyp ERR! find Python - "python3" is not in PATH or produced an error
> gyp ERR! find Python checking if the py launcher can be used to find Python 2
> gyp ERR! find Python - "py.exe" is not in PATH or produced an error
> gyp ERR! find Python checking if Python is C:\Python27\python.exe
> gyp ERR! find Python - "C:\Python27\python.exe" could not be run
> gyp ERR! find Python checking if Python is C:\Python37\python.exe
> gyp ERR! find Python - "C:\Python37\python.exe" could not be run
> gyp ERR! find Python
> gyp ERR! find Python **********************************************************
> gyp ERR! find Python You need to install the latest version of Python.
> gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
> gyp ERR! find Python you can try one of the following options:
> gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
> gyp ERR! find Python (accepted by both node-gyp and npm)
> gyp ERR! find Python - Set the environment variable PYTHON
> gyp ERR! find Python - Set the npm configuration variable python:
> gyp ERR! find Python npm config set python "C:\Path\To\python.exe"
> gyp ERR! find Python For more information consult the documentation at:
> gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
> gyp ERR! find Python **********************************************************
> gyp ERR! find Python
> gyp ERR! configure error
> gyp ERR! stack Error: Could not find any Python installation to use
> gyp ERR! stack at PythonFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
> gyp ERR! stack at PythonFinder.runChecks (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
> gyp ERR! stack at PythonFinder. (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
> gyp ERR! stack at PythonFinder.execFileCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
> gyp ERR! stack at exithandler (child_process.js:302:5)
> gyp ERR! stack at ChildProcess.errorhandler (child_process.js:314:5)
> gyp ERR! stack at ChildProcess.emit (events.js:210:5)
> gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
> gyp ERR! stack at onErrorNT (internal/child_process.js:456:16)
> gyp ERR! stack at processTicksAndRejections (internal/process/task_queues.js:80:21)
> gyp ERR! System Windows_NT 10.0.18363
> gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild" "--release"
> gyp ERR! cwd C:\BocchiBot-master\node_modules\better-sqlite3
> gyp ERR! node -v v12.13.0
> gyp ERR! node-gyp -v v5.0.5
> gyp ERR! not ok
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! better-sqlite3@7.1.1 build-release: `node-gyp rebuild --release`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the better-sqlite3@7.1.1 build-release script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\Asus\AppData\Roaming\npm-cache_logs\2020-12-18T07_33_17_872Z-debug.log
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! better-sqlite3@7.1.1 install: `prebuild-install || npm run build-release`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the better-sqlite3@7.1.1 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\Asus\AppData\Roaming\npm-cache_logs\2020-12-18T07_33_18_887Z-debug.log
> 
> C:\BocchiBot-master>--python="C:\Path\To\python.exe
> '--python' is not recognized as an internal or external command,
> operable program or batch file.

install python, jangan lupa centang add python to PATH

**Comment by akujeleksad** [comment]
pas dimana

**Comment by SlavyanDesu** [comment]
pas install

**Comment by SlavyanDesu** [comment]
silakan baca readme terlebih dahulu

**Comment by akujeleksad** [comment]
okok
