### ISSUE TITLE
i is not defined

### ISSUE THREAD

**Issue by rafaelmoris-hash** [SlavyanDesu/BocchiBot#59]
![Screenshot_12](https://user-images.githubusercontent.com/75946163/102589374-8251a300-4141-11eb-8926-fa20d2900754.png)

![Screenshot_13](https://user-images.githubusercontent.com/75946163/102589384-85e52a00-4141-11eb-8468-7fdba65658cb.png)

setiap user chat

**Comment by SlavyanDesu** [comment]
iya tadi salah, wkwkwkw. udah fix

**Comment by SlavyanDesu** [comment]
update aja
