### ISSUE TITLE
REQ

### ISSUE THREAD

**Issue by selyxn** [SlavyanDesu/BocchiBot#6]
Halo gan, mau request fitur

bisa tolong buatin limit untuk command tertentu gak?
sekalian fitur nsfw nya tambahin pornhubdl

Terimakasih.

**Comment by SlavyanDesu** [comment]
> Halo gan, mau request fitur
> 
> bisa tolong buatin limit untuk command tertentu gak?
> sekalian fitur nsfw nya tambahin pornhubdl
> 
> Terimakasih.

Diusahakan ya sob

**Comment by SlavyanDesu** [comment]
> Halo gan, mau request fitur
> 
> bisa tolong buatin limit untuk command tertentu gak?
> sekalian fitur nsfw nya tambahin pornhubdl
> 
> Terimakasih.

Oh iya, saya butuh info lebih lanjut. Limit ini tuh berupa apa? Waktu pemakaian sehari, user khusus (seperti user premium)?

**Comment by selyxn** [comment]
> > Halo gan, mau request fitur
> > bisa tolong buatin limit untuk command tertentu gak?
> > sekalian fitur nsfw nya tambahin pornhubdl
> > Terimakasih.
> 
> Oh iya, saya butuh info lebih lanjut. Limit ini tuh berupa apa? Waktu pemakaian sehari, user khusus (seperti user premium)?

Yap, waktu pemakaian sehari dan dibedakan dengan user premium

User biasa limit pemakaian sehari nya: 30-40
User Premium Limit pemakaian sehari nya: 100-150

atau kalau perlu tambahkan cmd mining

Apa itu fungsi mining?
Kalau user kehabisan limit/point, user tersebut bisa menggunakan cmd mining untuk menambah random point (1-6)
Tapi user biasa maksimal mining nya 15x
kalau user premium 999x

**Comment by selyxn** [comment]
> > > Halo gan, mau request fitur
> > > bisa tolong buatin limit untuk command tertentu gak?
> > > sekalian fitur nsfw nya tambahin pornhubdl
> > > Terimakasih.
> > 
> > 
> > Oh iya, saya butuh info lebih lanjut. Limit ini tuh berupa apa? Waktu pemakaian sehari, user khusus (seperti user premium)?
> 
> Yap, waktu pemakaian sehari dan dibedakan dengan user premium
> 
> User biasa limit pemakaian sehari nya: 30-40
> User Premium Limit pemakaian sehari nya: 100-150
> 
> atau kalau perlu tambahkan cmd mining
> 
> Apa itu fungsi mining?
> Kalau user kehabisan limit/point, user tersebut bisa menggunakan cmd mining untuk menambah random point (1-6)
> Tapi user biasa maksimal mining nya 15x
> kalau user premium maksimal mining nya 999x

Terimakasih.

**Comment by selyxn** [comment]
> > > > Halo gan, mau request fitur
> > > > bisa tolong buatin limit untuk command tertentu gak?
> > > > sekalian fitur nsfw nya tambahin pornhubdl
> > > > Terimakasih.
> > > 
> > > 
> > > Oh iya, saya butuh info lebih lanjut. Limit ini tuh berupa apa? Waktu pemakaian sehari, user khusus (seperti user premium)?
> > 
> > 
 Yap, waktu pemakaian sehari dan dibedakan dengan user premium
 User biasa limit pemakaian sehari nya: 30-40
 User Premium Limit pemakaian sehari nya: 100-150
 atau kalau perlu tambahkan cmd mining
 Apa itu fungsi mining?
Kalau user kehabisan limit/point, user tersebut bisa menggunakan cmd mining untuk menambah random point (1-6)
Tapi user biasa maksimal mining nya 15x
kalau user premium maksimal mining nya 999x

Terimakasih.

**Comment by SlavyanDesu** [comment]
Keren juga ya, diusahakan ya sob sembari belajar juga saya nya wkwkwk

**Comment by selyxn** [comment]
> Keren juga ya, diusahakan ya sob sembari belajar juga saya nya wkwkwk

Hehe maaf cuma bisa ngebebanin gan
Semoga fitur bot nya makin berkelas ya ^^
Semangat wkwk

**Comment by selyxn** [comment]
Kalau ga keberatan fitur nsfw pornhub downlod video nya diupload duluan di github @SlavyanDesu <3

**Comment by SlavyanDesu** [comment]
> Kalau ga keberatan fitur nsfw pornhub downlod video nya diupload duluan di github @SlavyanDesu <3

Sudah ditambahkan, silakan cek: https://github.com/SlavyanDesu/BocchiBot/commit/e04e429234707575339ce58baf41536e092c1e02

Untuk command daily yang itu untuk sementara tidak diprioritaskan dulu ya
