### ISSUE TITLE
Bang bantu gw bisa ga?

### ISSUE THREAD

**Issue by akujeleksad** [SlavyanDesu/BocchiBot#60]
pas npm install
kan w udah install python ama udah add path
nah gw ikutin cara trobleshooting tulis :npm install --global --production --vs2015 --add-python-to-path windows-build-tools

nah disitu w stuck di :[  ................] / fetchMetadata: sill resolveWithNewModule universalify@0.1.2 checking installable status 
gmn bang biar enak kita ngomong di wa bang add wa gua bang soalnya gw baru kali ni nemu bot gratis secakep ini
wa.me/6281395771492 
tuh wa gw bang

**Comment by akujeleksad** [comment]
tolong bantu bang

**Comment by akujeleksad** [comment]
kan gw udah cd C:\Nama bot lu
nah terus gw npm i, disitu ga bisa terus w tanya lu dijam 2 nah gw ikutin kata lu
gw baca trobleshooting terus w tulis npm install --global --production -vs2015 --add-python-to-path windows-build-tools 
nah pas udah 2 bar disitu ngestuck

**Comment by akujeleksad** [comment]
sama gw udah run adminstator

**Comment by MrPawNO** [comment]
Coba git nya hapus dari awal
uninstall node js

lalu clone ulang git, install nodejs, install python run as admin :> Add to path, npm i

**Comment by MrPawNO** [comment]
Install visual studio juga, with workload C++ nya

**Comment by MrPawNO** [comment]
Ane juga kemarin error tapi ngakalin sampe 1-2 jam bisa

**Comment by akujeleksad** [comment]
Minta no wa nya biar enak gw aga bingung

**Comment by akujeleksad** [comment]
gw aga bingung bro gmn nih

**Comment by MrPawNO** [comment]
> gw aga bingung bro gmn nih

[ini](https://wa.me/+6285692655520)

**Comment by MrPawNO** [comment]
> Minta no wa nya biar enak gw aga bingung

[ini](https://wa.me/+6285692655520)

**Comment by SlavyanDesu** [comment]
# Announcement
Silakan update source code ke versi terbaru.
```bash
> git pull orgin master
```

# Changelog
* Mengganti method storing data dari menggunakan `Quick.db` ke JSON array object, karena banyak mengeluh error.
* Register kini hadir dengan model storing yang lebih simpel dengan JSON array object.
* Update string bahasa Inggris.
* Tersedia group WhatsApp untuk live support.
* Refactoring.

# Note
Ini akan menghapus data register dan XP/level user, jika kalian tidak ingin menghilangkannya kalian bisa copy data-data tersebut lalu memasukannya lagi secara manual. It can be helped though, sorry.
