### ISSUE TITLE
eror pas npm start

### ISSUE THREAD

**Issue by akujeleksad** [SlavyanDesu/BocchiBot#61]
Error: Could not locate the bindings file. Tried:
 → C:\BocchiBot-master\node_modules\better-sqlite3\build\better_sqlite3.node
 → C:\BocchiBot-master\node_modules\better-sqlite3\build\Debug\better_sqlite3.node
 → C:\BocchiBot-master\node_modules\better-sqlite3\build\Release\better_sqlite3.node
 → C:\BocchiBot-master\node_modules\better-sqlite3\out\Debug\better_sqlite3.node
 → C:\BocchiBot-master\node_modules\better-sqlite3\Debug\better_sqlite3.node
 → C:\BocchiBot-master\node_modules\better-sqlite3\out\Release\better_sqlite3.node
 → C:\BocchiBot-master\node_modules\better-sqlite3\Release\better_sqlite3.node
 → C:\BocchiBot-master\node_modules\better-sqlite3\build\default\better_sqlite3.node
 → C:\BocchiBot-master\node_modules\better-sqlite3\compiled\12.13.0\win32\x64\better_sqlite3.node
 → C:\BocchiBot-master\node_modules\better-sqlite3\addon-build\release\install-root\better_sqlite3.node
 → C:\BocchiBot-master\node_modules\better-sqlite3\addon-build\debug\install-root\better_sqlite3.node
 → C:\BocchiBot-master\node_modules\better-sqlite3\addon-build\default\install-root\better_sqlite3.node
 → C:\BocchiBot-master\node_modules\better-sqlite3\lib\binding\node-v72-win32-x64\better_sqlite3.node
    at bindings (C:\BocchiBot-master\node_modules\bindings\bindings.js:126:9)
    at Object.<anonymous> (C:\BocchiBot-master\node_modules\better-sqlite3\lib\database.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\BocchiBot-master\node_modules\better-sqlite3\lib\index.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:956:30) {
  tries: [
    'C:\\BocchiBot-master\\node_modules\\better-sqlite3\\build\\better_sqlite3.node',
    'C:\\BocchiBot-master\\node_modules\\better-sqlite3\\build\\Debug\\better_sqlite3.node',
    'C:\\BocchiBot-master\\node_modules\\better-sqlite3\\build\\Release\\better_sqlite3.node',
    'C:\\BocchiBot-master\\node_modules\\better-sqlite3\\out\\Debug\\better_sqlite3.node',
    'C:\\BocchiBot-master\\node_modules\\better-sqlite3\\Debug\\better_sqlite3.node',
    'C:\\BocchiBot-master\\node_modules\\better-sqlite3\\out\\Release\\better_sqlite3.node',
    'C:\\BocchiBot-master\\node_modules\\better-sqlite3\\Release\\better_sqlite3.node',
    'C:\\BocchiBot-master\\node_modules\\better-sqlite3\\build\\default\\better_sqlite3.node',
    'C:\\BocchiBot-master\\node_modules\\better-sqlite3\\compiled\\12.13.0\\win32\\x64\\better_sqlite3.node',
    'C:\\BocchiBot-master\\node_modules\\better-sqlite3\\addon-build\\release\\install-root\\better_sqlite3.node',
    'C:\\BocchiBot-master\\node_modules\\better-sqlite3\\addon-build\\debug\\install-root\\better_sqlite3.node',
    'C:\\BocchiBot-master\\node_modules\\better-sqlite3\\addon-build\\default\\install-root\\better_sqlite3.node',
    'C:\\BocchiBot-master\\node_modules\\better-sqlite3\\lib\\binding\\node-v72-win32-x64\\better_sqlite3.node'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bocchibot@0.4.2 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bocchibot@0.4.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Asus\AppData\Roaming\npm-cache\_logs\2020-12-18T15_27_55_882Z-debug.log

**Comment by SlavyanDesu** [comment]
Udah `npm install quick.db`? Di error tertulis bahwa module-nya belom keinstall

**Comment by akujeleksad** [comment]
oh oke!
