### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by rafaelmoris-hash** [SlavyanDesu/BocchiBot#63]
"Anda tidak memiliki level" grup ku ada member yg gadapet level bro padahal leveling enable

**Comment by rafaelmoris-hash** [comment]
dan saya ngetes pakai nomor lain undang bot kedalam grup dan sudah #leveling enable, sudah chat juga agar exp nambah, pas ketik level, bot reply "kamu belum memiliki level!"

**Comment by SlavyanDesu** [comment]
member sudah terdaftar?

**Comment by rafaelmoris-hash** [comment]
> member sudah terdaftar?

terdaftar apa bg? isRegistered? ku gapaksi fitur itu

btw exp nya masuk di database, ketika ketik #level error kek tulisan diatas

**Comment by SlavyanDesu** [comment]
hmmm, agan bisa buka file `json.sqlite` gak? ngodingnya pake software apa?

**Comment by SlavyanDesu** [comment]
atau nggak, hapus aja `json.sqlite`

**Comment by SlavyanDesu** [comment]
level nanti menyesuaikan xp kok

**Comment by SlavyanDesu** [comment]
tadi saya coba biar botnya error, tetep levelnya ngikutin jumlah xp

**Comment by SlavyanDesu** [comment]
sekalian ngab
```bash
> git pull origin master
```

**Comment by rafaelmoris-hash** [comment]
> atau nggak, hapus aja `json.sqlite`

maap bro ngerepotin.... kayaknya yg bug di level soalnya aku coba pakai nomor lain "Kamu tidak memiliki level", nomor 1 lgi & user lain yg sudah 1 grup gak kenapa2

**Comment by rafaelmoris-hash** [comment]
ceritanya 1 grup ku normal, lalu ada orang join... dia nimbrung, tetapi pas ketik level yg terjadi malah "Kamu tidak memiliki level!"

**Comment by rafaelmoris-hash** [comment]
if (currentLevel === null && checking === undefined) { aku pakai itu work bg mkshhhh

**Comment by SlavyanDesu** [comment]
iya tadi ku sudah update wkwk maaf ya botnya sering error, saya masih belajar

**Comment by rafaelmoris-hash** [comment]
> iya tadi ku sudah update wkwk maaf ya botnya sering error, saya masih belajar

gpp bg aku ngucapin mksh bnyk udah bantu dan sabar dngn aku wkwkwkwk.., semoga sukses

**Comment by rafaelmoris-hash** [comment]
![Screenshot_15](https://user-images.githubusercontent.com/75946163/102640840-ac30b700-418d-11eb-8f76-ba84a3f3c318.png)

lhhhh 1 menit lalu bs, skrng napa gitu wokwkowkoko

**Comment by rafaelmoris-hash** [comment]
hbs ku restart bs lgi bg

**Comment by SlavyanDesu** [comment]
bjir, haruskah gw buat group khusus konsultasi?

**Comment by rafaelmoris-hash** [comment]
> bjir, haruskah gw buat group khusus konsultasi?

kwkwk hayuuuu

**Comment by SlavyanDesu** [comment]
> ![Screenshot_15](https://user-images.githubusercontent.com/75946163/102640840-ac30b700-418d-11eb-8f76-ba84a3f3c318.png)
> 
> lhhhh 1 menit lalu bs, skrng cmd level napa gitu wokwkowkoko

ini ngomong-ngomong error dari whatsapp nya, wkwkwk tadi saya juga gitu

**Comment by SlavyanDesu** [comment]
> > bjir, haruskah gw buat group khusus konsultasi?
> 
> kwkwk hayuuuu

nomornya sob

**Comment by rafaelmoris-hash** [comment]
> > > bjir, haruskah gw buat group khusus konsultasi?
> > 
> > 
> > kwkwk hayuuuu
> 
> nomornya sob

sherlink bro supaya yg lain ikut jg

**Comment by SlavyanDesu** [comment]
https://chat.whatsapp.com/LTTm0HGvFRu7uU23mr7ZaR
