### ISSUE TITLE
Nih pas npm start bgini

### ISSUE THREAD

**Issue by akujeleksad** [SlavyanDesu/BocchiBot#66]
in JSON at position 151649 while parsing '{
npm ERR!   "name": "bocchibot",
npm ERR!   "version": '

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Asus\AppData\Roaming\npm-cache\_logs\2020-12-19T02_54_59_275Z-debug.log

**Comment by SlavyanDesu** [comment]
> in JSON at position 151649 while parsing '{
> npm ERR! "name": "bocchibot",
> npm ERR! "version": '
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\Asus\AppData\Roaming\npm-cache_logs\2020-12-19T02_54_59_275Z-debug.log

Udah hapus aja file bot nya, terus `git clone` lagi.
Sekarang bot nya udah nggak pake Quick.db biar gak error

**Comment by akujeleksad** [comment]
tetep g bisa bang

**Comment by SlavyanDesu** [comment]
> tetep g bisa bang

Udah dicoba kah? Kalau masih gak bisa, itu sih pc kamu

**Comment by SlavyanDesu** [comment]
@MrPawNO pernah error gini kah?

**Comment by akujeleksad** [comment]
C:\BocchiBot-master>cd c:\BocchiBot

c:\BocchiBot>npm install
 in JSON at position 151649 while parsing '{
npm ERR!   "name": "bocchibot",
npm ERR!   "version": '

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Asus\AppData\Roaming\npm-cache\_logs\2020-12-19T02_54_59_275Z-debug.log

c:\BocchiBot>cd C:\papa

C:\papa>npm install
npm ERR! Unexpected token
npm ERR!  in JSON at position 147982 while parsing '{
npm ERR!   "name": "bocchibot",
npm ERR!   "version": "0'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Asus\AppData\Roaming\npm-cache\_logs\2020-12-19T03_03_44_454Z-debug.log

**Comment by akujeleksad** [comment]
mungkin dari package lock nya bg

**Comment by SlavyanDesu** [comment]
> mungkin dari package lock nya bg

Mungkin, cobain aja hapus

**Comment by akujeleksad** [comment]
oke

**Comment by akujeleksad** [comment]
nah kan betul

**Comment by SlavyanDesu** [comment]
Sebelumnya pernah install bot nggak?

**Comment by akujeleksad** [comment]
> Sebelumnya pernah install bot nggak?

pernah

**Comment by akujeleksad** [comment]
install bot toby doang sih

**Comment by SlavyanDesu** [comment]
Udah bisa?

**Comment by akujeleksad** [comment]
liat wa ku bang biar enak ngomongnya

**Comment by akujeleksad** [comment]
lagi npm install
