### ISSUE TITLE
req fitur boleh kah?

### ISSUE THREAD

**Issue by akujeleksad** [SlavyanDesu/BocchiBot#67]
kalo boleh w req
#afk (yang di wa bang)
#astik auto stiker
#setname (ganti nama grup)

kalo orang naik level ada pemberi tauan misal
si member @anu naik level
bot langsung nulis : Wah si @anu naik level (level)!

**Comment by akujeleksad** [comment]
makasih bang sudah mau buat bot gratis secakep ini

**Comment by SlavyanDesu** [comment]
> kalo boleh w req
> #afk (yang di wa bang)
> #astik auto stiker
> #setname (ganti nama grup)
> 
> kalo orang naik level ada pemberi tauan misal
> si member @anu naik level
> bot langsung nulis : Wah si @anu naik level (level)!

buat notif naik level udah ada, tinggal hapus symbol comment nya

**Comment by SlavyanDesu** [comment]
https://github.com/SlavyanDesu/BocchiBot/blob/266f30f72fe62a9fa49e44719a0cf46b1c7589d1/message/index.js#L236-L239

**Comment by SlavyanDesu** [comment]
semua fitur di atas udah ditambahin, kecuali set group title karena command itu perlu [https://gumroad.com/l/open-wa?tier=Insiders%20Program](insiders key) yang berbayar. kalau ada contoh sc tanpa key bisa kontak gw

**Comment by akujeleksad** [comment]
bang klo econmy
boleh u tambahin ga?
misal
#bj bermain permainan
#kerja untuk dapetin uang
#bal cek uang

**Comment by SlavyanDesu** [comment]
> bang klo econmy
> boleh u tambahin ga?
> misal
> #bj bermain permainan
> #kerja untuk dapetin uang
> #bal cek uang

mainnya main apaan
