### ISSUE TITLE
afk

### ISSUE THREAD

**Issue by rafaelmoris-hash** [SlavyanDesu/BocchiBot#68]
![Screenshot_16](https://user-images.githubusercontent.com/75946163/102683249-12efb800-4202-11eb-9d71-a02165d4cd24.png)
![Screenshot_17](https://user-images.githubusercontent.com/75946163/102683252-16833f00-4202-11eb-8e14-cc244f661ca6.png)

**Comment by SlavyanDesu** [comment]
@rafaelmoris-hash gimana ngefixnya tadi sob
