### ISSUE TITLE
cara kita afk gmn?

### ISSUE THREAD

**Issue by akujeleksad** [SlavyanDesu/BocchiBot#69]
misalnya kan kita udah enable afk
nah kita cara afknya gmn

**Comment by SlavyanDesu** [comment]
Hah maksudnya? Afk ya afk, kalau orang mention kamu ntar botnya ngirim pesan

**Comment by akujeleksad** [comment]
ok

**Comment by rafaelmoris-hash** [comment]
> Hah maksudnya? Afk ya afk, kalau orang mention kamu ntar botnya ngirim pesan

nah bg aku mau req, sediakan cmd afk.., jika ada user yg mau afk.., gunain cmd itu
Kalau user nya sudah mengirim chat bot nya bilang "Blablablabla sudah tidak AFK!"

**Comment by SlavyanDesu** [comment]
Nanti lusa saya balik ngoding lagi ya
