### ISSUE TITLE
Ngab?

### ISSUE THREAD

**Issue by Suryapardana** [SlavyanDesu/BocchiBot#7]
**Question**
What would you like to ask?

Rubah menu dibagian mana ya?, Mau rubah soalnya gasuka model terlalu banyak teks

**Comment by SlavyanDesu** [comment]
`message/text/lang/ind.js` ini untuk bahasa Indonesia.
`message/text/lang/eng.js` ini untuk bahasa Inggris.

**Comment by SlavyanDesu** [comment]
> **Question**
> What would you like to ask?
> 
> Rubah menu dibagian mana ya?, Mau rubah soalnya gasuka model terlalu banyak teks

Jika tidak keberatan, agan bisa pull request text menu nya biar modelnya lebih simpel wkwkwk

**Comment by Suryapardana** [comment]
Oke makasih mank
