### ISSUE TITLE
Mau Tanya

### ISSUE THREAD

**Issue by Tanaka9531** [SlavyanDesu/BocchiBot#70]
**Question**
What would you like to ask?
![bandicam 2020-12-19 16-56-39-928](https://user-images.githubusercontent.com/73052642/102686601-5a367280-421b-11eb-9247-da9ebe20a18c.jpg)
ini knp ??

**Comment by SlavyanDesu** [comment]
> **Question**
> What would you like to ask?
> ![bandicam 2020-12-19 16-56-39-928](https://user-images.githubusercontent.com/73052642/102686601-5a367280-421b-11eb-9247-da9ebe20a18c.jpg)
> ini knp ??

Hapus file package-lock.json

**Comment by Tanaka9531** [comment]
> > **Question**
> > What would you like to ask?
> > ![bandicam 2020-12-19 16-56-39-928](https://user-images.githubusercontent.com/73052642/102686601-5a367280-421b-11eb-9247-da9ebe20a18c.jpg)
> > ini knp ??
> 
> Hapus file package-lock.json

oke thx

**Comment by SlavyanDesu** [comment]
Kalau udah solved, harap close issue

**Comment by Tanaka9531** [comment]
mau tanya kalau mau naikin level tuh gimana

**Comment by Tanaka9531** [comment]
kalau afk apa gunanya

**Comment by Tanaka9531** [comment]
auto sticker apa gunanya

**Comment by SlavyanDesu** [comment]
Dibaca di menu

**Comment by SlavyanDesu** [comment]
> mau tanya kalau mau naikin level tuh gimana

Setiap message di group dihitung 500-510 xp

**Comment by SlavyanDesu** [comment]
Join group wa aja kalau mau nanya nanya yang kayak gini

**Comment by Tanaka9531** [comment]
> Join group wa aja kalau mau nanya nanya yang kayak gini

ok
