### ISSUE TITLE
Enchantment for AFK command

### ISSUE THREAD

**Issue by SlavyanDesu** [SlavyanDesu/BocchiBot#71]
nah bg aku mau req, sediakan cmd afk.., jika ada user yg mau afk.., gunain cmd itu
Kalau user nya sudah mengirim chat bot nya bilang "Blablablabla sudah tidak AFK!"

_Originally posted by @rafaelmoris-hash in https://github.com/SlavyanDesu/BocchiBot/issues/69#issuecomment-748451402_

**Comment by SlavyanDesu** [comment]
This issue will be worked on soon.

**Comment by rahmat225** [comment]
Cannot access 'getAfk' before initialization gimana bang??

**Comment by SlavyanDesu** [comment]
> Cannot access 'getAfk' before initialization gimana bang??

#68

**Comment by MrPawNO** [comment]
> Cannot access 'getAfk' before initialization gimana bang??



> Cannot access 'getAfk' before initialization gimana bang??

Kalo diliat dari err log nya, itu cuma kesalahan peletakan fungsi afk nya ngab

Letakkan validator isAfkOn nya dibawah fungsi afk

**Comment by rafaelmoris-hash** [comment]
> > Cannot access 'getAfk' before initialization gimana bang??
> 
> > Cannot access 'getAfk' before initialization gimana bang??
> 
> Kalo diliat dari err log nya, itu cuma kesalahan peletakan fungsi afk nya ngab
> 
> Letakkan validator isAfkOn nya dibawah fungsi afk

yachh dijawab dluan hahaha

**Comment by SlavyanDesu** [comment]
wkwkw terima kasih sudah bantu jawab ngab @MrPawNO dan terima kasih udah niat mau jawab tapi keburu duluan @rafaelmoris-hash wkwkwkwk

**Comment by MrPawNO** [comment]
> wkwkw terima kasih sudah bantu jawab ngab @MrPawNO dan terima kasih udah niat mau jawab tapi keburu duluan @rafaelmoris-hash wkwkwkwk

Santuy gan saling bantu
oiya, untuk leaderboard pushname belom ku akalin ngab sibuk sekolah wkwkk jarang buka github juga, nanti kalau ada waktu ante tambahin pushname di input nya

**Comment by SlavyanDesu** [comment]
@rafaelmoris-hash https://github.com/SlavyanDesu/BocchiBot/commit/ae527914a124cad1773eaa34f1683eba0a93c54d done ya
