### ISSUE TITLE
Req Bang kalo boleh

### ISSUE THREAD

**Issue by LeviathanH** [SlavyanDesu/BocchiBot#72]
Add Fitur Playstore bang, sama shoppe uheuehueh, kalau boleh
makasih :)

**Comment by SlavyanDesu** [comment]
bisa dijelasin lebih lanjut fungsinya apa?

**Comment by LeviathanH** [comment]
> bisa dijelasin lebih lanjut fungsinya apa?

Playstore untuk mencari aplikasi di playstore ngab, misal Ps whastapp, nanti yg mncu semu query tetang wa
untuk shopee juga hampir sama, nanti nampilin semua query apa yg dicari

**Comment by SlavyanDesu** [comment]
> > bisa dijelasin lebih lanjut fungsinya apa?
> 
> Playstore untuk mencari aplikasi di playstore ngab, misal Ps whastapp, nanti yg mncu semu query tetang wa
> untuk shopee juga hampir sama, nanti nampilin semua query apa yg dicari

itu perlu api? kalau boleh tau api nya apa ya, nanti saya tinggal fetching aja

**Comment by LeviathanH** [comment]
> > > bisa dijelasin lebih lanjut fungsinya apa?
> > 
> > 
> > Playstore untuk mencari aplikasi di playstore ngab, misal Ps whastapp, nanti yg mncu semu query tetang wa
> > untuk shopee juga hampir sama, nanti nampilin semua query apa yg dicari
> 
> itu perlu api? kalau boleh tau api nya apa ya, nanti saya tinggal fetching aja

Di VHtear Bang ada @SlavyanDesu

**Comment by SlavyanDesu** [comment]
done
