### ISSUE TITLE
Error pada canvas

### ISSUE THREAD

**Issue by TheSploit** [SlavyanDesu/BocchiBot#74]
Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- D:\MathType\Whatsapp\BotTester\node_modules\canvas\lib\bindings.js
- D:\MathType\Whatsapp\BotTester\node_modules\canvas\lib\canvas.js
- D:\MathType\Whatsapp\BotTester\node_modules\canvas\index.js
- D:\MathType\Whatsapp\BotTester\node_modules\canvacord\libs\Trigger.js
- D:\MathType\Whatsapp\BotTester\node_modules\canvacord\src\Canvacord.js
- D:\MathType\Whatsapp\BotTester\node_modules\canvacord\index.js
- D:\MathType\Whatsapp\BotTester\\tobz.js

- D:\MathType\Whatsapp\BotTester\\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)
    at Function.Module._load (node:internal/modules/cjs/loader:763:27)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (D:\MathType\Whatsapp\BotTester\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\MathType\\Whatsapp\\BotTester\\\\node_modules\\canvas\\lib\\bindings.js',
    'D:\\MathType\\Whatsapp\\BotTester\\\\node_modules\\canvas\\lib\\canvas.js',
    'D:\\MathType\\Whatsapp\\BotTester\\\\node_modules\\canvas\\index.js',
    'D:\\MathType\\Whatsapp\\BotTester\\\\node_modules\\canvacord\\libs\\Trigger.js',
    'D:\\MathType\\Whatsapp\\BotTester\\\\node_modules\\canvacord\\src\\Canvacord.js',
    'D:\\MathType\\Whatsapp\\BotTester\\\\node_modules\\canvacord\\index.js',
    'D:\\MathType\\Whatsapp\\BotTester\\\\tobz.js',
    'D:\\MathType\\Whatsapp\\BotTester\\\\index.js'
  ]
}
npm ERR! code 1
npm ERR! path D:\MathType\Whatsapp\BotTester\
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c "node index.js"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Local\npm-cache\_logs\2020-12-19T14_25_30_864Z-debug.log

ad yg bisa bantu?

**Comment by MrPawNO** [comment]
> Error: Cannot find module '../build/Release/canvas.node'
> Require stack:
> 
> * D:\MathType\Whatsapp\BotTester\node_modules\canvas\lib\bindings.js
> * D:\MathType\Whatsapp\BotTester\node_modules\canvas\lib\canvas.js
> * D:\MathType\Whatsapp\BotTester\node_modules\canvas\index.js
> * D:\MathType\Whatsapp\BotTester\node_modules\canvacord\libs\Trigger.js
> * D:\MathType\Whatsapp\BotTester\node_modules\canvacord\src\Canvacord.js
> * D:\MathType\Whatsapp\BotTester\node_modules\canvacord\index.js
> * D:\MathType\Whatsapp\BotTester\tobz.js
> * D:\MathType\Whatsapp\BotTester\index.js
>   at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)
>   at Function.Module._load (node:internal/modules/cjs/loader:763:27)
>   at Module.require (node:internal/modules/cjs/loader:991:19)
>   at require (node:internal/modules/cjs/helpers:92:18)
>   at Object. (D:\MathType\Whatsapp\BotTester\node_modules\canvas\lib\bindings.js:3:18)
>   at Module._compile (node:internal/modules/cjs/loader:1102:14)
>   at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
>   at Module.load (node:internal/modules/cjs/loader:967:32)
>   at Function.Module._load (node:internal/modules/cjs/loader:807:14)
>   at Module.require (node:internal/modules/cjs/loader:991:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>   'D:\MathType\Whatsapp\BotTester\\node_modules\canvas\lib\bindings.js',
>   'D:\MathType\Whatsapp\BotTester\\node_modules\canvas\lib\canvas.js',
>   'D:\MathType\Whatsapp\BotTester\\node_modules\canvas\index.js',
>   'D:\MathType\Whatsapp\BotTester\\node_modules\canvacord\libs\Trigger.js',
>   'D:\MathType\Whatsapp\BotTester\\node_modules\canvacord\src\Canvacord.js',
>   'D:\MathType\Whatsapp\BotTester\\node_modules\canvacord\index.js',
>   'D:\MathType\Whatsapp\BotTester\\tobz.js',
>   'D:\MathType\Whatsapp\BotTester\\index.js'
>   ]
>   }
>   npm ERR! code 1
>   npm ERR! path D:\MathType\Whatsapp\BotTester
>   npm ERR! command failed
>   npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c "node index.js"
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\user\AppData\Local\npm-cache_logs\2020-12-19T14_25_30_864Z-debug.log
> 
> ad yg bisa bantu?

Coba di ulang lagi gan, git clone lagi terus npm i ato npm i canvacord

**Comment by TheSploit** [comment]
> > Error: Cannot find module '../build/Release/canvas.node'
> > Require stack:
> > 
> > * D:\MathType\Whatsapp\BotTester\node_modules\canvas\lib\bindings.js
> > * D:\MathType\Whatsapp\BotTester\node_modules\canvas\lib\canvas.js
> > * D:\MathType\Whatsapp\BotTester\node_modules\canvas\index.js
> > * D:\MathType\Whatsapp\BotTester\node_modules\canvacord\libs\Trigger.js
> > * D:\MathType\Whatsapp\BotTester\node_modules\canvacord\src\Canvacord.js
> > * D:\MathType\Whatsapp\BotTester\node_modules\canvacord\index.js
> > * D:\MathType\Whatsapp\BotTester\tobz.js
> > * D:\MathType\Whatsapp\BotTester\index.js
> >   at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)
> >   at Function.Module._load (node:internal/modules/cjs/loader:763:27)
> >   at Module.require (node:internal/modules/cjs/loader:991:19)
> >   at require (node:internal/modules/cjs/helpers:92:18)
> >   at Object. (D:\MathType\Whatsapp\BotTester\node_modules\canvas\lib\bindings.js:3:18)
> >   at Module._compile (node:internal/modules/cjs/loader:1102:14)
> >   at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
> >   at Module.load (node:internal/modules/cjs/loader:967:32)
> >   at Function.Module._load (node:internal/modules/cjs/loader:807:14)
> >   at Module.require (node:internal/modules/cjs/loader:991:19) {
> >   code: 'MODULE_NOT_FOUND',
> >   requireStack: [
> >   'D:\MathType\Whatsapp\BotTester\node_modules\canvas\lib\bindings.js',
> >   'D:\MathType\Whatsapp\BotTester\node_modules\canvas\lib\canvas.js',
> >   'D:\MathType\Whatsapp\BotTester\node_modules\canvas\index.js',
> >   'D:\MathType\Whatsapp\BotTester\node_modules\canvacord\libs\Trigger.js',
> >   'D:\MathType\Whatsapp\BotTester\node_modules\canvacord\src\Canvacord.js',
> >   'D:\MathType\Whatsapp\BotTester\node_modules\canvacord\index.js',
> >   'D:\MathType\Whatsapp\BotTester\tobz.js',
> >   'D:\MathType\Whatsapp\BotTester\index.js'
> >   ]
> >   }
> >   npm ERR! code 1
> >   npm ERR! path D:\MathType\Whatsapp\BotTester
> >   npm ERR! command failed
> >   npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c "node index.js"
> > 
> > npm ERR! A complete log of this run can be found in:
> > npm ERR! C:\Users\user\AppData\Local\npm-cache_logs\2020-12-19T14_25_30_864Z-debug.log
> > ad yg bisa bantu?
> 
> Coba di ulang lagi gan, git clone lagi terus npm i ato npm i canvacord

ap ya yg di gitcloe bang? sebenarny saya cmn nyomot beberapa fiturny aj afk ma leveling trus ketemu error di canvas and udh nyoba sih npm i canvas ma npm i canvacord ttp ajh gabisa

**Comment by SlavyanDesu** [comment]
I had a similar problem but I used canvas-prebuilt which is a drop-in replacement for canvas and I fixed it for doing this:
-npm install -g node-gyp
-node-gyp rebuild

_Originally posted in https://github.com/Automattic/node-canvas/issues/1499#issuecomment-591151575_

**Comment by TheSploit** [comment]
> I had a similar problem but I used canvas-prebuilt which is a drop-in replacement for canvas and I fixed it for doing this:
> -npm install -g node-gyp
> -node-gyp rebuild
> 
> _Originally posted in [Automattic/node-canvas#1499 (comment)](https://github.com/Automattic/node-canvas/issues/1499#issuecomment-591151575)_

gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@15.2.1 | win32 | x64
gyp info find Python using Python version 3.9.1 found at "C:\Python\Python39\python.exe"
gyp info find VS using VS2019 (16.3.29411.108) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python\Python39\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\MathType\\Whatsapp\\BotTester\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\user\\AppData\\Local\\node-gyp\\Cache\\15.2.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\user\\AppData\\Local\\node-gyp\\Cache\\15.2.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\user\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\15.2.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\MathType\\Whatsapp\\BotTester',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\MathType\\Whatsapp\\BotTester\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: D:\MathType\Whatsapp\BotTester) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\user\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:329:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:277:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\MathType\Whatsapp\BotTester
gyp ERR! node -v v15.2.1
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok

ist ok?

**Comment by TheSploit** [comment]
> > I had a similar problem but I used canvas-prebuilt which is a drop-in replacement for canvas and I fixed it for doing this:
> > -npm install -g node-gyp
> > -node-gyp rebuild
> > _Originally posted in [Automattic/node-canvas#1499 (comment)](https://github.com/Automattic/node-canvas/issues/1499#issuecomment-591151575)_
> 
> gyp info it worked if it ends with ok
> gyp info using node-gyp@7.1.2
> gyp info using node@15.2.1 | win32 | x64
> gyp info find Python using Python version 3.9.1 found at "C:\Python\Python39\python.exe"
> gyp info find VS using VS2019 (16.3.29411.108) found at:
> gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
> gyp info find VS run with --verbose for detailed information
> gyp info spawn C:\Python\Python39\python.exe
> gyp info spawn args [
> gyp info spawn args 'C:\Users\user\AppData\Roaming\npm\node_modules\node-gyp\gyp\gyp_main.py',
> gyp info spawn args 'binding.gyp',
> gyp info spawn args '-f',
> gyp info spawn args 'msvs',
> gyp info spawn args '-I',
> gyp info spawn args 'D:\MathType\Whatsapp\BotTester\build\config.gypi',
> gyp info spawn args '-I',
> gyp info spawn args 'C:\Users\user\AppData\Roaming\npm\node_modules\node-gyp\addon.gypi',
> gyp info spawn args '-I',
> gyp info spawn args 'C:\Users\user\AppData\Local\node-gyp\Cache\15.2.1\include\node\common.gypi',
> gyp info spawn args '-Dlibrary=shared_library',
> gyp info spawn args '-Dvisibility=default',
> gyp info spawn args '-Dnode_root_dir=C:\Users\user\AppData\Local\node-gyp\Cache\15.2.1',
> gyp info spawn args '-Dnode_gyp_dir=C:\Users\user\AppData\Roaming\npm\node_modules\node-gyp',
> gyp info spawn args '-Dnode_lib_file=C:\\Users\\user\\AppData\\Local\\node-gyp\\Cache\\15.2.1\\<(target_arch)\\node.lib',
> gyp info spawn args '-Dmodule_root_dir=D:\MathType\Whatsapp\BotTester',
> gyp info spawn args '-Dnode_engine=v8',
> gyp info spawn args '--depth=.',
> gyp info spawn args '--no-parallel',
> gyp info spawn args '--generator-output',
> gyp info spawn args 'D:\MathType\Whatsapp\BotTester\build',
> gyp info spawn args '-Goutput_dir=.'
> gyp info spawn args ]
> gyp: binding.gyp not found (cwd: D:\MathType\Whatsapp\BotTester) while trying to load binding.gyp
> gyp ERR! configure error
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack at ChildProcess.onCpExit (C:\Users\user\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:351:16)
> gyp ERR! stack at ChildProcess.emit (node:events:329:20)
> gyp ERR! stack at Process.ChildProcess._handle.onexit (node:internal/child_process:277:12)
> gyp ERR! System Windows_NT 10.0.18363
> gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\user\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
> gyp ERR! cwd D:\MathType\Whatsapp\BotTester
> gyp ERR! node -v v15.2.1
> gyp ERR! node-gyp -v v7.1.2
> gyp ERR! not ok
> 
> ist ok?

btw still got error

**Comment by SlavyanDesu** [comment]
error nya sama kayak di sini, banyak solusinya kok di situ silakan coba satu satu. ga bisa bantu yang lain hanya ini karena ini error dari module itu sendiri
https://github.com/nodejs/node-gyp/issues/702

**Comment by akujeleksad** [comment]
Coba di git ulang kalo ga download virtual studio work load C++

**Comment by TheSploit** [comment]
> Coba di git ulang kalo ga download virtual studio work load C++

oke dah bsa saya make node folder di sc ini hehe thanks oke saya hapus ya, soalny udh Done
