### ISSUE TITLE
Autosticker problem in the group

### ISSUE THREAD

**Issue by gabrielwsy** [SlavyanDesu/BocchiBot#77]
Hello, I'm having autosticker problems in the group, when I activate it in the group and send the images to be made the stickers, the bot does not do and this error is showing up on the console, you know how to solve?
![image](https://user-images.githubusercontent.com/40281950/102698192-535b3000-421a-11eb-873d-f9de975fe1b4.png)

**Comment by SlavyanDesu** [comment]
Hi, thanks for submitting the issue. I will investigate it as fast as possible.

**Comment by gabrielwsy** [comment]
Okay thank you

**Comment by SlavyanDesu** [comment]
I've deleted some buggy function that doesn't really matter. Please update the source code to the latest version using:
```bash
> git pull origin master
```

**Comment by SlavyanDesu** [comment]
If another error occur, just send it here. I need to get some rest, it's 03:20 AM here lol.

**Comment by SlavyanDesu** [comment]
In case the issue has been really solved, considering to close this.

**Comment by gabrielwsy** [comment]
> I've deleted some buggy function that doesn't really matter. Please update the source code to the latest version by typing:
> 
> ```shell
> > git pull origin master
> ```
I came back, I will test again, I will be back in 5min.

**Comment by gabrielwsy** [comment]
> In case the issue has been really solved, considering to close this.

This problem has been resolved, thank you very much. Have a nice rest.
Closing the topic.
