### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by romystuas** [SlavyanDesu/BocchiBot#78]
Aku barusan update sc bro lalu coba level tpi error:
![Screenshot_21](https://user-images.githubusercontent.com/75922906/102707291-45fe7e00-42cc-11eb-83ff-bb92910c1575.png)

pdhl folder bot ku ada file levelcard na
![Screenshot_20](https://user-images.githubusercontent.com/75922906/102707299-557dc700-42cc-11eb-8840-0afb4998a8e7.png)

**Comment by rafaelmoris-hash** [comment]
> Aku barusan update sc bro lalu coba level tpi error:
> ![Screenshot_21](https://user-images.githubusercontent.com/75922906/102707291-45fe7e00-42cc-11eb-83ff-bb92910c1575.png)
> 
> pdhl folder bot ku ada file levelcard na
> ![Screenshot_20](https://user-images.githubusercontent.com/75922906/102707299-557dc700-42cc-11eb-8840-0afb4998a8e7.png)

sama

**Comment by TheSploit** [comment]
> > Aku barusan update sc bro lalu coba level tpi error:
> > ![Screenshot_21](https://user-images.githubusercontent.com/75922906/102707291-45fe7e00-42cc-11eb-83ff-bb92910c1575.png)
> > pdhl folder bot ku ada file levelcard na
> > ![Screenshot_20](https://user-images.githubusercontent.com/75922906/102707299-557dc700-42cc-11eb-8840-0afb4998a8e7.png)
> 
> sama

cek lagi gayn pastikan udh bener lokasiny

**Comment by romystuas** [comment]
> > > Aku barusan update sc bro lalu coba level tpi error:
> > > ![Screenshot_21](https://user-images.githubusercontent.com/75922906/102707291-45fe7e00-42cc-11eb-83ff-bb92910c1575.png)
> > > pdhl folder bot ku ada file levelcard na
> > > ![Screenshot_20](https://user-images.githubusercontent.com/75922906/102707299-557dc700-42cc-11eb-8840-0afb4998a8e7.png)
> > 
> > 
> > sama
> 
> cek lagi gayn pastikan udh bener lokasiny

![Screenshot_22](https://user-images.githubusercontent.com/75922906/102708636-7b0fce00-42d6-11eb-8671-d7bc7e324db1.png)
write & read ny dah bener

**Comment by SlavyanDesu** [comment]
> > > > Aku barusan update sc bro lalu coba level tpi error:
> > > > ![Screenshot_21](https://user-images.githubusercontent.com/75922906/102707291-45fe7e00-42cc-11eb-83ff-bb92910c1575.png)
> > > > pdhl folder bot ku ada file levelcard na
> > > > ![Screenshot_20](https://user-images.githubusercontent.com/75922906/102707299-557dc700-42cc-11eb-8840-0afb4998a8e7.png)
> > > 
> > > 
> > > sama
> > 
> > 
> > cek lagi gayn pastikan udh bener lokasiny
> 
> ![Screenshot_22](https://user-images.githubusercontent.com/75922906/102708636-7b0fce00-42d6-11eb-8671-d7bc7e324db1.png)
> write & read ny dah bener

Coba bagian itu diganti jadi ini bro:
```js
canvas.write(buffer, `${pushname}.png`)
await bocchi.sendFile(from, `${pushname}.png`, `${pushname}.png`, '', id)
fs.unlinkSync(`${pushname}.png`, function (err) {
    if (err) console.error(err)
    console.log('File deleted!')
})
```
Belum sempet coba soalnya lagi ada urusan.

**Comment by SlavyanDesu** [comment]
Ngomong-ngomong, foto levelnya terkirim atau nggak?
