### ISSUE TITLE
:)

### ISSUE THREAD

**Issue by MrPawNO** [SlavyanDesu/BocchiBot#8]
Boleh ikut berkontribusi ga?

// Teks to Sticker
        case 'ttp':
        if (args.length == 0) return vf.reply(from, `Untuk mengubah teks menjadi stiker, ketik ${prefix}ttp teks\n\nContoh: ${prefix}ttp fikri ganteng`, id)
        axios.get(`https://st4rz.herokuapp.com/api/ttp?kata=${body.slice(5)}`)
        .then(res => {
        vf.sendImageAsSticker(from, res.data.result)
        console.log(`Sticker Processed for ${processTime(t, moment())} Second`)
        })
        break

// Fun Menu (Seberapa Gay)
case 'howgay':
		if (args.length == 0) return vf.reply(from, `Untuk mengetahui seberapa gay seseorang gunakan ${prefix}howgay namanya\n\nContoh: #howgay burhan`, id)
            fetch('https://raw.githubusercontent.com/MrPawNO/howgay/main/howgay.txt')
            .then(res => res.text())
            .then(body => {
                let splithowgay = body.split('\n')
                let randomhowgay = splithowgay[Math.floor(Math.random() * splithowgay.length)]
                vf.reply(from, randomhowgay, id)
            })
            .catch(() => {
                vf.reply(from, 'Ada yang Error!', id)
            })
            break

//Kata-kata motivasi
case 'motivasi':
            fetch('https://raw.githubusercontent.com/MrPawNO/motivasi/main/motivasi.txt')
            .then(res => res.text())
            .then(body => {
                let splitmotivasi = body.split('\n')
                let randommotivasi = splitmotivasi[Math.floor(Math.random() * splitmotivasi.length)]
                vf.reply(from, randommotivasi, id)
            })
            .catch(() => {
                vf.reply(from, 'Ada yang Error!', id)
            })
            break

**Comment by SlavyanDesu** [comment]
> Boleh ikut berkontribusi ga?
> 
> // Teks to Sticker
> case 'ttp':
> if (args.length == 0) return vf.reply(from, `Untuk mengubah teks menjadi stiker, ketik ${prefix}ttp teks\n\nContoh: ${prefix}ttp fikri ganteng`, id)
> axios.get(`https://st4rz.herokuapp.com/api/ttp?kata=${body.slice(5)}`)
> .then(res => {
> vf.sendImageAsSticker(from, res.data.result)
> console.log(`Sticker Processed for ${processTime(t, moment())} Second`)
> })
> break
> 
> // Fun Menu (Seberapa Gay)
> case 'howgay':
> if (args.length == 0) return vf.reply(from, `Untuk mengetahui seberapa gay seseorang gunakan ${prefix}howgay namanya\n\nContoh: #howgay burhan`, id)
> fetch('https://raw.githubusercontent.com/MrPawNO/howgay/main/howgay.txt')
> .then(res => res.text())
> .then(body => {
> let splithowgay = body.split('\n')
> let randomhowgay = splithowgay[Math.floor(Math.random() * splithowgay.length)]
> vf.reply(from, randomhowgay, id)
> })
> .catch(() => {
> vf.reply(from, 'Ada yang Error!', id)
> })
> break
> 
> //Kata-kata motivasi
> case 'motivasi':
> fetch('https://raw.githubusercontent.com/MrPawNO/motivasi/main/motivasi.txt')
> .then(res => res.text())
> .then(body => {
> let splitmotivasi = body.split('\n')
> let randommotivasi = splitmotivasi[Math.floor(Math.random() * splitmotivasi.length)]
> vf.reply(from, randommotivasi, id)
> })
> .catch(() => {
> vf.reply(from, 'Ada yang Error!', id)
> })
> break

Boleh bangeeeet, silakan pull request. Otomatis masuk jadi kontributor <3

**Comment by MrPawNO** [comment]
> > Boleh ikut berkontribusi ga?
> > // Teks to Sticker
> > case 'ttp':
> > if (args.length == 0) return vf.reply(from, `Untuk mengubah teks menjadi stiker, ketik ${prefix}ttp teks\n\nContoh: ${prefix}ttp fikri ganteng`, id)
> > axios.get(`https://st4rz.herokuapp.com/api/ttp?kata=${body.slice(5)}`)
> > .then(res => {
> > vf.sendImageAsSticker(from, res.data.result)
> > console.log(`Sticker Processed for ${processTime(t, moment())} Second`)
> > })
> > break
> > // Fun Menu (Seberapa Gay)
> > case 'howgay':
> > if (args.length == 0) return vf.reply(from, `Untuk mengetahui seberapa gay seseorang gunakan ${prefix}howgay namanya\n\nContoh: #howgay burhan`, id)
> > fetch('https://raw.githubusercontent.com/MrPawNO/howgay/main/howgay.txt')
> > .then(res => res.text())
> > .then(body => {
> > let splithowgay = body.split('\n')
> > let randomhowgay = splithowgay[Math.floor(Math.random() * splithowgay.length)]
> > vf.reply(from, randomhowgay, id)
> > })
> > .catch(() => {
> > vf.reply(from, 'Ada yang Error!', id)
> > })
> > break
> > //Kata-kata motivasi
> > case 'motivasi':
> > fetch('https://raw.githubusercontent.com/MrPawNO/motivasi/main/motivasi.txt')
> > .then(res => res.text())
> > .then(body => {
> > let splitmotivasi = body.split('\n')
> > let randommotivasi = splitmotivasi[Math.floor(Math.random() * splitmotivasi.length)]
> > vf.reply(from, randommotivasi, id)
> > })
> > .catch(() => {
> > vf.reply(from, 'Ada yang Error!', id)
> > })
> > break
> 
> Boleh bangeeeet, silakan pull request. Otomatis masuk jadi kontributor <3

Itu ada yg perlu agan rubah dulu sc nya ngab biar sinkron sama bot agan

**Comment by SlavyanDesu** [comment]
> > > Boleh ikut berkontribusi ga?
> > > // Teks to Sticker
> > > case 'ttp':
> > > if (args.length == 0) return vf.reply(from, `Untuk mengubah teks menjadi stiker, ketik ${prefix}ttp teks\n\nContoh: ${prefix}ttp fikri ganteng`, id)
> > > axios.get(`https://st4rz.herokuapp.com/api/ttp?kata=${body.slice(5)}`)
> > > .then(res => {
> > > vf.sendImageAsSticker(from, res.data.result)
> > > console.log(`Sticker Processed for ${processTime(t, moment())} Second`)
> > > })
> > > break
> > > // Fun Menu (Seberapa Gay)
> > > case 'howgay':
> > > if (args.length == 0) return vf.reply(from, `Untuk mengetahui seberapa gay seseorang gunakan ${prefix}howgay namanya\n\nContoh: #howgay burhan`, id)
> > > fetch('https://raw.githubusercontent.com/MrPawNO/howgay/main/howgay.txt')
> > > .then(res => res.text())
> > > .then(body => {
> > > let splithowgay = body.split('\n')
> > > let randomhowgay = splithowgay[Math.floor(Math.random() * splithowgay.length)]
> > > vf.reply(from, randomhowgay, id)
> > > })
> > > .catch(() => {
> > > vf.reply(from, 'Ada yang Error!', id)
> > > })
> > > break
> > > //Kata-kata motivasi
> > > case 'motivasi':
> > > fetch('https://raw.githubusercontent.com/MrPawNO/motivasi/main/motivasi.txt')
> > > .then(res => res.text())
> > > .then(body => {
> > > let splitmotivasi = body.split('\n')
> > > let randommotivasi = splitmotivasi[Math.floor(Math.random() * splitmotivasi.length)]
> > > vf.reply(from, randommotivasi, id)
> > > })
> > > .catch(() => {
> > > vf.reply(from, 'Ada yang Error!', id)
> > > })
> > > break
> > 
> > 
> > Boleh bangeeeet, silakan pull request. Otomatis masuk jadi kontributor <3
> 
> Itu ada yg perlu agan rubah dulu sc nya ngab biar sinkron sama bot agan


Baik, nanti saya modifikasi script yang agan buat lalu disesuaikan. Ntar saya kirim sini wkwkwk

**Comment by SlavyanDesu** [comment]
@MrPawNO gan, nih sudah saya modifikasi. Agan tinggal edit aja di `message/index.js`.
```js
             // Fun
            case 'howgay':
                if (!isRegistered) return await bocchi.reply(from, ind.notRegistered(), id)
                if (!q) return await bocchi.reply(from, ind.wrongFormat(), id)
                fun.howgay(q)
                    .then(async (body) => {
                        let splitHowGay = body.split('\n')
                        let randomHowGay = splitHowGay[Math.floor(Math.random() * splitHowGay.length)]
                        await bocchi.reply(from, randomHowGay, id)
                    })
                    .catch(async (err) => {
                        console.error(err)
                        await bocchi.reply(from, err, id)
                    })
            break
            case 'motivates':
            case 'motivasi':
                if (!isRegistered) return await bocchi.reply(from, ind.notRegistered(), id)
                fun.motivasi()
                    .then(async (body) => {
                        let splitMotivasi = body.split('\n')
                        let randomMotivasi = splitMotivasi[Math.floor(Math.random() * splitMotivasi.length)]
                        await bocchi.reply(from, randomMotivasi, id)
                    })
                    .catch(async (err) => {
                        console.error(err)
                        await bocchi.reply(from, err, id)
                    })
            break

            // Sticker
            case 'stickertext':
            case 'stikerteks':
                if (!isRegistered) return await bocchi.reply(from, ind.notRegistered(), id)
                if (!q) return await bocchi.reply(from, ind.wrongFormat(), id)
                await bocchi.reply(from, ind.wait(), id)
                sticker.stickertext(q)
                    .then(async ({ result }) => {
                        await bocchi.sendImageAsSticker(from, result)
                        .then(async () => {
                            await bocchi.sendText(from, ind.ok())
                            console.log(`Sticker processed for ${processTime(t, moment())} seconds`)
                        })
                    })
                    .catch(async (err) => {
                        console.error(err)
                        await bocchi.reply(from, err, id)
                    })
            break
```
