### ISSUE TITLE
Help gan

### ISSUE THREAD

**Issue by Suryapardana** [SlavyanDesu/BocchiBot#9]
### EROR SAAT ADD
![Screenshot_2020-12-08-17-49-26-219_com whatsapp](https://user-images.githubusercontent.com/47344288/101475377-ed9bb800-397e-11eb-96be-1939e0b9dc79.jpg)

**Comment by SlavyanDesu** [comment]
> ### EROR SAAT ADD
> ![Screenshot_2020-12-08-17-49-26-219_com whatsapp](https://user-images.githubusercontent.com/47344288/101475377-ed9bb800-397e-11eb-96be-1939e0b9dc79.jpg)

Ini karena prefix agan `d` dan berspasi. Sedangkan di script itu gaboleh ada spasi, liat yang `if (args.length !== 1)`:
https://github.com/SlavyanDesu/BocchiBot/blob/6c222cd45d2ffc302e6eb908d7d566bb9d73b2d6/message/index.js#L803-L816
Coba prefixnya ganti ke yang lain seperti `!` atau `/`.

**Comment by Suryapardana** [comment]
Baik gan
